# 03 -- Collections: 50 Songs About a Keyword

Returns **50 globally most-played songs** matching a given keyword (love, war, happiness, loneliness, money),
using lyrics-based content filtering.

### Algorithm

Three approaches are compared:

1. **Baseline** -- exact keyword match: count occurrences of the keyword in each
   track's lyrics, apply a threshold, then sort by total play count.
2. **Word2Vec** -- expand the keyword with semantically similar tokens via a
   pre-trained word2vec model, then combine their lyric counts.
3. **Classification** -- label tracks as "about X" vs "not about X" using
   keyword presence, train a classifier on the labelled set, then predict
   scores for the remaining tracks.

### Output columns
| Column | Description |
|--------|-------------|
| `rank` | 1-50 index, by total play count (descending) |
| `artist` | Artist name |
| `title` | Track title |
| `play_count` | Total plays across all users |

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from src.data.loader import MySpotifyRecommender
from src.models.collections import (
    collection_baseline,
    collection_classification,
    collection_classification_compare,
    collection_word2vec,
)

In [2]:
rs = MySpotifyRecommender.from_files(Path.cwd().parent / "data", download=True, triplets_sample_rows=100_000)

Data dir    : /home/samy/MySpotify/data
Source      : cleaned CSVs (/home/samy/MySpotify/data/csv)

  tracks      (1000000, 4)
  genres      (280831, 3)
  triplets    (100000, 3)
  lyrics_long (16845822, 3)

---
## Research

In [3]:
KEYWORDS = ["love", "war", "happiness", "loneliness", "money"]

### Approach 1 -- Baseline (exact keyword match)

In [4]:
baseline_results = collection_baseline(rs, KEYWORDS, n=1, top_n=50)
for i in range(len(KEYWORDS)):
    keyword = KEYWORDS[i]
    result = baseline_results.get(keyword, "No results found")
    print(f"Keyword: {keyword}")
    display(result)
    print("\n")

Keyword: love

,artist,title,play_count
1,OneRepublic,Secrets,712.0
2,Five Iron Frenzy,Canada,552.0
3,Train,Marry Me,488.0
4,Tub Ring,Invalid,415.0
5,Train,Hey_ Soul Sister,403.0
6,Lil Wayne / Eminem,Drop The World,363.0
7,Florence + The Machine,Cosmic Love,339.0
8,Bill Withers,Make Love To Your Mind,322.0
9,Lady GaGa,Speechless,289.0
10,Panic At The Disco,Behind The Sea [Live In Chicago],269.0
11,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,266.0
12,The Dodos,Fools,245.0
13,Taylor Swift,Love Story,238.0
14,Angels and Airwaves,The Gift,236.0
15,Kix,Girl Money,233.0
16,La Roux,Bulletproof,232.0
17,Coldplay,Clocks,217.0
18,The Black Keys,Tighten Up,216.0
19,Mike And The Mechanics,A Beggar On A Beach Of Gold,210.0
20,Beastie Boys,Unite (2009 Digital Remaster),202.0
21,Rise Against,Savior,200.0
22,Beyoncé,Halo,195.0
23,Sheena Easton,Strut (1993 Digital Remaster),191.0
24,The Verve,Bitter Sweet Symphony,182.0
25,Eminem,Mockingbird,176.0
26,Julia Fordham,I Thought It Was You,175.0
27,Guns N' Roses,Paradise City,170.0
28,Albert Hammond Jr.,Everyone Gets A Star,168.0
29,Eminem,Without Me,166.0
30,Pearl Jam,The End,162.0
31,Radiohead,Creep (Explicit),160.0
32,Damn Yankees,Come Again (Album Version),155.0
33,OneRepublic,All The Right Moves,152.0
34,Sheryl Crow,Picture,146.0
35,The Black Keys,Howlin For You,144.0
36,Taylor Swift,You Belong With Me,143.0
37,Metallica,Master Of Puppets,142.0
38,Future Of The Left,Yin / Post-Yin,141.0
39,Evanescence,Bring Me To Life,141.0
40,Tenth Avenue North,Times,140.0
41,Eagles,Hotel California,139.0
42,Arctic Monkeys,Dancing Shoes,138.0
43,Pavement,Mercy:The Laundromat,133.0
44,Jason Derulo,Whatcha Say,132.0
45,Owl City,Vanilla Twilight,130.0
46,The Postal Service,Such Great Heights,129.0
47,Eminem / Nate Dogg,'Till I Collapse,121.0
48,John Mayer,Half Of My Heart,117.0
49,Jewel,Sometimes It Be That Way,116.0
50,P.M. Dawn,Id Die Without You,115.0

Keyword: war

,artist,title,play_count
1,Taylor Swift,Love Story,238.0
2,Taylor Swift,You Belong With Me,143.0
3,Carpenters,(They Long To Be) Close To You,140.0
4,Miley Cyrus,Party In The U.S.A.,124.0
5,Jewel,Sometimes It Be That Way,116.0
6,Jack Johnson,Breakdown,102.0
7,Margot & The Nuclear So And So's,Dress Me Like a Clown,84.0
8,Stan Ridgway,Drive_ She Said,82.0
9,Five Finger Death Punch,Bad Company,78.0
10,Lily Allen,LDN,76.0
11,Alicia Keys,Empire State Of Mind (Part II) Broken Down,76.0
12,Black Eyed Peas,Pump It,68.0
13,Taylor Swift,I'm Only Me When I'm With You,68.0
14,Lipps Inc.,Funkytown,61.0
15,Massive Attack,Splitting The Atom,61.0
16,Eddy Grant,Electric Avenue,58.0
17,Erykah Badu,Window Seat,55.0
18,Stan Ridgway,Salesman,53.0
19,Tevin Campbell,I'm Ready (Album Version),52.0
20,Black Eyed Peas,Hey Mama,47.0
21,ENUR Feat NATASJA,Calabria 2007,46.0
22,Sean Paul,Baby Boy [feat. Beyonce],45.0
23,The Avett Brothers,Shame,43.0
24,Marilyn Manson,This Is Halloween,43.0
25,Beirut,Elephant Gun,41.0
26,Eric Clapton,Willie And The Hand Jive,40.0
27,Sea Wolf,You're A Wolf (Album),39.0
28,Justin Timberlake,LoveStoned/I Think She Knows,38.0
29,Yellowcard,Ocean Avenue,38.0
30,Postal Service,Brand New Colony (Album),37.0
31,dEUS,Everybody's Weird,36.0
32,Delirious?,Paint The Town Red,36.0
33,Carpenters,Jambalaya (On The Bayou),35.0
34,Shawn Mullins,Lullaby,34.0
35,James Morrison,The Last Goodbye,33.0
36,Edwyn Collins,A Girl Like You,33.0
37,The Darkness,Hazel Eyes [Album Version],31.0
38,Aesop Rock,Catacomb Kids,31.0
39,Fleet Foxes,Tiger Mountain Peasant Song,29.0
40,Tenpole Tudor,Swords Of A Thousand Men,29.0
41,GZA/Genius / Killah Priest,Beneath The Surface,29.0
42,The Avett Brothers,The Weight Of Lies,28.0
43,Billy Joel,It's Still Rock And Roll To Me,28.0
44,Gorillaz,Feel Good Inc (Album Version),28.0
45,Jason Aldean,Big Green Tractor,27.0
46,Luke Bryan,Someone Else Calling You Baby,27.0
47,Modest Mouse,The World At Large,27.0
48,Chuck Ragan,Hearts Of Stone,27.0
49,Belle & Sebastian,If You Find Yourself Caught In Love,27.0
50,Lupe Fiasco feat. Biship G and Nikki Jean,Little Weapon (feat. Bishop G and Nikki Jean) ...,27.0

Keyword: happiness

'No results found'

Keyword: loneliness

'No results found'

Keyword: money

,artist,title,play_count
1,Fokofpolisiekar,Hemel Op Die Platteland,109.0
2,Yann Tiersen,A Quai,83.0
3,Céline Dion,Je ne vous oublie pas,78.0
4,Paris Combo,Prête A Porter,47.0
5,Macaco,Mama Tierra,29.0
6,Regina Spektor,Consequence Of Sounds,24.0
7,Belanova,Niño,22.0
8,Plastic Bertrand,Ca plane pour moi,21.0
9,Yelle,Amour Du Sol,21.0
10,Mecano,Sólo Soy Una Persona,20.0
11,La Rue Ketanou,Les derniers aventuriers,19.0
12,Les Nubians,Saravah,17.0
13,Spinvis,Smalfilm,16.0
14,Los Tipitos,Campanas En La Noche,15.0
15,Rob De Nijs,Het Dorp,15.0
16,Sondre Lerche,Hoisting The Flag,15.0
17,Gerard Lenorman,Michèle,15.0
18,Kate Ryan,Nos regards Qui M'Enflamment,14.0
19,Carla Bruni,Raphael,14.0
20,Yelle,Mal Poli,13.0
21,Kate Bush,Joanni,13.0
22,Metric,Poster Of A Girl,13.0
23,Fernando Delgadillo,Entre Pairos y Derivas (en vivo),13.0
24,Superbus,Butterfly,12.0
25,Thievery Corporation,Shadows Of Ourselves,12.0
26,Carla Bruni,L'Excessive,11.0
27,Mylène Farmer,Porno Graphique,10.0
28,Rob De Nijs,Ze Rook Naar Rozen,10.0
29,F4,Can't Help Falling In Love,10.0
30,Mecano,Otro Muerto,10.0
31,Calle 13 Featuring Café Tacuba,No Hay Nadie Como Tú,10.0
32,Kate Ryan,Désenchantée,10.0
33,Grégory Lemarchal,Ecris L'Histoire,9.0
34,Panteón Rococó,La Carencia,9.0
35,Étienne Daho,Le Premier Jour (Du Reste De Ta Vie) (Remix 05),9.0
36,Julien Clerc,Partir (Live),9.0
37,The Streets,Blinded By The Lights [Nero Remix],8.0
38,Thievery Corporation,Le Monde,8.0
39,Amel Bent,Où je vais,8.0
40,Pearl Jam,Not For You,7.0
41,Silvio Rodríguez,Yo digo que las estrellas,7.0
42,El Cuarteto De Nos,Ya No Se Que Hacer Conmigo,7.0
43,Kaizers Orchestra,Resistansen,6.0
44,Jane Birkin,Baby Alone In Babylone (Live),6.0
45,Solefald,Christiania (e Munch Commemoration),6.0
46,Gérard Manset,Le Masque Sur Le Mur,6.0
47,Fernando Delgadillo,Navegante,6.0
48,Yuri,El espejo (Album),6.0
49,Rohff,Le Pouvoir,6.0
50,Camélia Jordana,Tombée de haut,5.0

### Approach 2 -- Word2Vec (expanded keywords)

In [5]:
w2v_results = collection_word2vec(rs, KEYWORDS, n=50, top_n=50)
for kw, df in w2v_results.items():
    print(f"\n{'='*50}")
    print(f"  Collection: {kw.upper()}")
    print(f"{'='*50}")
    display(df)

==================================================
  Collection: LOVE
==================================================

,artist,title,play_count
1,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,266.0
2,Beastie Boys,Unite (2009 Digital Remaster),202.0
3,Eminem,Mockingbird,176.0
4,Guns N' Roses,Paradise City,170.0
5,Eminem,Without Me,166.0
6,Miley Cyrus,Party In The U.S.A.,124.0
7,Eminem / Nate Dogg,'Till I Collapse,121.0
8,Guns N' Roses,Don't Cry (Original),82.0
9,Aesop Rock,None Shall Pass (Main),72.0
10,Reality Check,Masquerade (Reality Check Album Version),63.0
11,Daft Punk,Around The World (Radio Edit),62.0
12,Immortal Technique,Peruvian Cocaine,60.0
13,Chiddy Bang,Opposite Of Adults,56.0
14,Blink-182,Feeling This,55.0
15,Vanessa Williams,Colors Of The Wind,54.0
16,Snow Patrol,The Lightning Strike,49.0
17,Black Eyed Peas,Hey Mama,47.0
18,R. Kelly,The World's Greatest,46.0
19,ENUR Feat NATASJA,Calabria 2007,46.0
20,N.W.A.,I Ain't Tha 1 (Explicit),44.0
21,Steve Goodman,A Dying Cub Fan's Last Request,41.0
22,Tinie Tempah,Pass Out (Instrumental),41.0
23,Gang Starr,Soliloquy Of Chaos (Explicit),39.0
24,Michael Jackson,Thriller,38.0
25,Flobots,Anne Braden,36.0
26,Bright Eyes,Lua (Single Version),36.0
27,The Lonely Island,Like A Boss,35.0
28,Ying Yang Twins ft. Lil Jon & The East Side Boyz,Salt Shakers,35.0
29,Flobots,Stand Up,35.0
30,Regina Spektor,Daniel Cowman,34.0
31,Dr. Dre / Eminem,Forgot About Dre,34.0
32,Rich Boy / Andre 3000 / Jim Jones / Nelly / Mu...,Throw Some D's Remix,32.0
33,The Mars Volta,Tetragrammaton,32.0
34,Tears For Fears,Sowing The Seeds Of Love,32.0
35,The B-52's,Love Shack,31.0
36,K-OS,Freeze,31.0
37,Fall Out Boy,Sugar_ We're Goin Down,31.0
38,Aesop Rock,Catacomb Kids,31.0
39,The Lonely Island / Julian Casablancas,Boombox,30.0
40,Jason Mraz,The Remedy (I Won't Worry) (New EQ'd LP Version),30.0
41,Binary Star,Solar Powered,30.0
42,P. Diddy,I Need A Girl (Part One) (Featuring Usher & Lo...,30.0
43,GZA/Genius / Killah Priest,Beneath The Surface,29.0
44,Eddie Vedder,Hard Sun,29.0
45,Eminem / Dr. Dre / 50 Cent,Crack A Bottle,29.0
46,Rihanna,Music Of The Sun,29.0
47,Florence + The Machine,Bird Song,28.0
48,the bird and the bee,You're A Cad,27.0
49,Destiny's Child,Jumpin'_ Jumpin',27.0
50,Lupe Fiasco feat. Biship G and Nikki Jean,Little Weapon (feat. Bishop G and Nikki Jean) ...,27.0

==================================================
  Collection: WAR
==================================================

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

==================================================
  Collection: HAPPINESS
==================================================

,artist,title,play_count
1,The Roots,The Session (Longest Posse Cut In History_ 12:43),1.0
2,Jessica Simpson,I've Got My Eyes On You,0.0
3,Heather Small,I've Been There,0.0
4,Red Hot Chili Peppers,Around The World (Album Version),0.0
5,Jessica Simpson,I Think I'm In Love With You,0.0
6,New Radicals,Maybe You've Been Brainwashed Too,0.0
7,John Martyn,Could've Been Me,0.0
8,Spice Girls,Something Kinda Funny,0.0
9,Missing Persons,Give (Dance Mix) (2002 Digital Remaster),0.0
10,Jessica Simpson,My Wonderful,0.0
11,Studio 99,What Have I Done To Deserve This,0.0

==================================================
  Collection: LONELINESS
==================================================

,artist,title,play_count
1,Silkk The Shocker,D-Game (feat. Master P_ Krazy and Terror) (Remix),0.0

==================================================
  Collection: MONEY
==================================================

,artist,title,play_count
1,The Hollies,I'm Down,5.0
2,Bruce Springsteen,I'm Goin' Down,2.0
3,Red Hot Chili Peppers,I Like Dirt (Album Version),1.0
4,The Benjamin Gate,Lay It Down (Untitled Album Version),0.0
5,Mad Skillz,It's Goin' Down [Explicit],0.0
6,Cupid,Cupid Shuffle [DFA Dub],0.0
7,Kool & The Gang,Jungle Boogie,0.0
8,Andres Calamaro,No Se Puede Vivir Del Amor,0.0
9,UGK (Underground Kingz),She Luv It,0.0
10,Unladylike,Sit Down,0.0
11,Fatboy Slim,The World Went Down,0.0
12,Will.I.Am,Over,0.0
13,Curiosity Killed The Cat,Down To Earth,0.0
14,LL Cool J,Buckin' Em Down,0.0
15,Big Moe,Freestyle (screwed),0.0
16,Spice Girls,Saturday Night Divas,0.0
17,LL Cool J,Diggy Down,0.0
18,Simply Red,Model,0.0
19,Jordanaires,Sit Down,0.0
20,America,Down To The Water (Album Version),0.0
21,Mississippi Fred McDowell,Shake 'Em On Down,0.0
22,Chris Brown,Fallin Down,0.0
23,Status Quo,Down Down,0.0
24,Chumbawamba,Tubthumping,0.0
25,Diomay,Bel Air,0.0
26,The Cult,The Snake,0.0
27,Sugababes,Down Down,0.0
28,Jennifer Warnes,Way Down Deep,0.0
29,Jamie Foxx featuring Gucci Mane,Speak French,0.0
30,Kool & The Gang,Get Down On It,0.0
31,G-Unit,Get Down,0.0
32,Joan Armatrading,Deep Down,0.0
33,Lionel Richie,Se La,0.0

### Approach 3 -- Classification (MultinomialNB / Logistic / SGD / RandomForest on lyrics)

In [6]:
classifiers = ["nb", "logistic", "sgd", "forest"]
clf_results = collection_classification_compare(rs, KEYWORDS, n=10, neg_ratio=1, classifiers=classifiers)
for name in classifiers:
    print(f"\n{'='*60}\nClassifier: {name.upper()}\n{'='*60}")
    for kw, df in clf_results[name].items():
        print(f"\n  Collection: {kw.upper()}")
        display(df)

============================================================
Classifier: NB
============================================================

  Collection: LOVE

,artist,title,play_count
1,Blessid Union Of Souls,Could've Been With You,0.0
2,Maxwell,Arroz Con Pollo,0.0
3,Maxwell,Eachhoureachsecondeachminuteeachday:Of My Life,0.0
4,Joe Clay,Annabella,0.0
5,Maxwell,This Woman's Work,4.0
6,Whitesnake,Mistreated (Live) (2007 Digital Remaster),0.0
7,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,0.0
8,Glenn Hughes,Mistreated,0.0
9,Hughes Turner Project,Mistreated,0.0
10,Songs:Ohia,Ghost Tropic,0.0
11,Lush,Ciao !,1.0
12,Leon Jackson,Caledonia,0.0
13,Chris De Burgh,Missing You,0.0
14,Uriah Heep,Been Away Too Long,0.0
15,Keith Sweat,What Goes Around (LP Version),0.0
16,Miss Li,Take a Shower!,0.0
17,Alexandra Burke,Overcome,0.0
18,Solitude Aeturnus,Believe,0.0
19,Ginuwine,Bedda To Have Loved,0.0
20,The Germs,Throw It Away,0.0
21,Martha Reeves,I've Got To Use My Imagination,0.0
22,Beth Orton,Live As You Dream,0.0
23,MU330,Oh My God,0.0
24,Ambrosia,How Can You Love Me (Remastered Version),0.0
25,All Saints,Never Ever,1.0
26,Thaddeus Hogarth,It Might As Well Be Now,0.0
27,Babe Ruth,Private Number (2007 Digital Remaster),0.0
28,Jennifer Lopez,Should've Never,0.0
29,Kingdom Come,Should Have Told You,0.0
30,88 Fingers Louie,Try It Again,0.0
31,Dwele,Find A Way,0.0
32,Sara Melson,Never Been Hurt,0.0
33,Kid Dynamite,Table 19,0.0
34,Blessid Union Of Souls,Lucky To Be Here,0.0
35,W.A.S.P.,Easy Living,0.0
36,Kenny Rogers,Through The Years,0.0
37,Edyta Gorniak,Anything,0.0
38,Marty Robbins,Like All The Other Times,0.0
39,Average White Band,Got The Love,0.0
40,On Thorns I Lay,Unsung Songs,0.0
41,Conway Twitty,Let Me Be The Judge,0.0
42,Brian McKnight,Try Our Love Again,0.0
43,PackFM,Token Love Song,0.0
44,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
45,Everyday Sunday,Mess With Your Mind,0.0
46,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
47,Joey McIntyre,Bewitched,0.0
48,The Michael Schenker Group,Ulcer (2009 Digital Remaster),0.0
49,Sandra,Put Your Arms Around Me,0.0
50,Linkin Park,What I've Done (Album Version),58.0

  Collection: WAR

,artist,title,play_count
1,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
2,Kenny G,Santa Claus Is Coming To Town,0.0
3,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
4,Willie Nelson,Here Comes Santa Claus,0.0
5,Gene Autry,Here Comes Santa Claus,0.0
6,Bob Dylan,Here Comes Santa Claus,0.0
7,Andrea Bocelli,Santa Claus Is Coming To Town,0.0
8,The SA,Santa Claus Is Coming to Town,0.0
9,Patty Loveless,The Boys Are Back In Town,0.0
10,Everclear,The Boys Are Back In Town,0.0
11,Brooks & Dunn,Santa Claus Is Comin' To Town,0.0
12,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
13,The Tractors,The Santa Claus Boogie,0.0
14,The Dubliners,Dirty Old Town,0.0
15,Billy Idol,Run Rudolph Run,0.0
16,Brooks & Dunn,She Likes To Get Out Of Town,0.0
17,The Pure,Rock This Town,0.0
18,Stray Cats,Rock This Town,0.0
19,Del Shannon,Stranger In Town,0.0
20,Adam Brand,Big Old Car,0.0
21,John Martyn,Dancing,0.0
22,Tony Lucca,Devil Town,0.0
23,War,L.A. Sunshine (Single Version),0.0
24,Billy Gilman,There's A New Kid In Town,0.0
25,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,1.0
26,Wishbone Ash,Rock 'N Roll Widow,0.0
27,ENUR Feat NATASJA,Calabria 2007,46.0
28,The Continentals,Santa Claus Is Back In Town,0.0
29,Hans Theessink,Bourgeois Blues,0.0
30,Lars Frederiksen And The Bastards,Bastards,0.0
31,The Continentals,I Saw Mommy Kissing Santa Claus,0.0
32,Sparks,The Toughest Girl in Town,0.0
33,Dan Colehour,Quarry Town,0.0
34,Phil Vassar,Joe & Rosalita,0.0
35,HOLLY DUNN,Rock-A-Billy,0.0
36,iLiKETRAiNS,Twenty Five Sins,0.0
37,L.A. Guns,Run Rudolph Run,0.0
38,Arthur Conley,Funky Street,2.0
39,Luke Bryan,Run Run Rudolph,0.0
40,Brenda Lee,Christy Christmas,0.0
41,Roy Brown,Good Rocking Tonight,0.0
42,Buck-O-Nine,Tool,0.0
43,Elvis Presley,Good Rockin' Tonight,0.0
44,Sparks,Big Boy,0.0
45,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
46,Mecca Normal,What About The Boy?,0.0
47,Peter and the Test Tube Babies,Boozanza (Single Version),0.0
48,Jimmy Dean,Cajun Queen,0.0
49,George Thorogood & The Destroyers,Restless,0.0
50,David Wilcox,Wilford Brandon Hayes,0.0

  Collection: HAPPINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: LONELINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: MONEY

,artist,title,play_count
1,Youssoupha,Éternel recommencement,0.0
2,Sinik,Dans le Vif,0.0
3,Alain Turban,Drôle de vie,0.0
4,Dub Incorporation,Face à Soi,0.0
5,Sniper,Visions Chaotiques,0.0
6,Sniper,Fallait que je te dise (radio edit),0.0
7,Rohff,La Puissance (Classic),0.0
8,Shurik'n,Fugitif,0.0
9,Oxmo Puccino,Amour Et Jalousie,0.0
10,Grand Corps Malade,Comme Une Evidence,0.0
11,Svinkels,Front Contre Front,0.0
12,Oxmo Puccino,Mourir 1000 Fois,0.0
13,Fatals Picards,Au mariage de Kevin et ma soeur [En Public],0.0
14,Khaled,Mauvais Sang,0.0
15,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
16,Rohff,Pervertie,0.0
17,Fonky Family,Mystère Et Suspens,0.0
18,La Fouine,Peace On Earth,0.0
19,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
20,Oxmo Puccino,Un Flingue Et Des Roses (Avec Kool Shen),0.0
21,Despo' Rutti,Legitime Defense,0.0
22,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
23,MYSA,80-07,0.0
24,Youssoupha,Toubab,0.0
25,Le Klub Des Loosers,Baise les gens,0.0
26,Nessbeal,Les larmes de ce monde,0.0
27,Sniper,35 heures,0.0
28,Dub Incorporation,Petit Soldat,1.0
29,La Fouine,Mon Autobiographie,0.0
30,Le Rat Luciano,Derrière Les Apparences,0.0
31,Despo' Rutti,Redemption,0.0
32,Shurik'n,Lettre,2.0
33,Alibi Montana,Fossoyeur,0.0
34,Oxmo Puccino,Parallèles,0.0
35,Cali,Roberta (Live Acoustique),0.0
36,Anis,Oisif,0.0
37,Bakar,Pour Les Quartiers feat. Jmi Sissoko,0.0
38,Nicolas Bacchus,Les maladies mortelles,0.0
39,Mac Tyer,Outro,0.0
40,Sinik,Ennemi d'Etat,0.0
41,Dany Dan,Master,0.0
42,Saian Supa Crew,X raisons (live),0.0
43,Les Sages Poetes De La Rue,Un monde étrange,0.0
44,NTM,Le monde de demain,0.0
45,Stomy Bugsy,Incendie Dans Mon Paradis,0.0
46,Booba,Le Météore,0.0
47,Rocé,Amitié et amertume,0.0
48,Marcel Mouloudji,Tout lamour que jai,0.0
49,Sexion d'Assaut,Arrête de te plaindre,0.0
50,Lara Fabian,Comme Ils Disent,0.0

============================================================
Classifier: LOGISTIC
============================================================

  Collection: LOVE

,artist,title,play_count
1,JET,L'esprit D'escalier (Digital Album Version),0.0
2,Glenn Hughes,Mistreated,0.0
3,Hughes Turner Project,Mistreated,0.0
4,Let's Go Sailing,Sideways,1.0
5,Whitesnake,Mistreated (Live) (2007 Digital Remaster),0.0
6,Le Tigre,Fake French,3.0
7,Screaming Trees,Dime Western,0.0
8,Mixel Pixel,I've Been Around,0.0
9,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,0.0
10,Neil Young,Jellyroll Man,0.0
11,Ginuwine,Bedda To Have Loved,0.0
12,Infected Mushroom,Tasty Mushroom,0.0
13,Don McLean,Since I Don't Have You,0.0
14,Husker Du,No Promise Have I Made,0.0
15,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
16,Ritchie Family,Brazil,0.0
17,Metronomy,A Thing For Me,5.0
18,Sophie Zelmani,Got To Stop,0.0
19,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
20,Nil Lara,Bleeding,0.0
21,The Heavy Blinkers,Don't Get Me Wrong,0.0
22,Randy Crawford,I've Never Been To Me (LP Version),0.0
23,Enchant,Despicable,0.0
24,Joe Clay,Annabella,0.0
25,Fozzy,Grail (Album),0.0
26,Marshall Crenshaw,Live it Up,0.0
27,The Germs,Throw It Away,0.0
28,Mike And The Mechanics,Now That You've Gone,0.0
29,The Yardbirds,My Baby (Top Gear),0.0
30,Hot Chocolate,You Could've Been A Lady,0.0
31,Alberta Hunter,You Can't Have It All,0.0
32,A Radio With Guts,Bloodletter,0.0
33,NOFX,No Problems,1.0
34,Eric Burdon,Never give up Blues,0.0
35,Kelly Marie,If I Can't Have You,0.0
36,Lionel Richie,One World,0.0
37,Blessid Union Of Souls,Could've Been With You,0.0
38,The Young Punx,You You You,0.0
39,Chris De Burgh,Missing You,0.0
40,Miss Li,Take a Shower!,0.0
41,MU330,Oh My God,0.0
42,Skin,Faithfulness,0.0
43,Thea Gilmore,Pontiac To A Home Girl,0.0
44,Patrice Rushen,Haven't You Heard (LP Version),0.0
45,Low,Stay,0.0
46,The Bees,End Of The Street,0.0
47,Timo Räisänen,With a Mask on,0.0
48,Songs:Ohia,Ghost Tropic,0.0
49,Fleetwood Mac,Coming Home,0.0
50,Linkin Park,What I've Done (Album Version),58.0

  Collection: WAR

,artist,title,play_count
1,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
2,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
3,Kenny G,Santa Claus Is Coming To Town,0.0
4,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
5,Everclear,The Boys Are Back In Town,0.0
6,Patty Loveless,The Boys Are Back In Town,0.0
7,The Silencers,Bulletproof heart,0.0
8,iLiKETRAiNS,Twenty Five Sins,0.0
9,Hot Hot Heat,This Town,0.0
10,Del Shannon,Stranger In Town,0.0
11,Tony Lucca,Devil Town,0.0
12,Brooks & Dunn,She Likes To Get Out Of Town,0.0
13,Pitchshifter,Phoenixology,0.0
14,War,L.A. Sunshine (Single Version),0.0
15,The Dubliners,Dirty Old Town,0.0
16,Sparks,The Toughest Girl in Town,0.0
17,O.A.R.,This Town (Album Version),0.0
18,Billy Gilman,There's A New Kid In Town,0.0
19,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,1.0
20,Hans Theessink,Bourgeois Blues,0.0
21,Siouxsie And The Banshees,Running Town,0.0
22,Dan Colehour,Quarry Town,0.0
23,Desmond Dekker,007,3.0
24,John Leyton,Country Boy,0.0
25,Jason & The Scorchers,Ghost Town,0.0
26,Joe Jackson,Hell of a Town,0.0
27,Lemonhead,Down Town,0.0
28,Wishbone Ash,Rock 'N Roll Widow,0.0
29,Meredith Brooks,My Little Town,0.0
30,The Gone Jackals,Get Outta Town,0.0
31,Milton Mapes,Lonesome Town,0.0
32,Kinesis,Civilised Fury,0.0
33,The Pure,Rock This Town,0.0
34,Fred Eaglesmith,The Rocket,0.0
35,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
36,Andrea Bocelli,Santa Claus Is Coming To Town,0.0
37,Willie Nelson,Here Comes Santa Claus,0.0
38,Gene Autry,Here Comes Santa Claus,0.0
39,Bob Dylan,Here Comes Santa Claus,0.0
40,Cocoa Tea,Sweeter (Album Version),0.0
41,Stray Cats,Rock This Town,0.0
42,Evidence,Out of Town,0.0
43,Lesley Gore,My Town My Guy And Me,0.0
44,John Martyn,Dancing,0.0
45,Odetta,The Fox,0.0
46,Jill Sobule,Happy Town (LP Version),0.0
47,Brooks & Dunn,Santa Claus Is Comin' To Town,0.0
48,Frankie Laine,Strange Lady In Town,0.0
49,Better Than Ezra,Normal Town (LP Version),0.0
50,ENUR Feat NATASJA,Calabria 2007,46.0

  Collection: HAPPINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: LONELINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: MONEY

,artist,title,play_count
1,Dany Dan,Master,0.0
2,Khaled,Mauvais Sang,0.0
3,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
4,Svinkels,Front Contre Front,0.0
5,Michèle Arnaud,Douze belles dans la peau (Gainsbourg),0.0
6,KDD,Orange M.,0.0
7,Nessbeal,Rimes Instinctives,0.0
8,Rohff,Pervertie,0.0
9,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
10,Youssoupha,Éternel recommencement,0.0
11,Sinik,Ennemi d'Etat,0.0
12,MYSA,80-07,0.0
13,Sniper,35 heures,0.0
14,Michèle Bernard,Ce soir je n'entends rien,0.0
15,Sniper,Visions Chaotiques,0.0
16,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
17,Shurik'n,Fugitif,0.0
18,Alibi Montana,Fossoyeur,0.0
19,Oxmo Puccino,Amour Et Jalousie,0.0
20,Lara Fabian,Comme Ils Disent,0.0
21,Despo' Rutti,Legitime Defense,0.0
22,Le Klub Des Loosers,Baise les gens,0.0
23,Les Sages Poetes De La Rue,Un monde étrange,0.0
24,Nicolas Bacchus,Les maladies mortelles,0.0
25,NTM,Le monde de demain,0.0
26,Oxmo Puccino,Un Flingue Et Des Roses (Avec Kool Shen),0.0
27,Sinik,Dans le Vif,0.0
28,Booba,Le Météore,0.0
29,Alain Turban,Drôle de vie,0.0
30,Dub Incorporation,Face à Soi,0.0
31,La Fouine,Ma Tabatière (Chronique D'Un Dealer),0.0
32,Despo' Rutti,L'Oeil Aux Beurs Noirs,0.0
33,Despo' Rutti,Redemption,0.0
34,Sefyu,Musculation,0.0
35,Marcel Mouloudji,Tout lamour que jai,0.0
36,Pierre Perret,La petite Kurde,0.0
37,Aldebert,Tête en l'air (Live),0.0
38,Sniper,Fallait que je te dise (radio edit),0.0
39,La Fouine,Peace On Earth,0.0
40,Fonky Family,La Furie Et La Foi,0.0
41,Mano Solo,Du Vent,0.0
42,KDD,Jungle Fever,0.0
43,Fonky Family;BOSS (Boss Of Scandalz Strategyz)...,La Résistance,0.0
44,Nessbeal,Au Dela De L'horizon,0.0
45,Oldelaf et Monsieur D,Rue de Nantes,0.0
46,Yann Perreau,Soul Circus,0.0
47,Benjamin Biolay,La Chambre D'amis,0.0
48,Sinik,Realiste,0.0
49,Expression Direkt,Krapulax,0.0
50,Rohff,La Puissance (Classic),0.0

============================================================
Classifier: SGD
============================================================

  Collection: LOVE

,artist,title,play_count
1,JET,L'esprit D'escalier (Digital Album Version),0.0
2,Glenn Hughes,Mistreated,0.0
3,Hughes Turner Project,Mistreated,0.0
4,Let's Go Sailing,Sideways,1.0
5,Whitesnake,Mistreated (Live) (2007 Digital Remaster),0.0
6,Le Tigre,Fake French,3.0
7,Infected Mushroom,Tasty Mushroom,0.0
8,Screaming Trees,Dime Western,0.0
9,Don McLean,Since I Don't Have You,0.0
10,Husker Du,No Promise Have I Made,0.0
11,Neil Young,Jellyroll Man,0.0
12,Mixel Pixel,I've Been Around,0.0
13,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,0.0
14,Ginuwine,Bedda To Have Loved,0.0
15,Ritchie Family,Brazil,0.0
16,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
17,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
18,Sophie Zelmani,Got To Stop,0.0
19,Metronomy,A Thing For Me,5.0
20,Nil Lara,Bleeding,0.0
21,Alberta Hunter,You Can't Have It All,0.0
22,The Heavy Blinkers,Don't Get Me Wrong,0.0
23,Enchant,Despicable,0.0
24,Mike And The Mechanics,Now That You've Gone,0.0
25,Kelly Marie,If I Can't Have You,0.0
26,Randy Crawford,I've Never Been To Me (LP Version),0.0
27,Fozzy,Grail (Album),0.0
28,The Germs,Throw It Away,0.0
29,Joe Clay,Annabella,0.0
30,NOFX,No Problems,1.0
31,A Radio With Guts,Bloodletter,0.0
32,Low,Stay,0.0
33,Hot Chocolate,You Could've Been A Lady,0.0
34,Lionel Richie,One World,0.0
35,The Yardbirds,My Baby (Top Gear),0.0
36,Thea Gilmore,Pontiac To A Home Girl,0.0
37,Marshall Crenshaw,Live it Up,0.0
38,MU330,Oh My God,0.0
39,Miss Li,Take a Shower!,0.0
40,Patrice Rushen,Haven't You Heard (LP Version),0.0
41,Eric Burdon,Never give up Blues,0.0
42,The Young Punx,You You You,0.0
43,Linkin Park,What I've Done (Album Version),58.0
44,Skin,Faithfulness,0.0
45,Blessid Union Of Souls,Could've Been With You,0.0
46,Hoobastank,Never Saw It Coming,1.0
47,Chris De Burgh,Missing You,0.0
48,Timo Räisänen,With a Mask on,0.0
49,Twisted Wheel,Let Them Have It All,0.0
50,Fleetwood Mac,Coming Home,0.0

  Collection: WAR

,artist,title,play_count
1,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
2,The Silencers,Bulletproof heart,0.0
3,iLiKETRAiNS,Twenty Five Sins,0.0
4,Patty Loveless,The Boys Are Back In Town,0.0
5,Del Shannon,Stranger In Town,0.0
6,Hot Hot Heat,This Town,0.0
7,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
8,Kenny G,Santa Claus Is Coming To Town,0.0
9,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
10,Everclear,The Boys Are Back In Town,0.0
11,War,L.A. Sunshine (Single Version),0.0
12,Tony Lucca,Devil Town,0.0
13,Pitchshifter,Phoenixology,0.0
14,Siouxsie And The Banshees,Running Town,0.0
15,Desmond Dekker,007,3.0
16,Brooks & Dunn,She Likes To Get Out Of Town,0.0
17,Billy Gilman,There's A New Kid In Town,0.0
18,The Dubliners,Dirty Old Town,0.0
19,Hans Theessink,Bourgeois Blues,0.0
20,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,1.0
21,O.A.R.,This Town (Album Version),0.0
22,The Pure,Rock This Town,0.0
23,The Gone Jackals,Get Outta Town,0.0
24,Kinesis,Civilised Fury,0.0
25,Cocoa Tea,Sweeter (Album Version),0.0
26,Sparks,The Toughest Girl in Town,0.0
27,Milton Mapes,Lonesome Town,0.0
28,Fred Eaglesmith,The Rocket,0.0
29,Stray Cats,Rock This Town,0.0
30,John Martyn,Dancing,0.0
31,Wishbone Ash,Rock 'N Roll Widow,0.0
32,Joe Jackson,Hell of a Town,0.0
33,Frankie Laine,Strange Lady In Town,0.0
34,Jason & The Scorchers,Ghost Town,0.0
35,Meredith Brooks,My Little Town,0.0
36,Iggy Pop,Butt Town,0.0
37,Lesley Gore,My Town My Guy And Me,0.0
38,Better Than Ezra,Normal Town (LP Version),0.0
39,Secret Lives Of The Freemasons,Airplanes (Album Version),0.0
40,Dan Colehour,Quarry Town,0.0
41,John Leyton,Country Boy,0.0
42,Lemonhead,Down Town,0.0
43,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
44,ENUR Feat NATASJA,Calabria 2007,46.0
45,Evidence,Out of Town,0.0
46,Jill Sobule,Happy Town (LP Version),0.0
47,Darden Smith,Love Left Town,0.0
48,The Everly Brothers,Bully Of The Town,0.0
49,Adam Brand,Big Old Car,0.0
50,The Upper Room,All Over This Town,0.0

  Collection: HAPPINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: LONELINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: MONEY

,artist,title,play_count
1,Michèle Arnaud,Douze belles dans la peau (Gainsbourg),0.0
2,Dany Dan,Master,0.0
3,Michèle Bernard,Ce soir je n'entends rien,0.0
4,Noir Désir,Des Armes,0.0
5,Svinkels,Front Contre Front,0.0
6,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
7,Sefyu,Musculation,0.0
8,KDD,Orange M.,0.0
9,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
10,Benjamin Biolay,La Chambre D'amis,0.0
11,Sinik,Ennemi d'Etat,0.0
12,Booba,Le Météore,0.0
13,Aldebert,Tête en l'air (Live),0.0
14,Vulgaires Machins,A (Live),0.0
15,Les Sages Poetes De La Rue,Un monde étrange,0.0
16,Oldelaf et Monsieur D,Rue de Nantes,0.0
17,Beau Dommage,Ginette (2004 Digital Remaster),0.0
18,Maxime Le Forestier,Education Sentimentale,0.0
19,Thomas Fersen,Pickpocket,0.0
20,Rohff,Pervertie,0.0
21,Isabelle Adjani,Ohio,0.0
22,Yann Perreau,Soul Circus,0.0
23,Alfa Rococo,Véga,0.0
24,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
25,Léo Ferré,Vitrines,0.0
26,Nessbeal,Au Dela De L'horizon,0.0
27,Nessbeal,Rimes Instinctives,0.0
28,Rocé,Amitié et amertume,0.0
29,Garou,Gitan,0.0
30,Olivia Ruiz,L'Absente,0.0
31,Java,Danser,0.0
32,Dany Brillant,Je Voudrais Tant Que Tu Me Donnes,1.0
33,Natasha St-Pier,Ce silence,0.0
34,Mano Solo,Du Vent,0.0
35,Medine,Écoute,0.0
36,Khaled,Mauvais Sang,0.0
37,Marcel Mouloudji,Tout lamour que jai,0.0
38,Fatal Bazooka,Ego Trip,0.0
39,La Fouine,Je Regarde Là-Haut,0.0
40,Raphaël,Et Dans 150 Ans (Live 2006),0.0
41,Georges Brassens,Le Pornographe,0.0
42,Aimable,Sombreros et Mantilles,0.0
43,Moxy Fruvous,Nuits De Reve,2.0
44,Cali,Roberta (Live Acoustique),0.0
45,Sefyu,Biff,0.0
46,Jean Ferrat,L'adresse du bonheur,0.0
47,Thomas Fersen,L'Escalier Live,0.0
48,Oxmo Puccino,Mourir 1000 Fois,0.0
49,MYSA,80-07,0.0
50,Youssoupha,Vous avez demandé la police ?,0.0

============================================================
Classifier: FOREST
============================================================

  Collection: LOVE

,artist,title,play_count
1,Maxwell,Arroz Con Pollo,0.0
2,Clawfinger,Runner Boy,0.0
3,Clawfinger,Life Will Kill You,0.0
4,Clawfinger,The Best & The Worst,0.0
5,Maxwell,Eachhoureachsecondeachminuteeachday:Of My Life,0.0
6,Geri,Superstar,0.0
7,Flaw,You've Changed,9.0
8,S Club 7,Stronger,0.0
9,Cutting Crew,(I Just) Died In Your Arms,0.0
10,Jason Mraz,Traveler / Make It Mine (Live On Earth Version),0.0
11,Leana,I Just Died In Your Arms Tonight,0.0
12,Leela James,Good Time [Groove Junkies MoHo Vox],0.0
13,Don Johnson,Lonely Too Long,0.0
14,Andrew W.K.,The Party God,0.0
15,K-Ci & JoJo,Love Ballad,0.0
16,Jeremiah Freed,Wait For Me,0.0
17,Martha Reeves,I've Got To Use My Imagination,0.0
18,Dhany,What You Do To Me,0.0
19,Maxwell,This Woman's Work,4.0
20,Albert Hammond Jr.,Holiday,0.0
21,Justin Tubb,Be Glad,0.0
22,Patrice Rushen,Haven't You Heard (LP Version),0.0
23,Mary Black,God Bless The Child,0.0
24,Keith Sweat,What Goes Around (LP Version),0.0
25,Re:hab,Find My Way,0.0
26,Buddy Jewell,I Can Get By,0.0
27,Whitesnake,Mistreated (Live) (2007 Digital Remaster),0.0
28,Fleetwood Mac,Coming Home,0.0
29,The Regiment,Take It Back,0.0
30,Margaret Becker,All I Ever Wanted,0.0
31,Robin S,Show Me Love,0.0
32,Vipers,Maggie May,0.0
33,Kimya Dawson,All I Want Is You (Album Version),0.0
34,Tree63,Look What You've Done,0.0
35,Jason Mraz,Butterfly [Live From Highline Ballroom],0.0
36,Glenn Hughes,Mistreated,0.0
37,James Blunt,Goodbye My Lover (Live at 93 East),0.0
38,Hughes Turner Project,Mistreated,0.0
39,James Taylor,Fire And Rain,39.0
40,Neil Sedaka,Happy Birthday_ Sweet Sixteen,1.0
41,Dinosaur Jr,Seemed Like The Thing To Do,1.0
42,The Stone Roses,Tears,0.0
43,Sammi Smith,Fire and Rain,0.0
44,Kleiton & Kledir,Mamma mia,0.0
45,Billy Joel,The Entertainer,0.0
46,The Bar-Kays,I Thank You,0.0
47,Nirvana,Been A Son,19.0
48,Joni Mitchell,This Flight Tonight (LP Version),0.0
49,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
50,The Jets,Crush On You,0.0

  Collection: WAR

,artist,title,play_count
1,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
2,Kenny G,Santa Claus Is Coming To Town,0.0
3,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
4,Everclear,The Boys Are Back In Town,0.0
5,The Pure,Rock This Town,0.0
6,Stray Cats,Rock This Town,0.0
7,Tom T. Hall,A Million Miles To The City,0.0
8,The Clash,Last Gang In Town,0.0
9,Tony Lucca,Devil Town,0.0
10,Johnny Cash,The Night Hank Williams Came To Town,0.0
11,Iggy Pop,Butt Town,0.0
12,Patty Loveless,The Boys Are Back In Town,0.0
13,ENUR Feat NATASJA,Calabria 2007,46.0
14,Thea Gilmore,My Own Private Riot,0.0
15,Billy Gilman,There's A New Kid In Town,0.0
16,Frankie Laine,Strange Lady In Town,0.0
17,Brian Wilson,Country Feelin's,0.0
18,The Clash,Clash City Rockers,0.0
19,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,1.0
20,The Gone Jackals,Get Outta Town,0.0
21,Webb Pierce,In the Jailhouse now,0.0
22,They Might Be Giants,They Got Lost,0.0
23,Snot,Snot,3.0
24,Andrea Bocelli,Santa Claus Is Coming To Town,0.0
25,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
26,Brooks & Dunn,She Likes To Get Out Of Town,0.0
27,The Vogues,Magic Town,0.0
28,The Dubliners,Dirty Old Town,0.0
29,Aviator,Dancing Bear,0.0
30,Swingin' Utters,Reggae Gets Big In A Small Town,0.0
31,The Brian Setzer Orchestra,Hey_ Louis Prima,0.0
32,Odetta,The Fox,0.0
33,Hans Theessink,Bourgeois Blues,0.0
34,The Most Serene Republic,Phages,0.0
35,George Thorogood & The Destroyers,Restless,0.0
36,Empire Of The Sun,Delta Bay,0.0
37,Woody Guthrie,Vigilante Man,0.0
38,Rogue Wave,Phonytown,0.0
39,Lucky Soul,Love3,0.0
40,Red Foley,Midnight,0.0
41,The Replacements,Lay It Down Clown,1.0
42,Sparks,The Toughest Girl in Town,0.0
43,Milton Mapes,Lonesome Town,0.0
44,Tift Merritt,Laid A Highway,0.0
45,The Enemy,We'll Live And Die In These Towns,0.0
46,Bachman-Turner Overdrive,Stonegates,0.0
47,The Enemy,Images (Live),0.0
48,John Martyn,Dancing,0.0
49,Jimmy Buffett,Fins,5.0
50,The Academy Is...,Paper Chase (Album Version),0.0

  Collection: HAPPINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: LONELINESS

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

  Collection: MONEY

,artist,title,play_count
1,Sniper,Panam All Star,0.0
2,Java,Danser,0.0
3,Mac Tyer,Outro,0.0
4,Alias,Hors la loi,0.0
5,Sniper,Y'a Pas De Mérite,0.0
6,La Fouine,Ma Tabatière (Chronique D'Un Dealer),0.0
7,Léo Ferré,Vitrines,0.0
8,Sniper,Fallait que je te dise (radio edit),0.0
9,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
10,Youssoupha,Éternel recommencement,0.0
11,Nessbeal,Au Dela De L'horizon,0.0
12,Nessbeal,Les larmes de ce monde,0.0
13,Fonky Family,La Guerre,1.0
14,Georges Brassens,Le gorille,0.0
15,Saian Supa Crew,J'adore ça (live),0.0
16,Khaled,Mauvais Sang,0.0
17,Saïan Supa Crew,J'ai dit,0.0
18,Le Rat Luciano,On Hait,0.0
19,Iron Sy,Mon opinion,0.0
20,La Rue Ketanou,Maître Corbeau,0.0
21,Michèle Arnaud,Douze belles dans la peau (Gainsbourg),0.0
22,Alibi Montana,Fossoyeur,0.0
23,Deka,La violence,0.0
24,KDD,Orange M.,0.0
25,Sefyu,La Frappe,0.0
26,Fonky Family,La Furie Et La Foi,0.0
27,A*Teens,S.O.S.,0.0
28,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
29,Patrick Bruel,Voulez-Vous,0.0
30,Les Ogres De Barback,Monde en or,0.0
31,Abd Al Malik,Soldat De Plomb,0.0
32,Thomas Fersen,Monsieur Live,0.0
33,Taktika,Au nom de qui?,0.0
34,Le Klub des 7,Pouilleux massacreur,0.0
35,Maurice Chevalier,La chanson du maçon,0.0
36,Dub Incorporation,Murderer,3.0
37,Les Sages Poetes De La Rue,Un noir tue un noir,0.0
38,Youssoupha,Vous avez demandé la police ?,0.0
39,Aldebert,Tête en l'air (Live),0.0
40,Svinkels,Ultras festifs,0.0
41,Sinik,Realiste,0.0
42,Don Choa,Toute La Nuit,0.0
43,Bézu,Etoile des neiges,0.0
44,MYSA,80-07,0.0
45,Dany Brillant,Suzette,0.0
46,Benabar,Majorette,0.0
47,Ridan,Pauvre Con,0.0
48,Renan Luce,Je Suis Une Feuille,0.0
49,Michèle Bernard,Ce soir je n'entends rien,0.0
50,Seth Gueko,J'oublierai Pas,0.0

### Comparison

Check overlap between the three approaches for each keyword.

In [7]:
import pandas as pd

def summarize(df):
    if df is None or len(df) == 0:
        return 0, set()
    return len(df), set(zip(df["artist"], df["title"]))

methods = [("baseline", baseline_results), ("w2v", w2v_results)]
methods += [(f"clf_{name}", clf_results[name]) for name in classifiers]

rows = {}
for kw in KEYWORDS:
    rows[kw.upper()] = {label: summarize(res.get(kw))[0] for label, res in methods}

print("Result sizes (rows per keyword and method):")
display(pd.DataFrame(rows).T)

Result sizes (rows per keyword and method):

            baseline  w2v  clf_nb  clf_logistic  clf_sgd  clf_forest
LOVE              50   50      50            50       50          50
WAR               50    0      50            50       50          50
HAPPINESS          0   11       0             0        0           0
LONELINESS         0    1       0             0        0           0
MONEY             50   33      50            50       50          50