# 04 -- Collaborative Filtering (implicit ALS)

Matrix-factorization collaborative filtering via the **`implicit`** library
(`implicit.als.AlternatingLeastSquares`), evaluated with **precision@10**.

### Algorithm

Implicit-feedback ALS (Hu, Koren & Volinsky 2008):
1. Build a sparse user x song matrix from play counts; each cell is a
   confidence `c_ui = alpha * play_count`.
2. `AlternatingLeastSquares` alternates least-squares updates to extract
   latent user and song factors that best explain the play signal.
3. **4a -- user-based**: score every song for a user as `U_u . V_i`, recommend
   the top-10 the user hasn't played.
4. **4b -- item-based**: for a seed song, rank songs by cosine similarity of
   their latent profiles, recommend the top-10.

### Evaluation
- **Train/test split**: random holdout of 20% per user (no timestamps in
  the data, so "last 20%" is approximated by a random split).
- **Metric**: Precision@10 -- fraction of recommended tracks the user
  actually listened to in the test set. Target: **> 10%**.

### Output columns
| Column | Description |
|--------|-------------|
| `rank` | 1-10, by likelihood score (descending) |
| `artist` | Artist name |
| `title` | Track title |

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from src.data.loader import MySpotifyRecommender

from src.models.collaborative_filtering import (
    build_user_item_matrix,
    fit_als,
    evaluate_user_cf,
)
from implicit.evaluation import train_test_split

/home/samy/MySpotify/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/samy/MySpotify/.venv/lib/python3.12/site-packages/implicit/gpu/__init__.py:28: UserWarning: Disabling GPU support because of 'libcublas.so.13: cannot open shared object file: No such file or directory'
  warnings.warn(

In [2]:
rs = MySpotifyRecommender.from_files(
    data_dir=Path.cwd().parent / "data",
    download=True,
    # triplets_sample_rows=1_000_000
)

Data dir    : /home/samy/MySpotify/data
Source      : cleaned CSVs (/home/samy/MySpotify/data/csv)

  tracks      (1000000, 4)
  genres      (280831, 3)
  triplets    (48373586, 3)
  lyrics_long (16845822, 3)

---
## Research

### Train / Test Split

In [3]:
user_item, user_idx, song_idx, idx_song = build_user_item_matrix(rs.triplets)
user_item.shape

(1019318, 384546)

In [4]:
train, test = train_test_split(user_item, train_percentage=0.8, random_state=42)

### 4. Collaborative Filtering

In [5]:
model = fit_als(train, factors=192, regularization=0.09, alpha=1.0, iterations=25)

/home/samy/MySpotify/.venv/lib/python3.12/site-packages/implicit/cpu/als.py:96: RuntimeWarning: OpenBLAS is configured to use 28 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/25 [00:00<?, ?it/s]

  4%|▍         | 1/25 [00:06<02:25,  6.06s/it]

  8%|▊         | 2/25 [00:12<02:23,  6.22s/it]

 12%|█▏        | 3/25 [00:18<02:20,  6.37s/it]

 16%|█▌        | 4/25 [00:25<02:16,  6.52s/it]

 20%|██        | 5/25 [00:32<02:14,  6.71s/it]

 24%|██▍       | 6/25 [00:39<02:10,  6.87s/it]

 28%|██▊       | 7/25 [00:47<02:05,  6.98s/it]

 32%|███▏      | 8/25 [00:54<01:59,  7.03s/it]

 36%|███▌      | 9/25 [01:01<01:53,  7.08s/it]

 40%|████      | 10/25 [01:09<01:48,  7.24s/it]

 44%|████▍     | 11/25 [01:16<01:42,  7.34s/it]

 48%|████▊     | 12/25 [01:24<01:36,  7.42s/it]

 52%|█████▏    | 13/25 [01:31<01:28,  7.41s/it]

 56%|█████▌    | 14/25 [01:39<01:21,  7.44s/it]

 60%|██████    | 15/25 [01:46<01:14,  7.48s/it]

 64%|██████▍   | 16/25 [01:54<01:07,  7.50s/it]

 68%|██████▊   | 17/25 [02:01<00:59,  7.49s/it]

 72%|███████▏  | 18/25 [02:09<00:52,  7.55s/it]

 76%|███████▌  | 19/25 [02:18<00:47,  7.97s/it]

 80%|████████  | 20/25 [02:27<00:42,  8.45s/it]

 84%|████████▍ | 21/25 [02:36<00:33,  8.49s/it]

 88%|████████▊ | 22/25 [02:45<00:26,  8.79s/it]

 92%|█████████▏| 23/25 [02:55<00:18,  9.07s/it]

 96%|█████████▌| 24/25 [03:05<00:09,  9.23s/it]

100%|██████████| 25/25 [03:14<00:00,  9.30s/it]

100%|██████████| 25/25 [03:14<00:00,  7.79s/it]

### 4a -- User-based recommendations (latent factors)

In [6]:
sample_user = ''
for i in user_idx.keys():
    sample_user = i
    break
print(f"Sample user: {sample_user}")

uid = user_idx[sample_user]

top_pred_indices, _ = model.recommend(
    uid, 
    train[uid],
    N=10,
    filter_already_liked_items=True
)

top_pred_item_ids = [idx_song[idx] for idx in top_pred_indices]

df = rs.tracks[rs.tracks["song_id"].isin(top_pred_item_ids)].reset_index(drop=True)
df = df[["artist", "title", "song_id"]]
df = df.drop_duplicates(subset=["song_id"])
df[["artist", "title"]]

Sample user: 00000b722001882066dff9d2da8a775658053ea0

,artist,title
0,Edwyn Collins,You'll Never Know (My Love) (Bovellian 07 Mix)
1,Edwyn Collins,Superstar Talking Blues
2,The Buggles,Video Killed The Radio Star
3,Atomic Kitten,Eternal Flame (Single Version)
4,Fisher,Rianna
5,Valerio Scanu,Esisti Tu
6,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...
7,Cosmo Vitelli,Robot Soul (Radio Edit)
8,Suicidal Tendencies,Go Skate! (Possessed To Skate '97)
9,The Verve,Lord I Guess I'll Never Know

### 4b -- Similar tracks (item-based CF)

In [7]:
top_song = top_pred_item_ids[1]

print(f"Top recommended song for user {sample_user}: {top_song}")

item_id = song_idx[top_song]

print(f"\n{rs.tracks[rs.tracks['song_id'] == top_song][['artist', 'title']].iloc[0]}")

similar_indices, similarity_scores = model.similar_items(itemid=item_id, N=11)
similar_indices = similar_indices[1:]
similarity_scores = similarity_scores[1:]

similar_item_ids = [idx_song[idx] for idx in similar_indices]

df = rs.tracks[rs.tracks["song_id"].isin(similar_item_ids)].reset_index(drop=True)
df = df.drop_duplicates(subset=["song_id"])
df[["artist", "title"]]

Top recommended song for user 00000b722001882066dff9d2da8a775658053ea0: SONHWUN12AC468C014

artist    Fisher
title     Rianna
Name: 456530, dtype: str

                 artist                                      title
0              N.E.R.D.                                  Rock Star
1           Chris Isaak                         The Christmas Song
2         Mickie Krause  Orange Trägt Nur Die Müllabfuhr (Go West)
3  Sonny Boy Williamson                     Don't Start Me Talkin'
4  Switchblade Symphony                                  Dollhouse
5               Cartola                                   Tive Sim
6     Charlelie Couture              L'histoire De Bernard Workers
7          Taylor Swift                         You Belong With Me
8          Taylor Swift                                 Love Story
9            Brenda Lee          Rockin' Around The Christmas Tree

#### Precision@10 -- User-based & Item-Based CF

In [8]:
pk_eval = evaluate_user_cf(
    model,
    train,
    test,
)

pk_eval

  0%|          | 0/998833 [00:00<?, ?it/s]

  0%|          | 1000/998833 [00:01<25:18, 657.29it/s]

  0%|          | 2000/998833 [00:03<25:19, 655.82it/s]

  0%|          | 3000/998833 [00:04<27:06, 612.16it/s]

  0%|          | 4000/998833 [00:06<25:18, 655.14it/s]

  1%|          | 5000/998833 [00:07<23:33, 703.17it/s]

  1%|          | 6000/998833 [00:08<23:19, 709.51it/s]

  1%|          | 7000/998833 [00:10<23:20, 708.43it/s]

  1%|          | 8000/998833 [00:11<23:38, 698.60it/s]

  1%|          | 9000/998833 [00:13<23:23, 705.41it/s]

  1%|          | 10000/998833 [00:14<22:41, 726.29it/s]

  1%|          | 11000/998833 [00:15<23:36, 697.56it/s]

  1%|          | 12000/998833 [00:17<24:27, 672.56it/s]

  1%|▏         | 13000/998833 [00:19<24:21, 674.52it/s]

  1%|▏         | 14000/998833 [00:20<26:05, 629.19it/s]

  2%|▏         | 15000/998833 [00:22<26:51, 610.57it/s]

  2%|▏         | 16000/998833 [00:23<24:45, 661.80it/s]

  2%|▏         | 17000/998833 [00:25<24:32, 666.95it/s]

  2%|▏         | 18000/998833 [00:26<24:17, 672.77it/s]

  2%|▏         | 19000/998833 [00:28<24:16, 672.69it/s]

  2%|▏         | 20000/998833 [00:29<23:01, 708.41it/s]

  2%|▏         | 21000/998833 [00:31<23:44, 686.36it/s]

  2%|▏         | 22000/998833 [00:32<24:53, 653.84it/s]

  2%|▏         | 23000/998833 [00:34<24:59, 650.85it/s]

  2%|▏         | 24000/998833 [00:35<24:37, 659.95it/s]

  3%|▎         | 25000/998833 [00:37<24:39, 658.34it/s]

  3%|▎         | 26000/998833 [00:38<23:29, 689.97it/s]

  3%|▎         | 27000/998833 [00:40<23:34, 687.09it/s]

  3%|▎         | 28000/998833 [00:41<22:48, 709.39it/s]

  3%|▎         | 29000/998833 [00:42<22:27, 719.68it/s]

  3%|▎         | 30000/998833 [00:43<21:55, 736.26it/s]

  3%|▎         | 31000/998833 [00:45<23:15, 693.67it/s]

  3%|▎         | 32000/998833 [00:47<23:32, 684.64it/s]

  3%|▎         | 33000/998833 [00:48<23:06, 696.83it/s]

  3%|▎         | 34000/998833 [00:49<22:33, 713.00it/s]

  4%|▎         | 35000/998833 [00:51<22:20, 718.97it/s]

  4%|▎         | 36000/998833 [00:52<22:51, 702.03it/s]

  4%|▎         | 37000/998833 [00:54<22:32, 711.05it/s]

  4%|▍         | 38000/998833 [00:55<23:18, 686.83it/s]

  4%|▍         | 39000/998833 [00:56<22:37, 706.89it/s]

  4%|▍         | 40000/998833 [00:58<21:50, 731.68it/s]

  4%|▍         | 41000/998833 [00:59<22:18, 715.85it/s]

  4%|▍         | 42000/998833 [01:00<21:47, 731.56it/s]

  4%|▍         | 43000/998833 [01:02<22:12, 717.08it/s]

  4%|▍         | 44000/998833 [01:03<22:34, 704.88it/s]

  5%|▍         | 45000/998833 [01:05<22:06, 719.23it/s]

  5%|▍         | 46000/998833 [01:06<22:05, 719.04it/s]

  5%|▍         | 47000/998833 [01:07<22:04, 718.84it/s]

  5%|▍         | 48000/998833 [01:09<21:48, 726.61it/s]

  5%|▍         | 49000/998833 [01:10<22:02, 718.12it/s]

  5%|▌         | 50000/998833 [01:11<21:14, 744.45it/s]

  5%|▌         | 51000/998833 [01:13<21:06, 748.12it/s]

  5%|▌         | 52000/998833 [01:14<21:11, 744.81it/s]

  5%|▌         | 53000/998833 [01:16<22:02, 715.04it/s]

  5%|▌         | 54000/998833 [01:17<21:33, 730.52it/s]

  6%|▌         | 55000/998833 [01:18<20:15, 776.74it/s]

  6%|▌         | 56000/998833 [01:19<20:07, 781.04it/s]

  6%|▌         | 57000/998833 [01:21<20:16, 774.26it/s]

  6%|▌         | 58000/998833 [01:22<20:17, 773.05it/s]

  6%|▌         | 59000/998833 [01:23<19:44, 793.25it/s]

  6%|▌         | 60000/998833 [01:25<20:46, 753.41it/s]

  6%|▌         | 61000/998833 [01:26<20:46, 752.14it/s]

  6%|▌         | 62000/998833 [01:27<19:40, 793.53it/s]

  6%|▋         | 63000/998833 [01:28<19:50, 786.13it/s]

  6%|▋         | 64000/998833 [01:30<19:26, 801.16it/s]

  7%|▋         | 65000/998833 [01:31<20:01, 777.36it/s]

  7%|▋         | 66000/998833 [01:32<19:36, 792.58it/s]

  7%|▋         | 67000/998833 [01:33<19:40, 789.13it/s]

  7%|▋         | 68000/998833 [01:35<19:46, 784.60it/s]

  7%|▋         | 69000/998833 [01:36<19:45, 784.42it/s]

  7%|▋         | 70000/998833 [01:37<19:43, 784.97it/s]

  7%|▋         | 71000/998833 [01:39<20:28, 755.12it/s]

  7%|▋         | 72000/998833 [01:40<20:22, 758.44it/s]

  7%|▋         | 73000/998833 [01:41<20:01, 770.63it/s]

  7%|▋         | 74000/998833 [01:43<19:59, 771.00it/s]

  8%|▊         | 75000/998833 [01:44<19:55, 772.50it/s]

  8%|▊         | 76000/998833 [01:45<19:36, 784.53it/s]

  8%|▊         | 77000/998833 [01:46<20:08, 763.05it/s]

  8%|▊         | 78000/998833 [01:48<19:36, 783.01it/s]

  8%|▊         | 79000/998833 [01:49<19:05, 803.06it/s]

  8%|▊         | 80000/998833 [01:50<18:47, 815.02it/s]

  8%|▊         | 81000/998833 [01:51<19:32, 782.82it/s]

  8%|▊         | 82000/998833 [01:53<19:10, 797.02it/s]

  8%|▊         | 83000/998833 [01:54<18:56, 806.11it/s]

  8%|▊         | 84000/998833 [01:55<19:10, 794.95it/s]

  9%|▊         | 85000/998833 [01:56<19:11, 793.87it/s]

  9%|▊         | 86000/998833 [01:58<19:58, 761.35it/s]

  9%|▊         | 87000/998833 [01:59<19:27, 781.30it/s]

  9%|▉         | 88000/998833 [02:00<19:44, 769.15it/s]

  9%|▉         | 89000/998833 [02:02<20:10, 751.64it/s]

  9%|▉         | 90000/998833 [02:03<19:42, 768.35it/s]

  9%|▉         | 91000/998833 [02:04<19:45, 765.91it/s]

  9%|▉         | 92000/998833 [02:05<18:59, 795.67it/s]

  9%|▉         | 93000/998833 [02:07<19:00, 794.03it/s]

  9%|▉         | 94000/998833 [02:08<19:24, 777.02it/s]

 10%|▉         | 95000/998833 [02:09<18:44, 803.67it/s]

 10%|▉         | 96000/998833 [02:10<18:22, 818.56it/s]

 10%|▉         | 97000/998833 [02:12<18:33, 809.60it/s]

 10%|▉         | 98000/998833 [02:13<18:22, 817.25it/s]

 10%|▉         | 99000/998833 [02:14<18:38, 804.73it/s]

 10%|█         | 100000/998833 [02:15<18:19, 817.79it/s]

 10%|█         | 101000/998833 [02:17<18:26, 811.41it/s]

 10%|█         | 102000/998833 [02:18<17:49, 838.19it/s]

 10%|█         | 103000/998833 [02:19<17:50, 836.48it/s]

 10%|█         | 104000/998833 [02:20<18:08, 822.19it/s]

 11%|█         | 105000/998833 [02:21<18:41, 796.94it/s]

 11%|█         | 106000/998833 [02:23<18:36, 799.36it/s]

 11%|█         | 107000/998833 [02:24<18:55, 785.37it/s]

 11%|█         | 108000/998833 [02:25<18:47, 789.95it/s]

 11%|█         | 109000/998833 [02:27<18:32, 799.70it/s]

 11%|█         | 110000/998833 [02:28<18:42, 791.91it/s]

 11%|█         | 111000/998833 [02:29<18:13, 811.57it/s]

 11%|█         | 112000/998833 [02:30<18:03, 818.26it/s]

 11%|█▏        | 113000/998833 [02:31<18:09, 813.38it/s]

 11%|█▏        | 114000/998833 [02:33<18:43, 787.23it/s]

 12%|█▏        | 115000/998833 [02:34<18:29, 796.59it/s]

 12%|█▏        | 116000/998833 [02:35<18:46, 783.93it/s]

 12%|█▏        | 117000/998833 [02:37<18:27, 796.12it/s]

 12%|█▏        | 118000/998833 [02:38<18:20, 800.59it/s]

 12%|█▏        | 119000/998833 [02:39<17:50, 822.01it/s]

 12%|█▏        | 120000/998833 [02:40<17:47, 823.30it/s]

 12%|█▏        | 121000/998833 [02:41<17:47, 822.01it/s]

 12%|█▏        | 122000/998833 [02:43<18:13, 802.15it/s]

 12%|█▏        | 123000/998833 [02:44<18:51, 774.18it/s]

 12%|█▏        | 124000/998833 [02:45<18:57, 769.29it/s]

 13%|█▎        | 125000/998833 [02:47<18:25, 790.66it/s]

 13%|█▎        | 126000/998833 [02:48<18:35, 782.73it/s]

 13%|█▎        | 127000/998833 [02:49<18:29, 785.62it/s]

 13%|█▎        | 128000/998833 [02:50<18:07, 800.48it/s]

 13%|█▎        | 129000/998833 [02:52<18:29, 783.82it/s]

 13%|█▎        | 130000/998833 [02:53<20:20, 711.58it/s]

 13%|█▎        | 131000/998833 [02:55<20:17, 713.01it/s]

 13%|█▎        | 132000/998833 [02:56<19:35, 737.26it/s]

 13%|█▎        | 133000/998833 [02:57<19:25, 742.59it/s]

 13%|█▎        | 134000/998833 [02:58<18:23, 783.44it/s]

 14%|█▎        | 135000/998833 [03:00<18:11, 791.30it/s]

 14%|█▎        | 136000/998833 [03:01<18:37, 772.12it/s]

 14%|█▎        | 137000/998833 [03:02<18:07, 792.70it/s]

 14%|█▍        | 138000/998833 [03:03<17:34, 816.73it/s]

 14%|█▍        | 139000/998833 [03:05<17:58, 797.47it/s]

 14%|█▍        | 140000/998833 [03:06<17:48, 803.94it/s]

 14%|█▍        | 141000/998833 [03:07<17:58, 795.17it/s]

 14%|█▍        | 142000/998833 [03:09<18:22, 777.31it/s]

 14%|█▍        | 143000/998833 [03:10<18:30, 770.42it/s]

 14%|█▍        | 144000/998833 [03:11<18:37, 764.88it/s]

 15%|█▍        | 145000/998833 [03:12<17:37, 807.14it/s]

 15%|█▍        | 146000/998833 [03:14<17:47, 798.93it/s]

 15%|█▍        | 147000/998833 [03:15<18:01, 787.67it/s]

 15%|█▍        | 148000/998833 [03:16<17:56, 790.06it/s]

 15%|█▍        | 149000/998833 [03:18<18:34, 762.67it/s]

 15%|█▌        | 150000/998833 [03:19<18:06, 781.35it/s]

 15%|█▌        | 151000/998833 [03:20<18:03, 782.39it/s]

 15%|█▌        | 152000/998833 [03:21<17:42, 797.24it/s]

 15%|█▌        | 153000/998833 [03:22<17:22, 811.61it/s]

 15%|█▌        | 154000/998833 [03:24<17:37, 799.15it/s]

 16%|█▌        | 155000/998833 [03:25<17:51, 787.48it/s]

 16%|█▌        | 156000/998833 [03:26<17:38, 796.46it/s]

 16%|█▌        | 157000/998833 [03:27<17:34, 798.15it/s]

 16%|█▌        | 158000/998833 [03:29<17:36, 795.85it/s]

 16%|█▌        | 159000/998833 [03:30<17:25, 803.00it/s]

 16%|█▌        | 160000/998833 [03:31<17:29, 799.35it/s]

 16%|█▌        | 161000/998833 [03:33<17:48, 783.95it/s]

 16%|█▌        | 162000/998833 [03:34<17:27, 798.80it/s]

 16%|█▋        | 163000/998833 [03:35<18:09, 767.22it/s]

 16%|█▋        | 164000/998833 [03:36<17:58, 774.15it/s]

 17%|█▋        | 165000/998833 [03:38<18:01, 771.23it/s]

 17%|█▋        | 166000/998833 [03:39<18:08, 765.23it/s]

 17%|█▋        | 167000/998833 [03:40<17:49, 777.58it/s]

 17%|█▋        | 168000/998833 [03:42<17:57, 771.26it/s]

 17%|█▋        | 169000/998833 [03:43<17:45, 778.88it/s]

 17%|█▋        | 170000/998833 [03:44<17:34, 786.10it/s]

 17%|█▋        | 171000/998833 [03:45<17:29, 788.50it/s]

 17%|█▋        | 172000/998833 [03:47<17:18, 795.94it/s]

 17%|█▋        | 173000/998833 [03:48<17:25, 790.25it/s]

 17%|█▋        | 174000/998833 [03:49<16:53, 813.86it/s]

 18%|█▊        | 175000/998833 [03:50<17:18, 793.63it/s]

 18%|█▊        | 176000/998833 [03:52<16:40, 822.29it/s]

 18%|█▊        | 177000/998833 [03:53<17:10, 797.29it/s]

 18%|█▊        | 178000/998833 [03:54<16:57, 806.98it/s]

 18%|█▊        | 179000/998833 [03:55<17:04, 800.13it/s]

 18%|█▊        | 180000/998833 [03:57<17:21, 786.48it/s]

 18%|█▊        | 181000/998833 [03:58<17:29, 778.91it/s]

 18%|█▊        | 182000/998833 [03:59<17:12, 790.81it/s]

 18%|█▊        | 183000/998833 [04:00<17:15, 788.19it/s]

 18%|█▊        | 184000/998833 [04:02<17:28, 776.99it/s]

 19%|█▊        | 185000/998833 [04:03<17:35, 771.37it/s]

 19%|█▊        | 186000/998833 [04:04<17:44, 763.40it/s]

 19%|█▊        | 187000/998833 [04:06<17:53, 756.12it/s]

 19%|█▉        | 188000/998833 [04:07<17:32, 770.67it/s]

 19%|█▉        | 189000/998833 [04:08<17:32, 769.50it/s]

 19%|█▉        | 190000/998833 [04:10<18:06, 744.63it/s]

 19%|█▉        | 191000/998833 [04:11<17:46, 757.64it/s]

 19%|█▉        | 192000/998833 [04:12<18:06, 742.65it/s]

 19%|█▉        | 193000/998833 [04:14<17:59, 746.68it/s]

 19%|█▉        | 194000/998833 [04:15<18:20, 731.22it/s]

 20%|█▉        | 195000/998833 [04:17<18:09, 737.90it/s]

 20%|█▉        | 196000/998833 [04:18<17:55, 746.79it/s]

 20%|█▉        | 197000/998833 [04:19<17:53, 747.26it/s]

 20%|█▉        | 198000/998833 [04:20<17:43, 753.25it/s]

 20%|█▉        | 199000/998833 [04:22<18:06, 736.04it/s]

 20%|██        | 200000/998833 [04:23<18:07, 734.35it/s]

 20%|██        | 201000/998833 [04:25<18:04, 735.73it/s]

 20%|██        | 202000/998833 [04:26<18:04, 734.82it/s]

 20%|██        | 203000/998833 [04:28<18:33, 714.65it/s]

 20%|██        | 204000/998833 [04:29<18:27, 717.47it/s]

 21%|██        | 205000/998833 [04:30<18:18, 722.62it/s]

 21%|██        | 206000/998833 [04:32<17:48, 741.78it/s]

 21%|██        | 207000/998833 [04:33<17:51, 738.84it/s]

 21%|██        | 208000/998833 [04:34<18:54, 697.34it/s]

 21%|██        | 209000/998833 [04:36<18:55, 695.38it/s]

 21%|██        | 210000/998833 [04:37<18:32, 708.95it/s]

 21%|██        | 211000/998833 [04:39<18:09, 722.87it/s]

 21%|██        | 212000/998833 [04:40<18:21, 714.14it/s]

 21%|██▏       | 213000/998833 [04:41<18:12, 719.05it/s]

 21%|██▏       | 214000/998833 [04:43<18:09, 720.57it/s]

 22%|██▏       | 215000/998833 [04:44<18:15, 715.83it/s]

 22%|██▏       | 216000/998833 [04:46<18:33, 703.11it/s]

 22%|██▏       | 217000/998833 [04:47<18:33, 702.30it/s]

 22%|██▏       | 218000/998833 [04:49<18:33, 701.24it/s]

 22%|██▏       | 219000/998833 [04:50<18:10, 715.44it/s]

 22%|██▏       | 220000/998833 [04:51<18:31, 700.67it/s]

 22%|██▏       | 221000/998833 [04:53<18:28, 701.85it/s]

 22%|██▏       | 222000/998833 [04:54<18:48, 688.36it/s]

 22%|██▏       | 223000/998833 [04:56<18:08, 713.06it/s]

 22%|██▏       | 224000/998833 [04:57<18:12, 709.16it/s]

 23%|██▎       | 225000/998833 [04:59<18:27, 698.69it/s]

 23%|██▎       | 226000/998833 [05:00<18:32, 694.71it/s]

 23%|██▎       | 227000/998833 [05:01<18:17, 703.14it/s]

 23%|██▎       | 228000/998833 [05:03<18:12, 705.44it/s]

 23%|██▎       | 229000/998833 [05:04<18:14, 703.11it/s]

 23%|██▎       | 230000/998833 [05:05<17:40, 724.85it/s]

 23%|██▎       | 231000/998833 [05:07<17:31, 730.55it/s]

 23%|██▎       | 232000/998833 [05:08<17:34, 726.99it/s]

 23%|██▎       | 233000/998833 [05:10<17:35, 725.23it/s]

 23%|██▎       | 234000/998833 [05:11<17:48, 715.71it/s]

 24%|██▎       | 235000/998833 [05:12<17:49, 714.18it/s]

 24%|██▎       | 236000/998833 [05:14<17:47, 714.65it/s]

 24%|██▎       | 237000/998833 [05:15<17:30, 725.46it/s]

 24%|██▍       | 238000/998833 [05:17<17:19, 732.24it/s]

 24%|██▍       | 239000/998833 [05:18<17:19, 730.94it/s]

 24%|██▍       | 240000/998833 [05:19<17:50, 709.04it/s]

 24%|██▍       | 241000/998833 [05:21<18:01, 700.43it/s]

 24%|██▍       | 242000/998833 [05:22<17:35, 716.79it/s]

 24%|██▍       | 243000/998833 [05:23<17:09, 734.33it/s]

 24%|██▍       | 244000/998833 [05:25<17:06, 735.10it/s]

 25%|██▍       | 245000/998833 [05:26<16:53, 743.68it/s]

 25%|██▍       | 246000/998833 [05:27<16:29, 760.59it/s]

 25%|██▍       | 247000/998833 [05:29<16:39, 751.96it/s]

 25%|██▍       | 248000/998833 [05:30<16:51, 741.94it/s]

 25%|██▍       | 249000/998833 [05:31<16:33, 754.78it/s]

 25%|██▌       | 250000/998833 [05:33<16:01, 778.90it/s]

 25%|██▌       | 251000/998833 [05:34<16:04, 775.17it/s]

 25%|██▌       | 252000/998833 [05:35<16:23, 759.12it/s]

 25%|██▌       | 253000/998833 [05:36<15:28, 803.33it/s]

 25%|██▌       | 254000/998833 [05:38<15:48, 785.36it/s]

 26%|██▌       | 255000/998833 [05:39<15:49, 783.73it/s]

 26%|██▌       | 256000/998833 [05:40<15:20, 807.22it/s]

 26%|██▌       | 257000/998833 [05:41<15:21, 805.42it/s]

 26%|██▌       | 258000/998833 [05:43<15:30, 796.28it/s]

 26%|██▌       | 259000/998833 [05:44<15:41, 785.41it/s]

 26%|██▌       | 260000/998833 [05:45<15:31, 792.84it/s]

 26%|██▌       | 261000/998833 [05:46<15:10, 810.10it/s]

 26%|██▌       | 262000/998833 [05:48<15:32, 790.20it/s]

 26%|██▋       | 263000/998833 [05:49<15:59, 766.73it/s]

 26%|██▋       | 264000/998833 [05:50<15:59, 765.78it/s]

 27%|██▋       | 265000/998833 [05:52<15:57, 766.72it/s]

 27%|██▋       | 266000/998833 [05:53<15:54, 767.72it/s]

 27%|██▋       | 267000/998833 [05:54<15:49, 771.02it/s]

 27%|██▋       | 268000/998833 [05:55<15:13, 800.22it/s]

 27%|██▋       | 269000/998833 [05:57<15:02, 808.92it/s]

 27%|██▋       | 270000/998833 [05:58<15:25, 787.32it/s]

 27%|██▋       | 271000/998833 [05:59<15:07, 802.00it/s]

 27%|██▋       | 272000/998833 [06:01<15:30, 780.77it/s]

 27%|██▋       | 273000/998833 [06:02<15:30, 780.31it/s]

 27%|██▋       | 274000/998833 [06:03<15:07, 798.33it/s]

 28%|██▊       | 275000/998833 [06:04<15:04, 800.69it/s]

 28%|██▊       | 276000/998833 [06:06<15:06, 797.05it/s]

 28%|██▊       | 277000/998833 [06:07<14:52, 809.09it/s]

 28%|██▊       | 278000/998833 [06:08<14:38, 820.11it/s]

 28%|██▊       | 279000/998833 [06:09<14:23, 834.06it/s]

 28%|██▊       | 280000/998833 [06:10<13:51, 864.38it/s]

 28%|██▊       | 281000/998833 [06:11<14:34, 820.94it/s]

 28%|██▊       | 282000/998833 [06:13<14:51, 804.37it/s]

 28%|██▊       | 283000/998833 [06:14<14:43, 810.58it/s]

 28%|██▊       | 284000/998833 [06:15<14:26, 825.05it/s]

 29%|██▊       | 285000/998833 [06:16<14:29, 821.26it/s]

 29%|██▊       | 286000/998833 [06:17<14:04, 844.55it/s]

 29%|██▊       | 287000/998833 [06:19<14:22, 825.02it/s]

 29%|██▉       | 288000/998833 [06:20<14:48, 800.19it/s]

 29%|██▉       | 289000/998833 [06:21<15:04, 784.74it/s]

 29%|██▉       | 290000/998833 [06:23<15:11, 778.08it/s]

 29%|██▉       | 291000/998833 [06:24<15:05, 781.96it/s]

 29%|██▉       | 292000/998833 [06:25<15:05, 780.30it/s]

 29%|██▉       | 293000/998833 [06:26<14:49, 793.66it/s]

 29%|██▉       | 294000/998833 [06:28<14:50, 791.13it/s]

 30%|██▉       | 295000/998833 [06:29<14:34, 805.14it/s]

 30%|██▉       | 296000/998833 [06:30<14:26, 811.07it/s]

 30%|██▉       | 297000/998833 [06:31<14:37, 799.38it/s]

 30%|██▉       | 298000/998833 [06:33<14:53, 784.32it/s]

 30%|██▉       | 299000/998833 [06:34<15:04, 773.43it/s]

 30%|███       | 300000/998833 [06:35<15:16, 762.60it/s]

 30%|███       | 301000/998833 [06:37<15:04, 771.26it/s]

 30%|███       | 302000/998833 [06:38<15:18, 758.81it/s]

 30%|███       | 303000/998833 [06:39<15:29, 748.34it/s]

 30%|███       | 304000/998833 [06:41<14:55, 776.16it/s]

 31%|███       | 305000/998833 [06:42<15:17, 756.36it/s]

 31%|███       | 306000/998833 [06:43<14:48, 779.54it/s]

 31%|███       | 307000/998833 [06:45<14:59, 768.89it/s]

 31%|███       | 308000/998833 [06:46<14:36, 787.92it/s]

 31%|███       | 309000/998833 [06:47<14:48, 776.45it/s]

 31%|███       | 310000/998833 [06:48<14:48, 775.27it/s]

 31%|███       | 311000/998833 [06:50<14:05, 813.18it/s]

 31%|███       | 312000/998833 [06:51<13:50, 826.63it/s]

 31%|███▏      | 313000/998833 [06:52<14:23, 794.38it/s]

 31%|███▏      | 314000/998833 [06:53<14:29, 787.81it/s]

 32%|███▏      | 315000/998833 [06:54<14:03, 810.99it/s]

 32%|███▏      | 316000/998833 [06:56<13:49, 822.93it/s]

 32%|███▏      | 317000/998833 [06:57<13:44, 827.34it/s]

 32%|███▏      | 318000/998833 [06:58<14:02, 808.19it/s]

 32%|███▏      | 319000/998833 [07:00<14:32, 778.93it/s]

 32%|███▏      | 320000/998833 [07:01<14:14, 794.36it/s]

 32%|███▏      | 321000/998833 [07:02<14:11, 795.91it/s]

 32%|███▏      | 322000/998833 [07:03<13:57, 808.04it/s]

 32%|███▏      | 323000/998833 [07:04<13:50, 813.28it/s]

 32%|███▏      | 324000/998833 [07:06<13:47, 816.00it/s]

 33%|███▎      | 325000/998833 [07:07<14:09, 793.68it/s]

 33%|███▎      | 326000/998833 [07:08<14:29, 773.82it/s]

 33%|███▎      | 327000/998833 [07:10<14:03, 796.32it/s]

 33%|███▎      | 328000/998833 [07:11<13:57, 800.57it/s]

 33%|███▎      | 329000/998833 [07:12<14:10, 787.15it/s]

 33%|███▎      | 330000/998833 [07:13<13:47, 808.16it/s]

 33%|███▎      | 331000/998833 [07:15<14:30, 766.93it/s]

 33%|███▎      | 332000/998833 [07:16<14:25, 770.21it/s]

 33%|███▎      | 333000/998833 [07:17<14:32, 762.95it/s]

 33%|███▎      | 334000/998833 [07:19<14:32, 762.13it/s]

 34%|███▎      | 335000/998833 [07:20<14:17, 774.42it/s]

 34%|███▎      | 336000/998833 [07:21<14:34, 757.70it/s]

 34%|███▎      | 337000/998833 [07:22<14:04, 783.82it/s]

 34%|███▍      | 338000/998833 [07:24<14:11, 775.96it/s]

 34%|███▍      | 339000/998833 [07:25<14:03, 782.04it/s]

 34%|███▍      | 340000/998833 [07:26<13:51, 792.23it/s]

 34%|███▍      | 341000/998833 [07:28<13:57, 785.42it/s]

 34%|███▍      | 342000/998833 [07:29<13:28, 812.18it/s]

 34%|███▍      | 343000/998833 [07:30<13:15, 824.18it/s]

 34%|███▍      | 344000/998833 [07:31<13:25, 812.50it/s]

 35%|███▍      | 345000/998833 [07:32<13:26, 810.75it/s]

 35%|███▍      | 346000/998833 [07:34<13:18, 817.30it/s]

 35%|███▍      | 347000/998833 [07:35<13:04, 830.69it/s]

 35%|███▍      | 348000/998833 [07:36<13:07, 826.09it/s]

 35%|███▍      | 349000/998833 [07:37<13:10, 822.18it/s]

 35%|███▌      | 350000/998833 [07:38<13:03, 828.04it/s]

 35%|███▌      | 351000/998833 [07:40<12:55, 835.72it/s]

 35%|███▌      | 352000/998833 [07:41<12:41, 849.39it/s]

 35%|███▌      | 353000/998833 [07:42<13:00, 827.60it/s]

 35%|███▌      | 354000/998833 [07:43<13:20, 805.83it/s]

 36%|███▌      | 355000/998833 [07:44<12:42, 844.65it/s]

 36%|███▌      | 356000/998833 [07:46<13:03, 820.91it/s]

 36%|███▌      | 357000/998833 [07:47<12:57, 826.00it/s]

 36%|███▌      | 358000/998833 [07:48<12:49, 832.98it/s]

 36%|███▌      | 359000/998833 [07:49<12:56, 824.09it/s]

 36%|███▌      | 360000/998833 [07:51<13:13, 804.95it/s]

 36%|███▌      | 361000/998833 [07:52<13:23, 793.39it/s]

 36%|███▌      | 362000/998833 [07:53<13:36, 780.04it/s]

 36%|███▋      | 363000/998833 [07:54<12:56, 818.95it/s]

 36%|███▋      | 364000/998833 [07:56<13:33, 780.04it/s]

 37%|███▋      | 365000/998833 [07:57<13:21, 790.70it/s]

 37%|███▋      | 366000/998833 [07:58<13:39, 772.61it/s]

 37%|███▋      | 367000/998833 [07:59<12:44, 826.00it/s]

 37%|███▋      | 368000/998833 [08:00<12:29, 841.77it/s]

 37%|███▋      | 369000/998833 [08:02<12:39, 828.88it/s]

 37%|███▋      | 370000/998833 [08:03<12:55, 810.99it/s]

 37%|███▋      | 371000/998833 [08:04<12:38, 827.67it/s]

 37%|███▋      | 372000/998833 [08:05<12:40, 824.57it/s]

 37%|███▋      | 373000/998833 [08:07<13:07, 794.36it/s]

 37%|███▋      | 374000/998833 [08:08<13:31, 770.09it/s]

 38%|███▊      | 375000/998833 [08:09<13:47, 753.89it/s]

 38%|███▊      | 376000/998833 [08:11<13:35, 763.31it/s]

 38%|███▊      | 377000/998833 [08:12<13:25, 772.32it/s]

 38%|███▊      | 378000/998833 [08:13<13:09, 786.73it/s]

 38%|███▊      | 379000/998833 [08:14<12:43, 812.05it/s]

 38%|███▊      | 380000/998833 [08:15<12:24, 830.65it/s]

 38%|███▊      | 381000/998833 [08:17<12:32, 821.23it/s]

 38%|███▊      | 382000/998833 [08:18<12:31, 821.09it/s]

 38%|███▊      | 383000/998833 [08:19<13:08, 780.68it/s]

 38%|███▊      | 384000/998833 [08:21<13:03, 784.70it/s]

 39%|███▊      | 385000/998833 [08:22<12:43, 803.61it/s]

 39%|███▊      | 386000/998833 [08:23<12:49, 796.06it/s]

 39%|███▊      | 387000/998833 [08:24<12:38, 806.20it/s]

 39%|███▉      | 388000/998833 [08:26<12:58, 784.95it/s]

 39%|███▉      | 389000/998833 [08:27<13:00, 780.85it/s]

 39%|███▉      | 390000/998833 [08:28<12:40, 800.23it/s]

 39%|███▉      | 391000/998833 [08:29<13:02, 777.26it/s]

 39%|███▉      | 392000/998833 [08:31<12:58, 779.18it/s]

 39%|███▉      | 393000/998833 [08:32<13:00, 776.43it/s]

 39%|███▉      | 394000/998833 [08:33<12:52, 782.82it/s]

 40%|███▉      | 395000/998833 [08:35<12:49, 784.99it/s]

 40%|███▉      | 396000/998833 [08:36<12:34, 799.13it/s]

 40%|███▉      | 397000/998833 [08:37<12:36, 795.06it/s]

 40%|███▉      | 398000/998833 [08:38<12:50, 779.94it/s]

 40%|███▉      | 399000/998833 [08:40<12:32, 797.05it/s]

 40%|████      | 400000/998833 [08:41<12:41, 786.13it/s]

 40%|████      | 401000/998833 [08:42<13:08, 758.52it/s]

 40%|████      | 402000/998833 [08:43<12:38, 786.66it/s]

 40%|████      | 403000/998833 [08:45<12:16, 809.52it/s]

 40%|████      | 404000/998833 [08:46<12:33, 789.85it/s]

 41%|████      | 405000/998833 [08:47<12:22, 799.63it/s]

 41%|████      | 406000/998833 [08:49<12:39, 780.31it/s]

 41%|████      | 407000/998833 [08:50<12:07, 813.76it/s]

 41%|████      | 408000/998833 [08:51<12:17, 801.38it/s]

 41%|████      | 409000/998833 [08:52<12:05, 813.13it/s]

 41%|████      | 410000/998833 [08:53<11:53, 824.93it/s]

 41%|████      | 411000/998833 [08:55<11:51, 826.67it/s]

 41%|████      | 412000/998833 [08:56<11:43, 834.73it/s]

 41%|████▏     | 413000/998833 [08:57<11:42, 834.25it/s]

 41%|████▏     | 414000/998833 [08:58<11:58, 814.03it/s]

 42%|████▏     | 415000/998833 [09:00<12:14, 795.11it/s]

 42%|████▏     | 416000/998833 [09:01<12:33, 773.79it/s]

 42%|████▏     | 417000/998833 [09:02<12:20, 786.22it/s]

 42%|████▏     | 418000/998833 [09:03<12:13, 792.13it/s]

 42%|████▏     | 419000/998833 [09:05<12:00, 804.29it/s]

 42%|████▏     | 420000/998833 [09:06<12:19, 782.62it/s]

 42%|████▏     | 421000/998833 [09:07<12:16, 784.47it/s]

 42%|████▏     | 422000/998833 [09:09<12:28, 770.41it/s]

 42%|████▏     | 423000/998833 [09:10<12:21, 776.41it/s]

 42%|████▏     | 424000/998833 [09:11<12:14, 782.66it/s]

 43%|████▎     | 425000/998833 [09:12<11:53, 803.81it/s]

 43%|████▎     | 426000/998833 [09:14<12:07, 787.73it/s]

 43%|████▎     | 427000/998833 [09:15<12:34, 758.12it/s]

 43%|████▎     | 428000/998833 [09:16<12:48, 743.16it/s]

 43%|████▎     | 429000/998833 [09:18<13:06, 724.08it/s]

 43%|████▎     | 430000/998833 [09:19<13:15, 715.42it/s]

 43%|████▎     | 431000/998833 [09:21<12:55, 732.16it/s]

 43%|████▎     | 432000/998833 [09:22<13:02, 724.12it/s]

 43%|████▎     | 433000/998833 [09:23<12:42, 742.24it/s]

 43%|████▎     | 434000/998833 [09:25<12:36, 746.94it/s]

 44%|████▎     | 435000/998833 [09:26<12:11, 770.66it/s]

 44%|████▎     | 436000/998833 [09:27<12:06, 775.23it/s]

 44%|████▍     | 437000/998833 [09:28<11:50, 790.60it/s]

 44%|████▍     | 438000/998833 [09:29<11:32, 810.11it/s]

 44%|████▍     | 439000/998833 [09:31<11:57, 780.35it/s]

 44%|████▍     | 440000/998833 [09:32<11:54, 782.14it/s]

 44%|████▍     | 441000/998833 [09:33<11:57, 777.78it/s]

 44%|████▍     | 442000/998833 [09:35<12:04, 768.56it/s]

 44%|████▍     | 443000/998833 [09:36<11:29, 806.50it/s]

 44%|████▍     | 444000/998833 [09:37<11:18, 817.33it/s]

 45%|████▍     | 445000/998833 [09:38<11:06, 830.36it/s]

 45%|████▍     | 446000/998833 [09:39<11:08, 826.71it/s]

 45%|████▍     | 447000/998833 [09:41<11:11, 821.77it/s]

 45%|████▍     | 448000/998833 [09:42<11:19, 810.57it/s]

 45%|████▍     | 449000/998833 [09:43<11:49, 774.44it/s]

 45%|████▌     | 450000/998833 [09:44<11:29, 795.51it/s]

 45%|████▌     | 451000/998833 [09:46<12:00, 760.03it/s]

 45%|████▌     | 452000/998833 [09:47<11:49, 770.86it/s]

 45%|████▌     | 453000/998833 [09:49<11:54, 763.86it/s]

 45%|████▌     | 454000/998833 [09:50<12:30, 725.80it/s]

 46%|████▌     | 455000/998833 [09:52<12:39, 716.12it/s]

 46%|████▌     | 456000/998833 [09:53<12:37, 716.23it/s]

 46%|████▌     | 457000/998833 [09:54<12:10, 741.67it/s]

 46%|████▌     | 458000/998833 [09:55<11:51, 760.40it/s]

 46%|████▌     | 459000/998833 [09:57<11:54, 755.06it/s]

 46%|████▌     | 460000/998833 [09:58<11:30, 780.25it/s]

 46%|████▌     | 461000/998833 [09:59<11:31, 777.97it/s]

 46%|████▋     | 462000/998833 [10:00<11:15, 794.58it/s]

 46%|████▋     | 463000/998833 [10:02<11:07, 802.65it/s]

 46%|████▋     | 464000/998833 [10:03<11:44, 759.60it/s]

 47%|████▋     | 465000/998833 [10:05<12:37, 704.57it/s]

 47%|████▋     | 466000/998833 [10:07<13:29, 658.31it/s]

 47%|████▋     | 467000/998833 [10:08<13:30, 656.06it/s]

 47%|████▋     | 468000/998833 [10:10<14:11, 623.53it/s]

 47%|████▋     | 469000/998833 [10:12<14:44, 598.81it/s]

 47%|████▋     | 470000/998833 [10:13<14:32, 606.13it/s]

 47%|████▋     | 471000/998833 [10:15<14:21, 612.74it/s]

 47%|████▋     | 472000/998833 [10:16<14:15, 615.89it/s]

 47%|████▋     | 473000/998833 [10:18<14:18, 612.43it/s]

 47%|████▋     | 474000/998833 [10:20<14:03, 622.41it/s]

 48%|████▊     | 475000/998833 [10:21<13:52, 629.14it/s]

 48%|████▊     | 476000/998833 [10:23<13:55, 625.44it/s]

 48%|████▊     | 477000/998833 [10:24<13:40, 636.30it/s]

 48%|████▊     | 478000/998833 [10:26<13:07, 661.76it/s]

 48%|████▊     | 479000/998833 [10:27<12:56, 669.67it/s]

 48%|████▊     | 480000/998833 [10:29<12:39, 682.94it/s]

 48%|████▊     | 481000/998833 [10:30<12:46, 676.00it/s]

 48%|████▊     | 482000/998833 [10:32<12:45, 674.86it/s]

 48%|████▊     | 483000/998833 [10:33<12:44, 675.04it/s]

 48%|████▊     | 484000/998833 [10:34<12:38, 678.86it/s]

 49%|████▊     | 485000/998833 [10:36<12:52, 664.73it/s]

 49%|████▊     | 486000/998833 [10:38<12:47, 668.53it/s]

 49%|████▉     | 487000/998833 [10:39<12:57, 658.70it/s]

 49%|████▉     | 488000/998833 [10:41<12:43, 669.10it/s]

 49%|████▉     | 489000/998833 [10:42<12:29, 680.31it/s]

 49%|████▉     | 490000/998833 [10:43<12:24, 683.60it/s]

 49%|████▉     | 491000/998833 [10:45<12:10, 695.36it/s]

 49%|████▉     | 492000/998833 [10:46<12:06, 697.49it/s]

 49%|████▉     | 493000/998833 [10:48<12:12, 690.66it/s]

 49%|████▉     | 494000/998833 [10:49<12:11, 690.02it/s]

 50%|████▉     | 495000/998833 [10:51<12:10, 690.09it/s]

 50%|████▉     | 496000/998833 [10:52<12:18, 681.11it/s]

 50%|████▉     | 497000/998833 [10:54<12:50, 651.33it/s]

 50%|████▉     | 498000/998833 [10:55<12:18, 677.79it/s]

 50%|████▉     | 499000/998833 [10:56<12:00, 693.66it/s]

 50%|█████     | 500000/998833 [10:58<11:56, 696.64it/s]

 50%|█████     | 501000/998833 [10:59<11:58, 693.13it/s]

 50%|█████     | 502000/998833 [11:01<12:09, 681.10it/s]

 50%|█████     | 503000/998833 [11:02<12:07, 681.28it/s]

 50%|█████     | 504000/998833 [11:04<12:15, 672.77it/s]

 51%|█████     | 505000/998833 [11:05<12:19, 667.43it/s]

 51%|█████     | 506000/998833 [11:07<12:17, 668.59it/s]

 51%|█████     | 507000/998833 [11:08<12:18, 666.10it/s]

 51%|█████     | 508000/998833 [11:10<12:22, 661.50it/s]

 51%|█████     | 509000/998833 [11:11<12:10, 670.44it/s]

 51%|█████     | 510000/998833 [11:13<12:01, 677.94it/s]

 51%|█████     | 511000/998833 [11:14<11:42, 694.32it/s]

 51%|█████▏    | 512000/998833 [11:16<11:49, 685.81it/s]

 51%|█████▏    | 513000/998833 [11:17<12:00, 674.39it/s]

 51%|█████▏    | 514000/998833 [11:19<11:38, 693.86it/s]

 52%|█████▏    | 515000/998833 [11:20<11:52, 678.83it/s]

 52%|█████▏    | 516000/998833 [11:22<11:39, 690.67it/s]

 52%|█████▏    | 517000/998833 [11:23<11:32, 695.75it/s]

 52%|█████▏    | 518000/998833 [11:24<11:30, 695.92it/s]

 52%|█████▏    | 519000/998833 [11:26<11:31, 693.72it/s]

 52%|█████▏    | 520000/998833 [11:27<11:45, 679.09it/s]

 52%|█████▏    | 521000/998833 [11:29<11:58, 665.13it/s]

 52%|█████▏    | 522000/998833 [11:30<12:00, 662.24it/s]

 52%|█████▏    | 523000/998833 [11:32<12:16, 645.90it/s]

 52%|█████▏    | 524000/998833 [11:34<12:15, 645.81it/s]

 53%|█████▎    | 525000/998833 [11:35<11:41, 675.00it/s]

 53%|█████▎    | 526000/998833 [11:36<11:34, 681.09it/s]

 53%|█████▎    | 527000/998833 [11:38<11:43, 670.59it/s]

 53%|█████▎    | 528000/998833 [11:39<11:24, 687.48it/s]

 53%|█████▎    | 529000/998833 [11:41<12:17, 637.09it/s]

 53%|█████▎    | 530000/998833 [11:43<12:42, 614.52it/s]

 53%|█████▎    | 531000/998833 [11:45<12:45, 611.41it/s]

 53%|█████▎    | 532000/998833 [11:46<12:24, 626.77it/s]

 53%|█████▎    | 533000/998833 [11:48<12:13, 634.67it/s]

 53%|█████▎    | 534000/998833 [11:49<11:47, 657.08it/s]

 54%|█████▎    | 535000/998833 [11:51<12:02, 642.18it/s]

 54%|█████▎    | 536000/998833 [11:52<11:44, 656.76it/s]

 54%|█████▍    | 537000/998833 [11:54<12:05, 636.92it/s]

 54%|█████▍    | 538000/998833 [11:55<11:43, 654.87it/s]

 54%|█████▍    | 539000/998833 [11:57<11:34, 662.04it/s]

 54%|█████▍    | 540000/998833 [11:58<11:29, 665.92it/s]

 54%|█████▍    | 541000/998833 [12:00<11:42, 652.18it/s]

 54%|█████▍    | 542000/998833 [12:01<11:57, 636.92it/s]

 54%|█████▍    | 543000/998833 [12:03<11:35, 655.34it/s]

 54%|█████▍    | 544000/998833 [12:05<11:50, 639.86it/s]

 55%|█████▍    | 545000/998833 [12:06<11:39, 648.45it/s]

 55%|█████▍    | 546000/998833 [12:08<11:35, 650.97it/s]

 55%|█████▍    | 547000/998833 [12:09<11:46, 639.18it/s]

 55%|█████▍    | 548000/998833 [12:11<11:51, 633.49it/s]

 55%|█████▍    | 549000/998833 [12:12<11:48, 634.55it/s]

 55%|█████▌    | 550000/998833 [12:14<11:53, 629.40it/s]

 55%|█████▌    | 551000/998833 [12:15<11:34, 644.43it/s]

 55%|█████▌    | 552000/998833 [12:17<11:34, 643.78it/s]

 55%|█████▌    | 553000/998833 [12:18<11:22, 652.81it/s]

 55%|█████▌    | 554000/998833 [12:20<11:23, 650.35it/s]

 56%|█████▌    | 555000/998833 [12:22<11:28, 644.80it/s]

 56%|█████▌    | 556000/998833 [12:23<11:18, 652.55it/s]

 56%|█████▌    | 557000/998833 [12:25<11:06, 663.02it/s]

 56%|█████▌    | 558000/998833 [12:26<10:56, 671.33it/s]

 56%|█████▌    | 559000/998833 [12:28<11:02, 664.11it/s]

 56%|█████▌    | 560000/998833 [12:29<11:10, 654.59it/s]

 56%|█████▌    | 561000/998833 [12:31<11:13, 650.27it/s]

 56%|█████▋    | 562000/998833 [12:32<11:24, 637.85it/s]

 56%|█████▋    | 563000/998833 [12:34<11:10, 649.95it/s]

 56%|█████▋    | 564000/998833 [12:35<11:15, 643.42it/s]

 57%|█████▋    | 565000/998833 [12:37<11:11, 646.34it/s]

 57%|█████▋    | 566000/998833 [12:38<11:06, 649.54it/s]

 57%|█████▋    | 567000/998833 [12:40<11:05, 648.74it/s]

 57%|█████▋    | 568000/998833 [12:42<11:06, 646.57it/s]

 57%|█████▋    | 569000/998833 [12:43<10:59, 651.47it/s]

 57%|█████▋    | 570000/998833 [12:45<11:00, 649.67it/s]

 57%|█████▋    | 571000/998833 [12:46<10:55, 652.23it/s]

 57%|█████▋    | 572000/998833 [12:48<10:54, 652.10it/s]

 57%|█████▋    | 573000/998833 [12:49<10:51, 653.78it/s]

 57%|█████▋    | 574000/998833 [12:51<10:48, 655.27it/s]

 58%|█████▊    | 575000/998833 [12:52<10:41, 660.41it/s]

 58%|█████▊    | 576000/998833 [12:54<10:54, 646.20it/s]

 58%|█████▊    | 577000/998833 [12:55<10:55, 643.54it/s]

 58%|█████▊    | 578000/998833 [12:57<10:48, 648.69it/s]

 58%|█████▊    | 579000/998833 [12:58<10:32, 663.79it/s]

 58%|█████▊    | 580000/998833 [13:00<10:39, 654.90it/s]

 58%|█████▊    | 581000/998833 [13:01<10:31, 662.00it/s]

 58%|█████▊    | 582000/998833 [13:03<10:33, 658.29it/s]

 58%|█████▊    | 583000/998833 [13:05<10:54, 635.22it/s]

 58%|█████▊    | 584000/998833 [13:06<10:46, 641.86it/s]

 59%|█████▊    | 585000/998833 [13:08<10:38, 648.34it/s]

 59%|█████▊    | 586000/998833 [13:09<10:43, 641.25it/s]

 59%|█████▉    | 587000/998833 [13:11<10:36, 646.91it/s]

 59%|█████▉    | 588000/998833 [13:12<10:50, 631.71it/s]

 59%|█████▉    | 589000/998833 [13:14<10:47, 632.48it/s]

 59%|█████▉    | 590000/998833 [13:15<10:37, 641.08it/s]

 59%|█████▉    | 591000/998833 [13:17<10:30, 646.95it/s]

 59%|█████▉    | 592000/998833 [13:19<10:30, 644.95it/s]

 59%|█████▉    | 593000/998833 [13:20<10:33, 640.33it/s]

 59%|█████▉    | 594000/998833 [13:22<10:36, 636.23it/s]

 60%|█████▉    | 595000/998833 [13:23<10:26, 644.64it/s]

 60%|█████▉    | 596000/998833 [13:25<10:24, 645.52it/s]

 60%|█████▉    | 597000/998833 [13:26<10:39, 628.70it/s]

 60%|█████▉    | 598000/998833 [13:28<10:25, 640.60it/s]

 60%|█████▉    | 599000/998833 [13:30<10:23, 641.27it/s]

 60%|██████    | 600000/998833 [13:31<10:12, 650.77it/s]

 60%|██████    | 601000/998833 [13:33<10:13, 648.03it/s]

 60%|██████    | 602000/998833 [13:34<10:02, 658.62it/s]

 60%|██████    | 603000/998833 [13:35<09:49, 671.06it/s]

 60%|██████    | 604000/998833 [13:37<09:48, 671.35it/s]

 61%|██████    | 605000/998833 [13:38<09:52, 665.00it/s]

 61%|██████    | 606000/998833 [13:40<10:05, 648.84it/s]

 61%|██████    | 607000/998833 [13:42<10:06, 646.50it/s]

 61%|██████    | 608000/998833 [13:43<10:00, 650.84it/s]

 61%|██████    | 609000/998833 [13:45<09:59, 649.77it/s]

 61%|██████    | 610000/998833 [13:46<10:03, 644.31it/s]

 61%|██████    | 611000/998833 [13:48<10:11, 633.88it/s]

 61%|██████▏   | 612000/998833 [13:49<10:09, 634.50it/s]

 61%|██████▏   | 613000/998833 [13:51<10:22, 619.82it/s]

 61%|██████▏   | 614000/998833 [13:53<10:19, 621.07it/s]

 62%|██████▏   | 615000/998833 [13:54<10:03, 636.29it/s]

 62%|██████▏   | 616000/998833 [13:56<10:11, 625.72it/s]

 62%|██████▏   | 617000/998833 [13:57<10:05, 631.07it/s]

 62%|██████▏   | 618000/998833 [13:59<10:03, 631.14it/s]

 62%|██████▏   | 619000/998833 [14:01<09:58, 634.74it/s]

 62%|██████▏   | 620000/998833 [14:02<09:48, 643.35it/s]

 62%|██████▏   | 621000/998833 [14:04<09:40, 650.88it/s]

 62%|██████▏   | 622000/998833 [14:05<09:38, 651.84it/s]

 62%|██████▏   | 623000/998833 [14:07<09:39, 649.01it/s]

 62%|██████▏   | 624000/998833 [14:08<09:49, 636.14it/s]

 63%|██████▎   | 625000/998833 [14:10<10:00, 622.95it/s]

 63%|██████▎   | 626000/998833 [14:12<09:58, 623.09it/s]

 63%|██████▎   | 627000/998833 [14:13<09:39, 641.37it/s]

 63%|██████▎   | 628000/998833 [14:15<09:35, 644.61it/s]

 63%|██████▎   | 629000/998833 [14:16<09:28, 651.05it/s]

 63%|██████▎   | 630000/998833 [14:18<09:28, 648.63it/s]

 63%|██████▎   | 631000/998833 [14:19<09:18, 658.59it/s]

 63%|██████▎   | 632000/998833 [14:21<09:30, 643.22it/s]

 63%|██████▎   | 633000/998833 [14:22<09:31, 639.60it/s]

 63%|██████▎   | 634000/998833 [14:24<09:35, 634.37it/s]

 64%|██████▎   | 635000/998833 [14:26<09:30, 637.32it/s]

 64%|██████▎   | 636000/998833 [14:27<09:26, 640.24it/s]

 64%|██████▍   | 637000/998833 [14:29<09:28, 636.12it/s]

 64%|██████▍   | 638000/998833 [14:30<09:24, 639.29it/s]

 64%|██████▍   | 639000/998833 [14:32<09:22, 639.39it/s]

 64%|██████▍   | 640000/998833 [14:33<09:21, 639.23it/s]

 64%|██████▍   | 641000/998833 [14:35<09:15, 643.63it/s]

 64%|██████▍   | 642000/998833 [14:37<09:32, 623.79it/s]

 64%|██████▍   | 643000/998833 [14:38<09:22, 632.68it/s]

 64%|██████▍   | 644000/998833 [14:40<09:02, 653.77it/s]

 65%|██████▍   | 645000/998833 [14:41<09:04, 649.71it/s]

 65%|██████▍   | 646000/998833 [14:43<09:10, 641.02it/s]

 65%|██████▍   | 647000/998833 [14:44<09:04, 645.85it/s]

 65%|██████▍   | 648000/998833 [14:46<09:05, 643.09it/s]

 65%|██████▍   | 649000/998833 [14:47<09:01, 646.50it/s]

 65%|██████▌   | 650000/998833 [14:49<09:11, 632.10it/s]

 65%|██████▌   | 651000/998833 [14:51<09:13, 628.55it/s]

 65%|██████▌   | 652000/998833 [14:52<09:26, 612.49it/s]

 65%|██████▌   | 653000/998833 [14:54<09:13, 625.30it/s]

 65%|██████▌   | 654000/998833 [14:55<09:04, 633.41it/s]

 66%|██████▌   | 655000/998833 [14:57<09:10, 624.03it/s]

 66%|██████▌   | 656000/998833 [14:58<08:50, 646.82it/s]

 66%|██████▌   | 657000/998833 [15:00<08:43, 653.36it/s]

 66%|██████▌   | 658000/998833 [15:02<08:49, 643.58it/s]

 66%|██████▌   | 659000/998833 [15:03<08:56, 633.13it/s]

 66%|██████▌   | 660000/998833 [15:05<09:05, 621.69it/s]

 66%|██████▌   | 661000/998833 [15:06<08:54, 632.07it/s]

 66%|██████▋   | 662000/998833 [15:08<08:54, 630.43it/s]

 66%|██████▋   | 663000/998833 [15:10<08:57, 624.62it/s]

 66%|██████▋   | 664000/998833 [15:11<08:52, 628.81it/s]

 67%|██████▋   | 665000/998833 [15:13<08:54, 624.80it/s]

 67%|██████▋   | 666000/998833 [15:14<08:52, 624.90it/s]

 67%|██████▋   | 667000/998833 [15:16<08:48, 627.32it/s]

 67%|██████▋   | 668000/998833 [15:18<08:41, 634.44it/s]

 67%|██████▋   | 669000/998833 [15:19<08:43, 630.50it/s]

 67%|██████▋   | 670000/998833 [15:21<08:38, 634.45it/s]

 67%|██████▋   | 671000/998833 [15:22<08:37, 634.09it/s]

 67%|██████▋   | 672000/998833 [15:24<08:36, 632.70it/s]

 67%|██████▋   | 673000/998833 [15:25<08:32, 635.85it/s]

 67%|██████▋   | 674000/998833 [15:27<08:23, 645.15it/s]

 68%|██████▊   | 675000/998833 [15:28<08:25, 640.08it/s]

 68%|██████▊   | 676000/998833 [15:30<08:31, 631.60it/s]

 68%|██████▊   | 677000/998833 [15:32<08:23, 638.63it/s]

 68%|██████▊   | 678000/998833 [15:33<08:22, 639.06it/s]

 68%|██████▊   | 679000/998833 [15:35<08:22, 635.99it/s]

 68%|██████▊   | 680000/998833 [15:36<08:25, 630.79it/s]

 68%|██████▊   | 681000/998833 [15:38<08:13, 644.43it/s]

 68%|██████▊   | 682000/998833 [15:39<08:16, 638.65it/s]

 68%|██████▊   | 683000/998833 [15:41<08:21, 629.70it/s]

 68%|██████▊   | 684000/998833 [15:43<08:19, 629.94it/s]

 69%|██████▊   | 685000/998833 [15:44<08:26, 620.06it/s]

 69%|██████▊   | 686000/998833 [15:46<08:17, 628.93it/s]

 69%|██████▉   | 687000/998833 [15:48<08:16, 628.01it/s]

 69%|██████▉   | 688000/998833 [15:49<08:14, 629.12it/s]

 69%|██████▉   | 689000/998833 [15:51<07:59, 645.87it/s]

 69%|██████▉   | 690000/998833 [15:52<08:06, 634.93it/s]

 69%|██████▉   | 691000/998833 [15:54<08:01, 638.88it/s]

 69%|██████▉   | 692000/998833 [15:55<07:50, 652.36it/s]

 69%|██████▉   | 693000/998833 [15:57<07:48, 652.58it/s]

 69%|██████▉   | 694000/998833 [15:58<07:56, 639.63it/s]

 70%|██████▉   | 695000/998833 [16:00<07:50, 646.02it/s]

 70%|██████▉   | 696000/998833 [16:01<07:48, 646.79it/s]

 70%|██████▉   | 697000/998833 [16:03<07:53, 638.09it/s]

 70%|██████▉   | 698000/998833 [16:05<07:44, 647.39it/s]

 70%|██████▉   | 699000/998833 [16:06<07:39, 652.19it/s]

 70%|███████   | 700000/998833 [16:08<07:36, 654.93it/s]

 70%|███████   | 701000/998833 [16:09<07:29, 662.90it/s]

 70%|███████   | 702000/998833 [16:11<07:33, 654.21it/s]

 70%|███████   | 703000/998833 [16:12<07:41, 641.17it/s]

 70%|███████   | 704000/998833 [16:14<07:36, 645.40it/s]

 71%|███████   | 705000/998833 [16:15<07:33, 647.58it/s]

 71%|███████   | 706000/998833 [16:17<07:32, 646.66it/s]

 71%|███████   | 707000/998833 [16:18<07:29, 649.83it/s]

 71%|███████   | 708000/998833 [16:20<07:32, 643.40it/s]

 71%|███████   | 709000/998833 [16:21<07:29, 644.63it/s]

 71%|███████   | 710000/998833 [16:23<07:28, 643.62it/s]

 71%|███████   | 711000/998833 [16:25<07:39, 626.63it/s]

 71%|███████▏  | 712000/998833 [16:26<07:42, 619.69it/s]

 71%|███████▏  | 713000/998833 [16:28<07:29, 636.40it/s]

 71%|███████▏  | 714000/998833 [16:29<07:23, 642.06it/s]

 72%|███████▏  | 715000/998833 [16:31<07:26, 635.74it/s]

 72%|███████▏  | 716000/998833 [16:33<07:24, 636.83it/s]

 72%|███████▏  | 717000/998833 [16:34<07:24, 633.65it/s]

 72%|███████▏  | 718000/998833 [16:36<07:28, 626.49it/s]

 72%|███████▏  | 719000/998833 [16:38<07:37, 611.11it/s]

 72%|███████▏  | 720000/998833 [16:39<07:21, 630.96it/s]

 72%|███████▏  | 721000/998833 [16:41<07:27, 621.55it/s]

 72%|███████▏  | 722000/998833 [16:42<07:21, 626.52it/s]

 72%|███████▏  | 723000/998833 [16:44<07:16, 631.60it/s]

 72%|███████▏  | 724000/998833 [16:45<07:06, 644.68it/s]

 73%|███████▎  | 725000/998833 [16:47<06:57, 655.47it/s]

 73%|███████▎  | 726000/998833 [16:48<06:54, 658.00it/s]

 73%|███████▎  | 727000/998833 [16:50<06:50, 662.71it/s]

 73%|███████▎  | 728000/998833 [16:51<06:41, 674.18it/s]

 73%|███████▎  | 729000/998833 [16:53<06:41, 672.86it/s]

 73%|███████▎  | 730000/998833 [16:54<06:49, 656.96it/s]

 73%|███████▎  | 731000/998833 [16:56<06:41, 666.97it/s]

 73%|███████▎  | 732000/998833 [16:57<06:36, 672.14it/s]

 73%|███████▎  | 733000/998833 [16:59<06:35, 672.28it/s]

 73%|███████▎  | 734000/998833 [17:00<06:28, 680.99it/s]

 74%|███████▎  | 735000/998833 [17:02<06:41, 656.75it/s]

 74%|███████▎  | 736000/998833 [17:03<06:49, 641.11it/s]

 74%|███████▍  | 737000/998833 [17:05<06:46, 644.31it/s]

 74%|███████▍  | 738000/998833 [17:06<06:46, 641.73it/s]

 74%|███████▍  | 739000/998833 [17:08<06:44, 642.61it/s]

 74%|███████▍  | 740000/998833 [17:09<06:37, 651.83it/s]

 74%|███████▍  | 741000/998833 [17:11<06:34, 653.65it/s]

 74%|███████▍  | 742000/998833 [17:12<06:25, 665.99it/s]

 74%|███████▍  | 743000/998833 [17:14<06:17, 678.25it/s]

 74%|███████▍  | 744000/998833 [17:15<06:22, 667.00it/s]

 75%|███████▍  | 745000/998833 [17:17<06:24, 660.58it/s]

 75%|███████▍  | 746000/998833 [17:18<06:24, 657.93it/s]

 75%|███████▍  | 747000/998833 [17:20<06:24, 654.73it/s]

 75%|███████▍  | 748000/998833 [17:22<06:30, 641.61it/s]

 75%|███████▍  | 749000/998833 [17:23<06:29, 641.46it/s]

 75%|███████▌  | 750000/998833 [17:25<06:26, 644.55it/s]

 75%|███████▌  | 751000/998833 [17:26<06:28, 637.93it/s]

 75%|███████▌  | 752000/998833 [17:28<06:26, 638.16it/s]

 75%|███████▌  | 753000/998833 [17:30<06:24, 638.55it/s]

 75%|███████▌  | 754000/998833 [17:31<06:16, 649.91it/s]

 76%|███████▌  | 755000/998833 [17:32<06:10, 658.36it/s]

 76%|███████▌  | 756000/998833 [17:34<06:16, 645.03it/s]

 76%|███████▌  | 757000/998833 [17:36<06:13, 647.45it/s]

 76%|███████▌  | 758000/998833 [17:37<06:00, 668.80it/s]

 76%|███████▌  | 759000/998833 [17:39<06:00, 664.80it/s]

 76%|███████▌  | 760000/998833 [17:40<06:05, 652.66it/s]

 76%|███████▌  | 761000/998833 [17:42<06:10, 642.06it/s]

 76%|███████▋  | 762000/998833 [17:43<06:09, 640.29it/s]

 76%|███████▋  | 763000/998833 [17:45<05:52, 668.19it/s]

 76%|███████▋  | 764000/998833 [17:46<05:54, 661.73it/s]

 77%|███████▋  | 765000/998833 [17:48<06:01, 646.70it/s]

 77%|███████▋  | 766000/998833 [17:49<06:00, 645.93it/s]

 77%|███████▋  | 767000/998833 [17:51<05:48, 665.97it/s]

 77%|███████▋  | 768000/998833 [17:52<05:41, 675.67it/s]

 77%|███████▋  | 769000/998833 [17:54<05:48, 659.57it/s]

 77%|███████▋  | 770000/998833 [17:55<05:43, 666.05it/s]

 77%|███████▋  | 771000/998833 [17:57<05:47, 656.22it/s]

 77%|███████▋  | 772000/998833 [17:58<05:47, 653.38it/s]

 77%|███████▋  | 773000/998833 [18:00<05:45, 653.65it/s]

 77%|███████▋  | 774000/998833 [18:02<05:52, 637.48it/s]

 78%|███████▊  | 775000/998833 [18:03<05:46, 646.42it/s]

 78%|███████▊  | 776000/998833 [18:05<05:42, 651.05it/s]

 78%|███████▊  | 777000/998833 [18:06<05:40, 651.34it/s]

 78%|███████▊  | 778000/998833 [18:08<05:38, 652.30it/s]

 78%|███████▊  | 779000/998833 [18:09<05:37, 652.03it/s]

 78%|███████▊  | 780000/998833 [18:11<05:28, 665.17it/s]

 78%|███████▊  | 781000/998833 [18:12<05:36, 648.18it/s]

 78%|███████▊  | 782000/998833 [18:14<05:46, 625.83it/s]

 78%|███████▊  | 783000/998833 [18:16<05:42, 630.13it/s]

 78%|███████▊  | 784000/998833 [18:17<05:41, 628.19it/s]

 79%|███████▊  | 785000/998833 [18:19<05:32, 642.89it/s]

 79%|███████▊  | 786000/998833 [18:20<05:35, 634.49it/s]

 79%|███████▉  | 787000/998833 [18:22<05:38, 625.35it/s]

 79%|███████▉  | 788000/998833 [18:23<05:32, 633.58it/s]

 79%|███████▉  | 789000/998833 [18:25<05:29, 637.10it/s]

 79%|███████▉  | 790000/998833 [18:27<05:33, 626.55it/s]

 79%|███████▉  | 791000/998833 [18:28<05:28, 633.49it/s]

 79%|███████▉  | 792000/998833 [18:30<05:19, 648.11it/s]

 79%|███████▉  | 793000/998833 [18:31<05:15, 652.93it/s]

 79%|███████▉  | 794000/998833 [18:33<05:19, 641.81it/s]

 80%|███████▉  | 795000/998833 [18:34<05:16, 643.04it/s]

 80%|███████▉  | 796000/998833 [18:36<05:11, 651.05it/s]

 80%|███████▉  | 797000/998833 [18:37<05:10, 649.29it/s]

 80%|███████▉  | 798000/998833 [18:39<05:10, 646.70it/s]

 80%|███████▉  | 799000/998833 [18:40<05:11, 641.43it/s]

 80%|████████  | 800000/998833 [18:42<05:04, 652.46it/s]

 80%|████████  | 801000/998833 [18:43<05:01, 655.82it/s]

 80%|████████  | 802000/998833 [18:45<05:02, 650.09it/s]

 80%|████████  | 803000/998833 [18:47<05:10, 630.23it/s]

 80%|████████  | 804000/998833 [18:48<05:13, 620.80it/s]

 81%|████████  | 805000/998833 [18:50<05:07, 629.35it/s]

 81%|████████  | 806000/998833 [18:51<05:01, 639.89it/s]

 81%|████████  | 807000/998833 [18:53<04:54, 651.71it/s]

 81%|████████  | 808000/998833 [18:54<04:53, 649.75it/s]

 81%|████████  | 809000/998833 [18:56<04:46, 662.27it/s]

 81%|████████  | 810000/998833 [18:57<04:47, 656.76it/s]

 81%|████████  | 811000/998833 [18:59<04:49, 648.14it/s]

 81%|████████▏ | 812000/998833 [19:01<04:50, 642.43it/s]

 81%|████████▏ | 813000/998833 [19:02<04:48, 645.12it/s]

 81%|████████▏ | 814000/998833 [19:04<04:50, 635.30it/s]

 82%|████████▏ | 815000/998833 [19:05<04:44, 645.60it/s]

 82%|████████▏ | 816000/998833 [19:07<04:41, 648.34it/s]

 82%|████████▏ | 817000/998833 [19:08<04:39, 651.72it/s]

 82%|████████▏ | 818000/998833 [19:10<04:42, 639.84it/s]

 82%|████████▏ | 819000/998833 [19:11<04:39, 643.80it/s]

 82%|████████▏ | 820000/998833 [19:13<04:40, 638.66it/s]

 82%|████████▏ | 821000/998833 [19:15<04:38, 639.66it/s]

 82%|████████▏ | 822000/998833 [19:16<04:34, 645.12it/s]

 82%|████████▏ | 823000/998833 [19:18<04:38, 631.68it/s]

 82%|████████▏ | 824000/998833 [19:19<04:40, 623.26it/s]

 83%|████████▎ | 825000/998833 [19:21<04:39, 623.02it/s]

 83%|████████▎ | 826000/998833 [19:23<04:35, 627.49it/s]

 83%|████████▎ | 827000/998833 [19:24<04:37, 619.42it/s]

 83%|████████▎ | 828000/998833 [19:26<04:31, 628.33it/s]

 83%|████████▎ | 829000/998833 [19:28<04:34, 618.03it/s]

 83%|████████▎ | 830000/998833 [19:29<04:29, 626.78it/s]

 83%|████████▎ | 831000/998833 [19:31<04:27, 627.58it/s]

 83%|████████▎ | 832000/998833 [19:32<04:24, 630.93it/s]

 83%|████████▎ | 833000/998833 [19:34<04:22, 631.75it/s]

 83%|████████▎ | 834000/998833 [19:35<04:20, 632.61it/s]

 84%|████████▎ | 835000/998833 [19:37<04:19, 630.85it/s]

 84%|████████▎ | 836000/998833 [19:39<04:22, 621.17it/s]

 84%|████████▍ | 837000/998833 [19:40<04:17, 628.52it/s]

 84%|████████▍ | 838000/998833 [19:42<04:19, 620.26it/s]

 84%|████████▍ | 839000/998833 [19:43<04:18, 618.75it/s]

 84%|████████▍ | 840000/998833 [19:45<04:09, 635.94it/s]

 84%|████████▍ | 841000/998833 [19:46<04:04, 645.18it/s]

 84%|████████▍ | 842000/998833 [19:48<04:09, 629.81it/s]

 84%|████████▍ | 843000/998833 [19:50<04:08, 628.23it/s]

 84%|████████▍ | 844000/998833 [19:51<04:08, 622.06it/s]

 85%|████████▍ | 845000/998833 [19:53<04:04, 629.21it/s]

 85%|████████▍ | 846000/998833 [19:55<04:03, 627.05it/s]

 85%|████████▍ | 847000/998833 [19:56<03:59, 635.26it/s]

 85%|████████▍ | 848000/998833 [19:58<03:55, 639.20it/s]

 85%|████████▍ | 849000/998833 [19:59<03:53, 641.12it/s]

 85%|████████▌ | 850000/998833 [20:00<03:43, 664.58it/s]

 85%|████████▌ | 851000/998833 [20:02<03:51, 637.47it/s]

 85%|████████▌ | 852000/998833 [20:04<03:56, 621.16it/s]

 85%|████████▌ | 853000/998833 [20:06<03:56, 615.35it/s]

 85%|████████▌ | 854000/998833 [20:07<03:50, 629.16it/s]

 86%|████████▌ | 855000/998833 [20:09<03:47, 633.05it/s]

 86%|████████▌ | 856000/998833 [20:10<03:44, 636.59it/s]

 86%|████████▌ | 857000/998833 [20:12<03:45, 627.69it/s]

 86%|████████▌ | 858000/998833 [20:13<03:41, 636.82it/s]

 86%|████████▌ | 859000/998833 [20:15<03:40, 634.22it/s]

 86%|████████▌ | 860000/998833 [20:17<03:38, 636.56it/s]

 86%|████████▌ | 861000/998833 [20:18<03:33, 644.81it/s]

 86%|████████▋ | 862000/998833 [20:20<03:35, 636.04it/s]

 86%|████████▋ | 863000/998833 [20:21<03:38, 620.37it/s]

 87%|████████▋ | 864000/998833 [20:23<03:42, 605.20it/s]

 87%|████████▋ | 865000/998833 [20:25<03:37, 615.71it/s]

 87%|████████▋ | 866000/998833 [20:26<03:40, 601.50it/s]

 87%|████████▋ | 867000/998833 [20:28<03:42, 593.23it/s]

 87%|████████▋ | 868000/998833 [20:30<03:32, 615.91it/s]

 87%|████████▋ | 869000/998833 [20:31<03:31, 613.09it/s]

 87%|████████▋ | 870000/998833 [20:33<03:33, 604.78it/s]

 87%|████████▋ | 871000/998833 [20:35<03:33, 599.19it/s]

 87%|████████▋ | 872000/998833 [20:36<03:31, 598.53it/s]

 87%|████████▋ | 873000/998833 [20:38<03:27, 606.42it/s]

 88%|████████▊ | 874000/998833 [20:40<03:22, 616.80it/s]

 88%|████████▊ | 875000/998833 [20:41<03:17, 628.42it/s]

 88%|████████▊ | 876000/998833 [20:43<03:17, 621.57it/s]

 88%|████████▊ | 877000/998833 [20:44<03:14, 624.88it/s]

 88%|████████▊ | 878000/998833 [20:46<03:16, 615.07it/s]

 88%|████████▊ | 879000/998833 [20:48<03:13, 618.67it/s]

 88%|████████▊ | 880000/998833 [20:49<03:14, 612.22it/s]

 88%|████████▊ | 881000/998833 [20:51<03:08, 626.72it/s]

 88%|████████▊ | 882000/998833 [20:52<03:08, 620.75it/s]

 88%|████████▊ | 883000/998833 [20:54<03:09, 612.80it/s]

 89%|████████▊ | 884000/998833 [20:56<03:06, 616.58it/s]

 89%|████████▊ | 885000/998833 [20:57<02:58, 637.11it/s]

 89%|████████▊ | 886000/998833 [20:59<02:58, 631.19it/s]

 89%|████████▉ | 887000/998833 [21:00<02:56, 632.52it/s]

 89%|████████▉ | 888000/998833 [21:02<02:55, 632.56it/s]

 89%|████████▉ | 889000/998833 [21:03<02:54, 629.52it/s]

 89%|████████▉ | 890000/998833 [21:05<02:51, 633.16it/s]

 89%|████████▉ | 891000/998833 [21:07<02:51, 627.19it/s]

 89%|████████▉ | 892000/998833 [21:08<02:48, 633.32it/s]

 89%|████████▉ | 893000/998833 [21:10<02:48, 629.52it/s]

 90%|████████▉ | 894000/998833 [21:11<02:43, 642.32it/s]

 90%|████████▉ | 895000/998833 [21:13<02:44, 632.53it/s]

 90%|████████▉ | 896000/998833 [21:14<02:39, 644.77it/s]

 90%|████████▉ | 897000/998833 [21:16<02:35, 656.37it/s]

 90%|████████▉ | 898000/998833 [21:17<02:35, 646.48it/s]

 90%|█████████ | 899000/998833 [21:19<02:36, 639.88it/s]

 90%|█████████ | 900000/998833 [21:21<02:33, 642.07it/s]

 90%|█████████ | 901000/998833 [21:22<02:31, 644.41it/s]

 90%|█████████ | 902000/998833 [21:24<02:31, 639.80it/s]

 90%|█████████ | 903000/998833 [21:25<02:31, 631.89it/s]

 91%|█████████ | 904000/998833 [21:27<02:29, 635.01it/s]

 91%|█████████ | 905000/998833 [21:28<02:26, 641.56it/s]

 91%|█████████ | 906000/998833 [21:30<02:25, 636.38it/s]

 91%|█████████ | 907000/998833 [21:32<02:26, 627.37it/s]

 91%|█████████ | 908000/998833 [21:33<02:25, 623.86it/s]

 91%|█████████ | 909000/998833 [21:35<02:24, 620.50it/s]

 91%|█████████ | 910000/998833 [21:37<02:24, 613.74it/s]

 91%|█████████ | 911000/998833 [21:38<02:22, 614.50it/s]

 91%|█████████▏| 912000/998833 [21:40<02:23, 604.28it/s]

 91%|█████████▏| 913000/998833 [21:42<02:21, 608.13it/s]

 92%|█████████▏| 914000/998833 [21:43<02:20, 605.00it/s]

 92%|█████████▏| 915000/998833 [21:45<02:16, 615.95it/s]

 92%|█████████▏| 916000/998833 [21:46<02:14, 614.74it/s]

 92%|█████████▏| 917000/998833 [21:48<02:13, 614.57it/s]

 92%|█████████▏| 918000/998833 [21:50<02:10, 620.93it/s]

 92%|█████████▏| 919000/998833 [21:51<02:08, 622.68it/s]

 92%|█████████▏| 920000/998833 [21:53<02:04, 634.60it/s]

 92%|█████████▏| 921000/998833 [21:54<02:03, 628.61it/s]

 92%|█████████▏| 922000/998833 [21:56<02:03, 622.99it/s]

 92%|█████████▏| 923000/998833 [21:58<02:00, 627.55it/s]

 93%|█████████▎| 924000/998833 [21:59<01:59, 625.00it/s]

 93%|█████████▎| 925000/998833 [22:01<01:59, 618.77it/s]

 93%|█████████▎| 926000/998833 [22:02<01:55, 627.89it/s]

 93%|█████████▎| 927000/998833 [22:04<01:53, 635.29it/s]

 93%|█████████▎| 928000/998833 [22:05<01:51, 636.45it/s]

 93%|█████████▎| 929000/998833 [22:07<01:49, 635.82it/s]

 93%|█████████▎| 930000/998833 [22:09<01:46, 644.33it/s]

 93%|█████████▎| 931000/998833 [22:10<01:45, 640.77it/s]

 93%|█████████▎| 932000/998833 [22:12<01:43, 643.04it/s]

 93%|█████████▎| 933000/998833 [22:13<01:42, 641.67it/s]

 94%|█████████▎| 934000/998833 [22:15<01:41, 641.22it/s]

 94%|█████████▎| 935000/998833 [22:16<01:39, 641.10it/s]

 94%|█████████▎| 936000/998833 [22:18<01:38, 635.73it/s]

 94%|█████████▍| 937000/998833 [22:20<01:38, 629.75it/s]

 94%|█████████▍| 938000/998833 [22:21<01:36, 628.60it/s]

 94%|█████████▍| 939000/998833 [22:23<01:35, 628.87it/s]

 94%|█████████▍| 940000/998833 [22:25<01:35, 614.45it/s]

 94%|█████████▍| 941000/998833 [22:26<01:32, 624.76it/s]

 94%|█████████▍| 942000/998833 [22:28<01:31, 620.68it/s]

 94%|█████████▍| 943000/998833 [22:29<01:29, 621.99it/s]

 95%|█████████▍| 944000/998833 [22:31<01:28, 619.70it/s]

 95%|█████████▍| 945000/998833 [22:32<01:25, 630.90it/s]

 95%|█████████▍| 946000/998833 [22:34<01:21, 647.52it/s]

 95%|█████████▍| 947000/998833 [22:36<01:22, 631.20it/s]

 95%|█████████▍| 948000/998833 [22:37<01:22, 619.05it/s]

 95%|█████████▌| 949000/998833 [22:39<01:21, 613.51it/s]

 95%|█████████▌| 950000/998833 [22:40<01:17, 627.48it/s]

 95%|█████████▌| 951000/998833 [22:42<01:14, 641.39it/s]

 95%|█████████▌| 952000/998833 [22:44<01:14, 628.92it/s]

 95%|█████████▌| 953000/998833 [22:45<01:13, 627.47it/s]

 96%|█████████▌| 954000/998833 [22:47<01:12, 621.32it/s]

 96%|█████████▌| 955000/998833 [22:48<01:09, 626.60it/s]

 96%|█████████▌| 956000/998833 [22:50<01:07, 630.11it/s]

 96%|█████████▌| 957000/998833 [22:52<01:06, 629.29it/s]

 96%|█████████▌| 958000/998833 [22:53<01:04, 636.20it/s]

 96%|█████████▌| 959000/998833 [22:55<01:04, 620.61it/s]

 96%|█████████▌| 960000/998833 [22:56<01:02, 620.93it/s]

 96%|█████████▌| 961000/998833 [22:58<01:00, 628.95it/s]

 96%|█████████▋| 962000/998833 [22:59<00:57, 640.06it/s]

 96%|█████████▋| 963000/998833 [23:01<00:56, 639.24it/s]

 97%|█████████▋| 964000/998833 [23:03<00:54, 638.83it/s]

 97%|█████████▋| 965000/998833 [23:04<00:53, 627.65it/s]

 97%|█████████▋| 966000/998833 [23:06<00:51, 642.24it/s]

 97%|█████████▋| 967000/998833 [23:07<00:49, 646.19it/s]

 97%|█████████▋| 968000/998833 [23:09<00:48, 634.92it/s]

 97%|█████████▋| 969000/998833 [23:10<00:47, 632.91it/s]

 97%|█████████▋| 970000/998833 [23:12<00:45, 631.89it/s]

 97%|█████████▋| 971000/998833 [23:14<00:44, 625.00it/s]

 97%|█████████▋| 972000/998833 [23:15<00:41, 640.98it/s]

 97%|█████████▋| 973000/998833 [23:17<00:40, 637.02it/s]

 98%|█████████▊| 974000/998833 [23:18<00:38, 641.79it/s]

 98%|█████████▊| 975000/998833 [23:20<00:37, 631.58it/s]

 98%|█████████▊| 976000/998833 [23:21<00:35, 648.66it/s]

 98%|█████████▊| 977000/998833 [23:23<00:34, 628.64it/s]

 98%|█████████▊| 978000/998833 [23:25<00:33, 624.13it/s]

 98%|█████████▊| 979000/998833 [23:26<00:31, 621.89it/s]

 98%|█████████▊| 980000/998833 [23:28<00:30, 617.22it/s]

 98%|█████████▊| 981000/998833 [23:30<00:28, 620.37it/s]

 98%|█████████▊| 982000/998833 [23:31<00:26, 637.05it/s]

 98%|█████████▊| 983000/998833 [23:33<00:25, 629.65it/s]

 99%|█████████▊| 984000/998833 [23:34<00:23, 634.60it/s]

 99%|█████████▊| 985000/998833 [23:36<00:21, 648.01it/s]

 99%|█████████▊| 986000/998833 [23:37<00:20, 628.57it/s]

 99%|█████████▉| 987000/998833 [23:39<00:18, 637.69it/s]

 99%|█████████▉| 988000/998833 [23:40<00:16, 640.10it/s]

 99%|█████████▉| 989000/998833 [23:42<00:15, 645.86it/s]

 99%|█████████▉| 990000/998833 [23:43<00:13, 655.96it/s]

 99%|█████████▉| 991000/998833 [23:45<00:11, 661.77it/s]

 99%|█████████▉| 992000/998833 [23:47<00:10, 633.69it/s]

 99%|█████████▉| 993000/998833 [23:48<00:09, 627.08it/s]

100%|█████████▉| 994000/998833 [23:50<00:07, 643.40it/s]

100%|█████████▉| 995000/998833 [23:51<00:05, 648.46it/s]

100%|█████████▉| 996000/998833 [23:53<00:04, 657.68it/s]

100%|█████████▉| 997000/998833 [23:54<00:02, 655.11it/s]

100%|█████████▉| 998000/998833 [23:56<00:01, 647.11it/s]

100%|██████████| 998833/998833 [23:57<00:00, 639.67it/s]

100%|██████████| 998833/998833 [23:57<00:00, 694.76it/s]

0.11717241827367085