# MySpotify — complete recommendation pipeline

Merged version of notebooks 01 (Top-250), 02 (Top-100 by genre), 03 (Collections)
and 04 (Collaborative filtering).

All tables are parsed **in place from the uncleaned raw files** (`data/raw`)
with pandas — no cleaning, no intermediate files are written or read. The heavy triplets table (~48.4 M rows) and the tidy
lyrics table (~210 k tracks) are ordinary DataFrames, so every task is plain
pandas + scikit-learn + implicit.

In [1]:
import gc
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from implicit.evaluation import train_test_split as implicit_split

from src.data.loader import MySpotifyRecommender
from src.models.collaborative_filtering import (
    build_user_item_matrix,
    evaluate_user_cf,
    fit_als,
    recommend_tracks_df,
    recommend_users_df,
)
from src.models.collections import (
    collection_baseline,
    collection_classification_compare,
    collection_word2vec,
)
from src.models.top_n import top_n_songs
from src.models.top_n_genre import top_n_per_genre


def rss_mb():
    try:
        with open("/proc/self/status") as fh:
            for line in fh:
                if line.startswith("VmRSS"):
                    return int(line.split()[1]) // 1024
    except OSError:
        pass
    return 0


rs = MySpotifyRecommender.from_files(Path.cwd().parent / "data")
print(f"peak RSS : {rss_mb()} MB (all tables loaded in memory)")

/home/samy/MySpotify/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/samy/MySpotify/.venv/lib/python3.12/site-packages/implicit/gpu/__init__.py:28: UserWarning: Disabling GPU support because of 'libcublas.so.13: cannot open shared object file: No such file or directory'
  warnings.warn(

Data dir    : /home/samy/MySpotify/data
Source      : uncleaned raw files (parsed in place)

  tracks      (1000000, 4)
  genres      (280831, 3)
  triplets    (48373586, 3)
  lyrics_long (16845822, 3)
peak RSS : 5146 MB (all tables loaded in memory)

---
## 1. Top-250 most-played songs

Total play count per song is aggregated from the full triplets table with a
pandas ``groupby``; the 250 most-played songs are then joined to the tracks.

In [2]:
a = top_n_songs(rs, n=250, user_id=None)
print("head(5):")
display(a[["artist", "title", "play_count"]].head(5))
print("\ntail(5):")
display(a[["artist", "title", "play_count"]].tail(5))
print(f"peak RSS : {rss_mb()} MB")

head(5):

,artist,title,play_count
0,Dwight Yoakam,You're The One,726885
1,Björk,Undo,648239
2,Kings Of Leon,Revelry,527893
3,Harmonia,Sehr kosmisch,425463
4,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...,389880

tail(5):

                           artist                        title  play_count
245              Triple Six Mafia    Now I'm High_ Really High       35253
246    The Red Jumpsuit Apparatus    Face Down (Album Version)       35245
247                   Linkin Park   New Divide (Album Version)       35191
248      Selena Gomez & The Scene                    Naturally       35074
249  Creedence Clearwater Revival  Have You Ever Seen The Rain       34831

peak RSS : 5310 MB

In [3]:
# the same query for a single user (read from one row of the sparse matrix)
user_id = rs.triplets["user_id"].unique()[0]
print(f"sample user : {user_id}")

a = top_n_songs(rs, n=250, user_id=user_id)
display(a[["artist", "title", "play_count"]].head(10))

sample user : b80344d063b5ccb3212f76538f3d9e43d87dca9e

,artist,title,play_count
0,Jack Johnson,Moonshine,8
1,Panic At The Disco,Behind The Sea [Live In Chicago],6
2,Bobby Freeman,Do You Wanna Dance,6
3,Héroes del Silencio,Apuesta Por El Rock 'N' Roll,5
4,Puff Daddy,I'll Be Missing You (Featuring Faith Evans & 1...,5
5,Robert Johnson,I?'m A Steady Rollin? Man,5
6,Bob Rivers,No So Silent Night (album version),5
7,Paco De Lucia,Entre Dos Aguas,2
8,Jorge Drexler,12 segundos de oscuridad,2
9,Chris Bell,Speed Of Sound,2

---
## 2. Top-100 most-played songs by genre

Genres use the `majority_genre` tag. Tracks are deduplicated by `song_id`
(keeping the first row) *before* the genre join, matching the reference output.

In [4]:
genres = rs.genres["majority_genre"].unique()
print(f"Available genres ({len(genres)}): {sorted(genres)}")

Available genres (15): ['Blues', 'Country', 'Electronic', 'Folk', 'Jazz', 'Latin', 'Metal', 'New Age', 'Pop', 'Punk', 'Rap', 'Reggae', 'RnB', 'Rock', 'World']

In [5]:
top100_rock = top_n_per_genre(rs, "Rock", n=100)
print("Rock head(5):")
display(top100_rock[["artist", "title", "play_count"]].head(5))
print("\nRock tail(5):")
display(top100_rock[["artist", "title", "play_count"]].tail(5))

Rock head(5):

          artist          title  play_count
0          Björk           Undo    648239.0
1  Kings Of Leon        Revelry    527893.0
2       Harmonia  Sehr kosmisch    425463.0
3    OneRepublic        Secrets    292642.0
4       Tub Ring        Invalid    268353.0

Rock tail(5):

          artist              title  play_count
95        Metric    Gold Guns Girls     28148.0
96     Pearl Jam       Encore Break     27579.0
97      Daughtry        No Surprise     27187.0
98  Eric Clapton    Tears In Heaven     26999.0
99     Nick Lowe  All Men Are Liars     26683.0

In [6]:
top100_rap = top_n_per_genre(rs, "Rap", n=100)
print("Rap head(5):")
display(top100_rap[["artist", "title", "play_count"]].head(5))
print("\nRap tail(5):")
display(top100_rap[["artist", "title", "play_count"]].tail(5))

Rap head(5):

            artist         title  play_count
0  Alliance Ethnik    Représente    241669.0
1     Beastie Boys   The Maestro     72381.0
2           Eminem    Without Me     63918.0
3  Black Eyed Peas       Imma Be     62438.0
4         Kid Cudi  Up Up & Away     59810.0

Rap tail(5):

                  artist            title  play_count
95               Shwayze          Buzzin'      7384.0
96               Orishas          El Kilo      7324.0
97            Snoop Dogg  Sexual Eruption      7171.0
98  Bone Thugs-N-Harmony   Tha Crossroads      7124.0
99               Orishas           Habana      6998.0

In [7]:
top100_elec = top_n_per_genre(rs, "Electronic", n=100)
print("Electronic head(5):")
display(top100_elec[["artist", "title", "play_count"]].head(5))
print("\nElectronic tail(5):")
display(top100_elec[["artist", "title", "play_count"]].tail(5))

Electronic head(5):

,artist,title,play_count
0,Southside Spinners,Luvstruck,84225.0
1,The Black Keys,Tighten Up,81179.0
2,Deadmau5,Ghosts 'n' Stuff (Original Instrumental Mix),63951.0
3,Daft Punk,Harder Better Faster Stronger,63170.0
4,Clara Hill,Clara meets Slope - Hard To Say,58887.0

Electronic tail(5):

,artist,title,play_count
95,Nicolette,No Government,9541.0
96,Two Door Cinema Club,Eat That Up_ It's Good For You,9524.0
97,Moby,Why Does My Heart Feel So Bad? (2006 Digital R...,9491.0
98,Death In Vegas,Girls,9490.0
99,Johan Gielen,Flash,9431.0

In [8]:
# a single user's favourite Rock songs
user_1 = rs.triplets["user_id"].unique()[0]
print(f"User 1 : {user_1}")

top100_rock_user_1 = top_n_per_genre(rs, "Rock", n=100, user_id=user_1)
display(top100_rock_user_1[["artist", "title", "play_count"]].head(10))

User 1 : b80344d063b5ccb3212f76538f3d9e43d87dca9e

                artist                         title  play_count
0  Héroes del Silencio  Apuesta Por El Rock 'N' Roll         5.0
1           Chris Bell                Speed Of Sound         2.0
2           John Mayer          Love Song For No One         1.0
3           Josh Rouse                Nice To Fit In         1.0
4           Josh Rouse           Domesticated Lovers         1.0
5          Andrew Bird                         Oh No         1.0
6          Takka Takka                         Fever         1.0
7              Incubus                         Drive         1.0
8           Josh Rouse           It's The Night Time         1.0
9      Jimmy Eat World                    The Middle         1.0

---
## 3. Collections — 50 songs about a keyword

Lyrics are loaded as a tidy `(track_id, word, count)` table (~210 k tracks ×
5000 vocabulary words). The musiXmatch vocabulary is Porter-stemmed, so
`happiness` → `happi`, `loneliness` → `loneli`. Three approaches are compared:
baseline keyword counts, word2vec-expanded keywords, and ML classification.

In [9]:
KEYWORDS = ["love", "war", "happiness", "loneliness", "money"]

In [10]:
baseline_results = collection_baseline(rs, KEYWORDS, n=1, top_n=50)
for kw in KEYWORDS:
    print(f"\nKeyword: {kw}")
    display(baseline_results.get(kw, "No results found"))
print(f"peak RSS : {rss_mb()} MB")

Keyword: love

,artist,title,play_count
1,OneRepublic,Secrets,292642.0
2,Five Iron Frenzy,Canada,274627.0
3,Tub Ring,Invalid,268353.0
4,Train,Hey_ Soul Sister,209212.0
5,Angels and Airwaves,The Gift,192884.0
6,Train,Marry Me,174080.0
7,Lil Wayne / Eminem,Drop The World,155717.0
8,Bill Withers,Make Love To Your Mind,146978.0
9,Pavement,Mercy:The Laundromat,130116.0
10,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,122318.0
11,Sheena Easton,Strut (1993 Digital Remaster),115134.0
12,Coldplay,Clocks,114362.0
13,La Roux,Bulletproof,110240.0
14,Beastie Boys,Unite (2009 Digital Remaster),99137.0
15,Radiohead,Creep (Explicit),98854.0
16,Metallica,Master Of Puppets,98667.0
17,Mike And The Mechanics,A Beggar On A Beach Of Gold,97488.0
18,Florence + The Machine,Cosmic Love,94002.0
19,Beyoncé,Halo,91461.0
20,Evanescence,Bring Me To Life,91448.0
21,Panic At The Disco,Behind The Sea [Live In Chicago],89974.0
22,Taylor Swift,Love Story,89589.0
23,OneRepublic,All The Right Moves,81736.0
24,The Black Keys,Tighten Up,81179.0
25,The Verve,Bitter Sweet Symphony,76893.0
26,Rise Against,Savior,74654.0
27,Eminem,Mockingbird,74103.0
28,Jason Derulo,Whatcha Say,69053.0
29,Shania Twain,Nah!,68150.0
30,Sean Kingston and Justin Bieber,Eenie Meenie,66998.0
31,John Mayer,Half Of My Heart,65966.0
32,Eagles,Hotel California,65585.0
33,Taylor Swift,You Belong With Me,65582.0
34,Thursday,Voices On A String (Album Version),64374.0
35,Owl City,Vanilla Twilight,63937.0
36,Eminem,Without Me,63918.0
37,Guns N' Roses,Paradise City,60787.0
38,The Postal Service,Such Great Heights,58059.0
39,N.E.R.D.,Rock Star,52834.0
40,Postal Service,Nothing Better (Album),51280.0
41,M.I.A.,Paper Planes,50763.0
42,Two Door Cinema Club,What You Know,49030.0
43,Reality Check,Masquerade (Reality Check Album Version),48393.0
44,Linkin Park,What I've Done (Album Version),45817.0
45,Eminem / Dina Rae,Superman,45328.0
46,Eminem / Nate Dogg,'Till I Collapse,44305.0
47,Sheryl Crow,Picture,42563.0
48,Five Finger Death Punch,Bad Company,42348.0
49,Lynyrd Skynyrd,Sweet home Alabama,42059.0
50,Coldplay,Speed Of Sound,41493.0

Keyword: war

,artist,title,play_count
1,Taylor Swift,Love Story,89589.0
2,Miley Cyrus,Party In The U.S.A.,78443.0
3,Taylor Swift,You Belong With Me,65582.0
4,Five Finger Death Punch,Bad Company,42348.0
5,Black Eyed Peas,Pump It,41243.0
6,Jack Johnson,Breakdown,32684.0
7,Eddy Grant,Electric Avenue,29781.0
8,Alicia Keys,Empire State Of Mind (Part II) Broken Down,25203.0
9,Beirut,Elephant Gun,25133.0
10,John Mayer,Perfectly Lonely,24737.0
11,Kanye West,Homecoming,23119.0
12,Taylor Swift,I'm Only Me When I'm With You,22962.0
13,Vanilla Ice,Ice Ice Baby (Radio Edit),22909.0
14,Carpenters,(They Long To Be) Close To You,22811.0
15,Lily Allen,LDN,22046.0
16,Black Eyed Peas,Hey Mama,20040.0
17,A Day To Remember,The Downfall Of Us All,19913.0
18,Sean Paul,Baby Boy [feat. Beyonce],19892.0
19,Yellowcard,Ocean Avenue,18817.0
20,Jason Aldean,Big Green Tractor,18515.0
21,Lipps Inc.,Funkytown,18460.0
22,ENUR Feat NATASJA,Calabria 2007,18045.0
23,Billy Idol,Yellin' At The Xmas Tree,17279.0
24,MxPx,Invitation To Understanding,16773.0
25,Modest Mouse,The World At Large,16256.0
26,Luke Bryan,Someone Else Calling You Baby,15670.0
27,Tom Petty And The Heartbreakers,Learning To Fly,15503.0
28,Gorillaz,Feel Good Inc (Album Version),15443.0
29,Luke Bryan,Rain Is A Good Thing,14378.0
30,Margot & The Nuclear So And So's,Dress Me Like a Clown,14311.0
31,Delirious?,Paint The Town Red,13392.0
32,Edwyn Collins,A Girl Like You,12687.0
33,Justin Timberlake,LoveStoned/I Think She Knows,12516.0
34,Red Hot Chili Peppers,Road Trippin' (Album Version),12325.0
35,Arcade Fire,Neighborhood #1 (Tunnels),12232.0
36,Belle & Sebastian,We Are The Sleepyheads,12016.0
37,Rise Against,Paper Wings,11925.0
38,Postal Service,Brand New Colony (Album),11745.0
39,Aerosmith,Sweet Emotion,11646.0
40,Red Hot Chili Peppers,Tell Me Baby (Album Version),11611.0
41,Marilyn Manson,This Is Halloween,11202.0
42,Eric Clapton,Willie And The Hand Jive,10643.0
43,Anberlin,The Feel Good Drag,10429.0
44,All Time Low,Jasey Rae,10424.0
45,Foreigner,Juke Box Hero (Remastered LP Version ),9874.0
46,We The Kings,Skyway Avenue,9818.0
47,Taylor Swift,The Best Day,9631.0
48,Fleet Foxes,Tiger Mountain Peasant Song,9146.0
49,Regina Spektor,Lady (Album Version),9118.0
50,Empire Of The Sun,Half Mast,8911.0

Keyword: happiness

,artist,title,play_count
1,Train,Hey_ Soul Sister,209212.0
2,Train,Marry Me,174080.0
3,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,122318.0
4,Beyoncé,Halo,91461.0
5,Eminem,Mockingbird,74103.0
6,The White Stripes,Seven Nation Army (Album Version),70470.0
7,Shania Twain,Nah!,68150.0
8,Eagles,Hotel California,65585.0
9,Owl City,Vanilla Twilight,63937.0
10,Another Sunny Day,Rio,49126.0
11,New Radicals,You Get What You Give,35408.0
12,O.G.C.,Gunn Clapp,33897.0
13,UB40,Red Red Wine (Edit),23263.0
14,The Ordinary Boys,Boys Will Be Boys,21005.0
15,Ten Years After,As The Sun Still Burns Away (2002 Digital Rema...,20162.0
16,Madonna,Beautiful Stranger,20077.0
17,A Day To Remember,The Downfall Of Us All,19913.0
18,Lady GaGa,Boys Boys Boys,16925.0
19,Guns N' Roses,You Could Be Mine,16578.0
20,New Order,Let's Go [from 'Salvation'],16429.0
21,ARRESTED DEVELOPMENT,Fountain Of Youth,15247.0
22,Ryan Leslie,Nothing,14157.0
23,Coldplay,Politik,14000.0
24,Michael Bublé,Save The Last Dance For Me [Ralphi Rosario Ant...,12387.0
25,Arcade Fire,Neighborhood #1 (Tunnels),12232.0
26,Man Man,Van Helsing Boombox,12196.0
27,Muse,Plug In Baby,12181.0
28,Coldplay,Spies,11982.0
29,Lit,My Own Worst Enemy,11776.0
30,The Streets,The Irony Of It All (Album Version),11497.0
31,Vampire Weekend,Giving Up The Gun,11238.0
32,U2,Love Comes Tumbling,11158.0
33,Taylor Swift,Forever & Always,11053.0
34,Harvey Danger,Flagpole Sitta,11001.0
35,Savatage,Drive,10800.0
36,P.O.D.,Thinking About Forever (Album Version),10689.0
37,Despised Icon,In The Arms Of Perdition,10624.0
38,Gang Starr,Soliloquy Of Chaos (Explicit),10590.0
39,Erin McKeown,Fast As I Can,10578.0
40,All Time Low,Jasey Rae,10424.0
41,Vampire Weekend,I Stand Corrected (Album),10406.0
42,Divinyls,I Touch Myself,10131.0
43,The Kills,Goodnight Bad Morning,10063.0
44,Daft Punk,Face To Face,10003.0
45,Coldplay,Swallowed In The Sea,9938.0
46,Fort Minor (Featuring Styles Of Beyond),Remember The Name (Album Version),9750.0
47,Simple Minds,Oh Jungleland,9677.0
48,Joshua Radin_ Schuyler Fisk,Paperweight,9667.0
49,Slipknot,Before I Forget (Album Version),9649.0
50,Beyoncé,Kitty Kat,9583.0

Keyword: loneliness

,artist,title,play_count
1,O.G.C.,Gunn Clapp,33897.0
2,Toby Keith,American Soldier,23872.0
3,Rise Against,Hero Of War,18939.0
4,Vampire Weekend,Horchata,16823.0
5,The Kooks,She Moves In Her Own Way,14561.0
6,Dierks Bentley,Sideways,13892.0
7,Eric Church,Love Your Love The Most,10738.0
8,Iron And Wine,The Devil Never Sleeps (Album),10596.0
9,Eric Church,Guys Like Me,8627.0
10,311,Get Down,8258.0
11,The Notorious B.I.G.,One More Chance (Album Version),8123.0
12,The Notorious B.I.G.,Gimme The Loot (Album Version),7874.0
13,The Lonely Island,Punch You In The Jeans,7609.0
14,Lupe Fiasco feat. Biship G and Nikki Jean,Little Weapon (feat. Bishop G and Nikki Jean) ...,6928.0
15,Toby Keith,Courtesy Of The Red_ White And Blue (The Angry...,6859.0
16,Flogging Molly,Salty Dog,6387.0
17,Rich Boy / Andre 3000 / Jim Jones / Nelly / Mu...,Throw Some D's Remix,5568.0
18,Beastie Boys,Get It Together,5435.0
19,DMX,Where The Hood At,5408.0
20,Fall Out Boy,Calm Before The Storm (Album Version),4897.0
21,Beck,E-Pro,4889.0
22,The Tallest Man On Earth,King of Spain,4858.0
23,Wu-Tang Clan featuring Redman,Redbull (featuring Redman),4832.0
24,Iron And Wine,Pagan Angel and a Borrowed Car (Album),4745.0
25,Aesop Rock,Daylight,4624.0
26,Eric Church,These Boots,4589.0
27,Heltah Skeltah,Soldiers Gone Psyco (Explicit),4486.0
28,Nick Drake,One Of These Things First,4478.0
29,Unk,Walk It Out,4475.0
30,Nancy Sinatra,These Boots are Made For Walkin' (2006 Digital...,4254.0
31,MGMT,The Handshake,3951.0
32,Dierks Bentley,Lot Of Leavin' Left To Do,3903.0
33,Big Punisher featuring Joe,Still Not A Player,3897.0
34,NOFX,Bob,3853.0
35,Jay-Z,So Ambitious [Jay-Z + Pharrell] (Explicit Albu...,3843.0
36,Dropkick Murphys,Walk Away (Album Version),3596.0
37,Eric Church,How 'Bout You,3548.0
38,Masta Killa,Brooklyn King,3520.0
39,Cat Stevens,Portobello Road,3478.0
40,The Decemberists,July_ July!,3475.0
41,Ice Cube,When Will They Shoot? (Edited),3435.0
42,Randy Houser,Boots On,3375.0
43,504 Boyz,Wobble Wobble,3215.0
44,Dave Navarro,Venus In Furs,3030.0
45,The Gaslight Anthem,High Lonesome,2993.0
46,U2,Get On Your Boots,2951.0
47,Beyoncé feat. Jay-Z,That's How You Like It,2948.0
48,The Airborne Toxic Event,This Is Nowhere,2775.0
49,Santigold,Unstoppable,2769.0
50,OutKast,Player's Ball,2751.0

Keyword: money

,artist,title,play_count
1,Paris Combo,Prête A Porter,17179.0
2,Yann Tiersen,A Quai,12471.0
3,Calle 13 Featuring Café Tacuba,No Hay Nadie Como Tú,9591.0
4,Sondre Lerche,Hoisting The Flag,9024.0
5,Mylène Farmer,Porno Graphique,7840.0
6,La Rue Ketanou,Les derniers aventuriers,7575.0
7,Clarika,Les Garçons Dans Les Vestiaires,7407.0
8,Kate Ryan,Désenchantée,6071.0
9,Macaco,Mama Tierra,5591.0
10,Metric,Poster Of A Girl,5300.0
11,Hem,Half Acre,5149.0
12,Jamie T,Sheila (Explicit),4684.0
13,El Cuarteto De Nos,Ya No Se Que Hacer Conmigo,4497.0
14,Plastic Bertrand,Ca plane pour moi,4485.0
15,Carla Bruni,Raphael,4324.0
16,Kate Bush,Joanni,4209.0
17,Regina Spektor,Consequence Of Sounds,4089.0
18,David Cook,Come Back to Me,4081.0
19,Rob De Nijs,Ze Rook Naar Rozen,3753.0
20,Josh Groban,Hymne A L'Amour (Album Version),3521.0
21,Thievery Corporation,Shadows Of Ourselves,3373.0
22,MGMT,Song For Dan Treacy,3332.0
23,Le Rat Luciano;Sat;Rohff,Nous Contre Eux,2946.0
24,Thievery Corporation,Le Monde,2884.0
25,Alizée,J'En Ai Marre,2877.0
26,Carla Bruni,L'Excessive,2803.0
27,Jane Birkin,Baby Alone In Babylone (Live),2740.0
28,Bebe,Siete Horas,2682.0
29,Feist,Tout doucement,2591.0
30,Grace Jones,I've Seen That Face Before (Libertango),2510.0
31,Belanova,Niño,2504.0
32,Daddy Yankee,Todos Quieren A Raymond,2402.0
33,Raymond Van Het Groenewoud,Winterochtend (1991 Digital Remaster),2398.0
34,The Streets,Could Well Be In,2309.0
35,Fernando Delgadillo,Entre Pairos y Derivas (en vivo),2301.0
36,Pearl Jam,Not For You,2250.0
37,Brigitte Bardot / Serge Gainsbourg,Bonnie And Clyde,2230.0
38,Lara Fabian,Je Suis Malade,2222.0
39,Rufus Wainwright,Complainte De La Butte,2145.0
40,Daddy Yankee,El Muro,2038.0
41,Yelle,Mal Poli,1928.0
42,Mago de Oz,La posada de los muertos,1921.0
43,Basement Jaxx,La Photo,1885.0
44,Les Trois Accords,Dans mon corps,1860.0
45,Faudel,Mon Pays,1854.0
46,Saian Supa Crew,Angela,1845.0
47,Renan Luce,La Lettre,1839.0
48,Molotov,Cerdo,1820.0
49,Dub Incorporation,Même Dub,1801.0
50,Naast,Coeur De Glace,1787.0

peak RSS : 5202 MB

In [11]:
w2v_results = collection_word2vec(rs, KEYWORDS, n=50, top_n=50)
for kw, df in w2v_results.items():
    print(f"\n{'='*50}\n  Collection: {kw.upper()}\n{'='*50}")
    display(df)

==================================================
  Collection: LOVE
==================================================

,artist,title,play_count
1,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,122318.0
2,Beastie Boys,Unite (2009 Digital Remaster),99137.0
3,Miley Cyrus,Party In The U.S.A.,78443.0
4,Eminem,Mockingbird,74103.0
5,Eminem,Without Me,63918.0
6,Guns N' Roses,Paradise City,60787.0
7,Reality Check,Masquerade (Reality Check Album Version),48393.0
8,Eminem / Nate Dogg,'Till I Collapse,44305.0
9,Guns N' Roses,Don't Cry (Original),40480.0
10,Gang Starr/Inspectah Deck,Above The Clouds (Edited),39140.0
11,Daft Punk,Around The World (Radio Edit),35885.0
12,Chiddy Bang,Opposite Of Adults,34504.0
13,The Lonely Island,Like A Boss,26205.0
14,Michael Jackson,Thriller,26038.0
15,Vanessa Williams,Colors Of The Wind,26001.0
16,Eminem / Dr. Dre / 50 Cent,Crack A Bottle,24856.0
17,Dr. Dre / Eminem,Forgot About Dre,24502.0
18,Vanilla Ice,Ice Ice Baby (Radio Edit),22909.0
19,Blink-182,Feeling This,22371.0
20,Leona Lewis,Bleeding Love,22195.0
21,Modern Lovers,Modern world,20584.0
22,The B-52's,Love Shack,20226.0
23,Zac Brown Band,Chicken Fried (Album),20088.0
24,Black Eyed Peas,Hey Mama,20040.0
25,Fall Out Boy,Sugar_ We're Goin Down,20035.0
26,Aesop Rock,None Shall Pass (Main),19168.0
27,ENUR Feat NATASJA,Calabria 2007,18045.0
28,Jason Mraz,The Remedy (I Won't Worry) (New EQ'd LP Version),17780.0
29,Shaggy,Boombastic,17115.0
30,Hollywood Undead,Young,16920.0
31,New Order,Let's Go [from 'Salvation'],16429.0
32,Outkast Featuring Killer Mike,The Whole World,16240.0
33,Tinie Tempah,Pass Out (Instrumental),15560.0
34,Dragonforce,Through The Fire And Flames (Album Version),15152.0
35,The Lonely Island / Julian Casablancas,Boombox,14839.0
36,Eddie Vedder,Hard Sun,14804.0
37,Blur,Country House,13603.0
38,Binary Star,Solar Powered,13304.0
39,50 Cent,P.I.M.P.,13190.0
40,Yeah Yeah Yeahs,Gold Lion,12395.0
41,OutKast,The Way You Move,11923.0
42,The Lonely Island / Justin Timberlake,Dick In A Box,11589.0
43,The Streets,The Irony Of It All (Album Version),11497.0
44,Carnal Forge,Sacred Flame,11271.0
45,Twista,Sunshine (Feat. Anthony Hamilton) (Edited Albu...,10992.0
46,K'Naan,Take A Minute,10813.0
47,Natasha Bedingfield,Unwritten,10590.0
48,Gang Starr,Soliloquy Of Chaos (Explicit),10590.0
49,Florence + The Machine,Bird Song,10576.0
50,Blue October,Into The Ocean,10536.0

==================================================
  Collection: WAR
==================================================

Empty DataFrame
Columns: [artist, title, play_count]
Index: []

==================================================
  Collection: HAPPINESS
==================================================

,artist,title,play_count
1,Spice Girls,Something Kinda Funny,801.0
2,New Radicals,Maybe You've Been Brainwashed Too,495.0
3,The Roots,The Session (Longest Posse Cut In History_ 12:43),298.0
4,Obie Trice,Never Forget Ya,101.0
5,Lil' Romeo,The Girlies,13.0
6,Heather Small,I've Been There,12.0
7,Jessica Simpson,My Wonderful,8.0
8,Missing Persons,Give (Dance Mix) (2002 Digital Remaster),3.0
9,Jessica Simpson,I've Got My Eyes On You,0.0
10,Red Hot Chili Peppers,Around The World (Album Version),0.0
11,Jessica Simpson,I Think I'm In Love With You,0.0
12,John Martyn,Could've Been Me,0.0
13,The Misfits,Night Of The Living Dead,0.0
14,Studio 99,What Have I Done To Deserve This,0.0

==================================================
  Collection: LONELINESS
==================================================

,artist,title,play_count
1,Silkk The Shocker,D-Game (feat. Master P_ Krazy and Terror) (Remix),0.0

==================================================
  Collection: MONEY
==================================================

,artist,title,play_count
1,The Hollies,I'm Down,3973.0
2,Bruce Springsteen,I'm Goin' Down,2371.0
3,Andres Calamaro,No Se Puede Vivir Del Amor,1322.0
4,Will.I.Am,Over,1260.0
5,Red Hot Chili Peppers,I Like Dirt (Album Version),686.0
6,Spice Girls,Saturday Night Divas,478.0
7,Jamie Foxx featuring Gucci Mane,Speak French,349.0
8,Simply Red,Model,288.0
9,Fatboy Slim,The World Went Down,49.0
10,G-Unit,Get Down,36.0
11,LL Cool J,Buckin' Em Down,23.0
12,Unladylike,Sit Down,16.0
13,UGK (Underground Kingz),She Luv It,11.0
14,LL Cool J,Diggy Down,11.0
15,The Cult,The Snake,8.0
16,Joan Armatrading,Deep Down,4.0
17,Chris Brown,Fallin Down,3.0
18,The Benjamin Gate,Lay It Down (Untitled Album Version),0.0
19,Jordanaires,Sit Down,0.0
20,Big Moe,Freestyle (screwed),0.0
21,Cupid,Cupid Shuffle [DFA Dub],0.0
22,Kool & The Gang,Jungle Boogie,0.0
23,Mad Skillz,It's Goin' Down [Explicit],0.0
24,Curiosity Killed The Cat,Down To Earth,0.0
25,America,Down To The Water (Album Version),0.0
26,Diomay,Bel Air,0.0
27,Chumbawamba,Tubthumping,0.0
28,Status Quo,Down Down,0.0
29,Mississippi Fred McDowell,Shake 'Em On Down,0.0
30,Jennifer Warnes,Way Down Deep,0.0
31,Sugababes,Down Down,0.0
32,Kool & The Gang,Get Down On It,0.0
33,Lionel Richie,Se La,0.0

In [12]:
classifiers = ["nb", "logistic", "sgd", "forest"]
clf_results = collection_classification_compare(rs, KEYWORDS, n=10, neg_ratio=1, classifiers=classifiers)
for name in classifiers:
    print(f"\n{'='*60}\nClassifier: {name.upper()}\n{'='*60}")
    for kw, df in clf_results[name].items():
        print(f"\n  Collection: {kw.upper()}")
        display(df)
print(f"peak RSS : {rss_mb()} MB")

============================================================
Classifier: NB
============================================================

  Collection: LOVE

,artist,title,play_count
1,Blessid Union Of Souls,Could've Been With You,57.0
2,Maxwell,Arroz Con Pollo,0.0
3,Maxwell,Eachhoureachsecondeachminuteeachday:Of My Life,0.0
4,Joe Clay,Annabella,0.0
5,Maxwell,This Woman's Work,3601.0
6,Whitesnake,Mistreated (Live) (2007 Digital Remaster),383.0
7,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,4.0
8,Glenn Hughes,Mistreated,0.0
9,Hughes Turner Project,Mistreated,0.0
10,Songs:Ohia,Ghost Tropic,94.0
11,Lush,Ciao !,264.0
12,Leon Jackson,Caledonia,0.0
13,Chris De Burgh,Missing You,1551.0
14,Uriah Heep,Been Away Too Long,18.0
15,Keith Sweat,What Goes Around (LP Version),35.0
16,Miss Li,Take a Shower!,68.0
17,Alexandra Burke,Overcome,0.0
18,Solitude Aeturnus,Believe,3.0
19,Ginuwine,Bedda To Have Loved,0.0
20,The Germs,Throw It Away,0.0
21,Martha Reeves,I've Got To Use My Imagination,0.0
22,Beth Orton,Live As You Dream,0.0
23,MU330,Oh My God,5.0
24,Ambrosia,How Can You Love Me (Remastered Version),3.0
25,All Saints,Never Ever,3438.0
26,Thaddeus Hogarth,It Might As Well Be Now,0.0
27,Babe Ruth,Private Number (2007 Digital Remaster),1.0
28,Jennifer Lopez,Should've Never,741.0
29,Kingdom Come,Should Have Told You,21.0
30,88 Fingers Louie,Try It Again,271.0
31,Dwele,Find A Way,0.0
32,Sara Melson,Never Been Hurt,15.0
33,Kid Dynamite,Table 19,34.0
34,Blessid Union Of Souls,Lucky To Be Here,5.0
35,W.A.S.P.,Easy Living,49.0
36,Kenny Rogers,Through The Years,0.0
37,Edyta Gorniak,Anything,19.0
38,Marty Robbins,Like All The Other Times,0.0
39,Average White Band,Got The Love,167.0
40,On Thorns I Lay,Unsung Songs,0.0
41,Conway Twitty,Let Me Be The Judge,0.0
42,Brian McKnight,Try Our Love Again,77.0
43,PackFM,Token Love Song,2.0
44,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
45,Everyday Sunday,Mess With Your Mind,0.0
46,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
47,Joey McIntyre,Bewitched,0.0
48,The Michael Schenker Group,Ulcer (2009 Digital Remaster),0.0
49,Sandra,Put Your Arms Around Me,110.0
50,Linkin Park,What I've Done (Album Version),45817.0

  Collection: WAR

,artist,title,play_count
1,Kenny G,Santa Claus Is Coming To Town,8.0
2,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
3,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
4,Willie Nelson,Here Comes Santa Claus,0.0
5,Gene Autry,Here Comes Santa Claus,0.0
6,Bob Dylan,Here Comes Santa Claus,0.0
7,Andrea Bocelli,Santa Claus Is Coming To Town,36.0
8,The SA,Santa Claus Is Coming to Town,71.0
9,Patty Loveless,The Boys Are Back In Town,0.0
10,Everclear,The Boys Are Back In Town,836.0
11,Brooks & Dunn,Santa Claus Is Comin' To Town,0.0
12,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
13,The Tractors,The Santa Claus Boogie,0.0
14,The Dubliners,Dirty Old Town,0.0
15,Billy Idol,Run Rudolph Run,60.0
16,Brooks & Dunn,She Likes To Get Out Of Town,0.0
17,The Pure,Rock This Town,0.0
18,Stray Cats,Rock This Town,0.0
19,Del Shannon,Stranger In Town,0.0
20,Adam Brand,Big Old Car,0.0
21,John Martyn,Dancing,0.0
22,Tony Lucca,Devil Town,665.0
23,War,L.A. Sunshine (Single Version),481.0
24,Billy Gilman,There's A New Kid In Town,0.0
25,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,59.0
26,Wishbone Ash,Rock 'N Roll Widow,0.0
27,ENUR Feat NATASJA,Calabria 2007,18045.0
28,The Continentals,Santa Claus Is Back In Town,0.0
29,Hans Theessink,Bourgeois Blues,0.0
30,Lars Frederiksen And The Bastards,Bastards,72.0
31,The Continentals,I Saw Mommy Kissing Santa Claus,0.0
32,Sparks,The Toughest Girl in Town,0.0
33,Dan Colehour,Quarry Town,0.0
34,Phil Vassar,Joe & Rosalita,120.0
35,HOLLY DUNN,Rock-A-Billy,0.0
36,iLiKETRAiNS,Twenty Five Sins,28.0
37,L.A. Guns,Run Rudolph Run,317.0
38,Arthur Conley,Funky Street,91.0
39,Luke Bryan,Run Run Rudolph,487.0
40,Brenda Lee,Christy Christmas,0.0
41,Roy Brown,Good Rocking Tonight,0.0
42,Buck-O-Nine,Tool,31.0
43,Elvis Presley,Good Rockin' Tonight,0.0
44,Sparks,Big Boy,29.0
45,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
46,Mecca Normal,What About The Boy?,0.0
47,Peter and the Test Tube Babies,Boozanza (Single Version),0.0
48,Jimmy Dean,Cajun Queen,0.0
49,George Thorogood & The Destroyers,Restless,0.0
50,David Wilcox,Wilford Brandon Hayes,19.0

  Collection: HAPPINESS

,artist,title,play_count
1,Dionysus,Don't Forget,30.0
2,The Cooper Temple Clause,Head,11.0
3,Stefanie Bennett,I'll Never Forget You,0.0
4,The Outfield,All The Love,301.0
5,From Zero,Undeniable,0.0
6,Saga,Back To The Shadows,1.0
7,Procol Harum,I Keep Forgetting,12.0
8,B3,Where I'll Be,2.0
9,Go:Audio,Forget About It,0.0
10,Danielle Brisebois,Don't Wanna Talk About Love,1.0
11,The Honor System,Saints,45.0
12,Gabrielle,Forget About The World,0.0
13,Guns N' Roses,Think About You,2123.0
14,Carl Belew,Am I That Easy To Forget,2.0
15,Before Dark,It's All About You,0.0
16,Heart,What About Love? (2000 Digital Remaster),0.0
17,Rufio,Don't You Forget About Me,323.0
18,Janet Jackson,What About,85.0
19,Jill Paquette,Forget,0.0
20,Wild Strawberries,I Don't Want To Think About It,147.0
21,Morcheeba,What New York Couples Fight About (KCRW Sessio...,0.0
22,Chrisette Michele,All I Ever Think About,798.0
23,Millencolin,Birdie,311.0
24,Jim Reeves,Am I That Easy To Forget,0.0
25,Ingrid Olava,Headlines,37.0
26,Cake,Never_ Never Gonna Give You Up,1731.0
27,Nico,Never Talk About It,0.0
28,Soulwax,A ballad to forget,481.0
29,Angela Bofill,Something About You,16.0
30,Sandrine,Don't Forget About Me,0.0
31,Paula Abdul,It's All About Feeling Good,0.0
32,Four Year Strong,The Afterglow,0.0
33,SR-71,Goodbye,2.0
34,Finger Eleven,I'll Keep Your Memory Vague,698.0
35,Yellowcard,One Year_ Six Months,2872.0
36,Training For Utopia,Thoughtless Reminders (The Falling Cycle Album...,1.0
37,R. Kelly,When I Think About You,0.0
38,Land Of Talk,Speak To Me Bones,519.0
39,Harry Nilsson,Don't Leave Me,0.0
40,Waylon Jennings,Pretend I Never Happened,0.0
41,All-4-One,Something About You (LP Version),0.0
42,Trisha Yearwood,Thinkin' About You,312.0
43,88 Fingers Louie,Summer Photos,27.0
44,Jimmy Cozier,Two Steps,0.0
45,Janis Joplin,To Love Somebody,0.0
46,Southern Pacific,Thing About You,32.0
47,Natalie Imbruglia,Fun,85.0
48,New Found Glory,Sucker,229.0
49,Elvis Presley,I Forgot To Remember To Forget,0.0
50,Coldfinger,Cover Sleeve,52.0

  Collection: LONELINESS

,artist,title,play_count
1,Laurie Berkner,BOOTS,164.0
2,Bon Jovi,Put The Boy Back In Cowboy,1000.0
3,Bow Wow Wow,Cowboy,0.0
4,Bodyrockers,Keep Your Boots On,11.0
5,The Milkshakes,Boys,0.0
6,Dolly Parton,White Limozeen,0.0
7,Josh Turner,Backwoods Boy,1277.0
8,Randy Houser,Boots On,3375.0
9,Venus,In Dissolvenza (live At suoni E Ultrasuoni_ Rai,0.0
10,Lonestar,Cowboy Girl,0.0
11,Unwound,Fingernails On A Chalkboard,22.0
12,Lou Reed,I Wanna Be Black,0.0
13,Die Fantastischen Vier,Yeah Yeah Yeah,0.0
14,Die Fantastischen Vier,Le Smou,0.0
15,Eric Church,These Boots,4589.0
16,Lloyd Cole,Let's Get Lost,0.0
17,J-Diggs,Dirty Girls,7.0
18,Jon & Vangelis,Back To School,73.0
19,Godhead,Girls and Boys,0.0
20,Ghoti Hook,Cowboy,12.0
21,Sutton Foster,Flight,76.0
22,Ashford & Simpson,High-Rise,0.0
23,Underworld,Born Slippy,0.0
24,Good Charlotte,Girls & Boys,80.0
25,Massive Töne,Cruisen,222.0
26,The Aliens,Robot Man,36.0
27,Eleni Mandell,Miracle of Five,32.0
28,Fettes Brot,Da draussen,720.0
29,Silvertide,Blue Jeans,0.0
30,Samy Deluxe,Sensationell,90.0
31,Erin O'Donnell,Janie's Garden (LP Version),0.0
32,Gorillaz,Man Research (Clapper),2708.0
33,Jill Phillips,Wrecking Ball (Album Version),39.0
34,Red Rider,Through The Curtain,0.0
35,The Wolfmen,Kama Sutra,0.0
36,ZU2T,Der Kapitän,0.0
37,Mason Jennings,Fighter Girl,6.0
38,Quiet Riot,Let's Get Crazy,0.0
39,Lisa Miskovsky,Judas Kiss,0.0
40,Fleetwood Mac,My Baby's Sweet,254.0
41,Gyllene Tider,Teaser Japaneese,77.0
42,67 Special,Hard Kinda Talk,0.0
43,Eko Fresh,Intro,0.0
44,Red Elvises,Sad Cowboy Song,0.0
45,Hot Action Cop,Alayal (Album Version),72.0
46,Yung Berg,Look What You Made Me,0.0
47,Massive Töne,Traumreise (Album Version),512.0
48,Toby Keith,Whiskey Girl,4729.0
49,Dismemberment Plan,The Dismemberment Plan Gets Rich,7.0
50,Illuminate,Requiem,0.0

  Collection: MONEY

,artist,title,play_count
1,Youssoupha,Éternel recommencement,0.0
2,Alain Turban,Drôle de vie,0.0
3,Sinik,Dans le Vif,36.0
4,Dub Incorporation,Face à Soi,74.0
5,Sniper,Visions Chaotiques,27.0
6,Grand Corps Malade,Comme Une Evidence,81.0
7,Svinkels,Front Contre Front,0.0
8,Rohff,La Puissance (Classic),1287.0
9,Shurik'n,Fugitif,68.0
10,Oxmo Puccino,Amour Et Jalousie,32.0
11,Sniper,Fallait que je te dise (radio edit),114.0
12,Khaled,Mauvais Sang,55.0
13,Fonky Family,Mystère Et Suspens,0.0
14,Oxmo Puccino,Mourir 1000 Fois,35.0
15,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
16,Fatals Picards,Au mariage de Kevin et ma soeur [En Public],0.0
17,MYSA,80-07,0.0
18,Rohff,Pervertie,8.0
19,La Fouine,Peace On Earth,0.0
20,Oxmo Puccino,Un Flingue Et Des Roses (Avec Kool Shen),27.0
21,Nessbeal,Les larmes de ce monde,0.0
22,Youssoupha,Toubab,0.0
23,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
24,Sniper,35 heures,0.0
25,Despo' Rutti,Legitime Defense,0.0
26,Dub Incorporation,Petit Soldat,74.0
27,Le Klub Des Loosers,Baise les gens,0.0
28,Le Rat Luciano,Derrière Les Apparences,0.0
29,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
30,Alibi Montana,Fossoyeur,0.0
31,Despo' Rutti,Redemption,0.0
32,Bakar,Pour Les Quartiers feat. Jmi Sissoko,0.0
33,NTM,Le monde de demain,0.0
34,Oxmo Puccino,Parallèles,15.0
35,La Fouine,Mon Autobiographie,0.0
36,Anis,Oisif,98.0
37,Nicolas Bacchus,Les maladies mortelles,0.0
38,Sinik,Ennemi d'Etat,12.0
39,Mac Tyer,Outro,0.0
40,Lara Fabian,Comme Ils Disent,40.0
41,Shurik'n,Lettre,184.0
42,Saian Supa Crew,X raisons (live),6.0
43,Dany Dan,Master,0.0
44,Cali,Roberta (Live Acoustique),0.0
45,Les Sages Poetes De La Rue,Un monde étrange,0.0
46,Julien Clerc,L'assassin Assassiné,7.0
47,Stomy Bugsy,Incendie Dans Mon Paradis,0.0
48,Marcel Mouloudji,Tout lamour que jai,0.0
49,Despo' Rutti,L'Oeil Aux Beurs Noirs,0.0
50,Fonky Family,On Respecte Ca,0.0

============================================================
Classifier: LOGISTIC
============================================================

  Collection: LOVE

,artist,title,play_count
1,JET,L'esprit D'escalier (Digital Album Version),0.0
2,Glenn Hughes,Mistreated,0.0
3,Hughes Turner Project,Mistreated,0.0
4,Let's Go Sailing,Sideways,398.0
5,Whitesnake,Mistreated (Live) (2007 Digital Remaster),383.0
6,Le Tigre,Fake French,233.0
7,Screaming Trees,Dime Western,35.0
8,Mixel Pixel,I've Been Around,0.0
9,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,4.0
10,Neil Young,Jellyroll Man,22.0
11,Ginuwine,Bedda To Have Loved,0.0
12,Infected Mushroom,Tasty Mushroom,263.0
13,Don McLean,Since I Don't Have You,365.0
14,Husker Du,No Promise Have I Made,31.0
15,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
16,Ritchie Family,Brazil,48.0
17,Metronomy,A Thing For Me,1616.0
18,Sophie Zelmani,Got To Stop,0.0
19,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
20,Nil Lara,Bleeding,342.0
21,The Heavy Blinkers,Don't Get Me Wrong,0.0
22,Randy Crawford,I've Never Been To Me (LP Version),0.0
23,Enchant,Despicable,46.0
24,Joe Clay,Annabella,0.0
25,Fozzy,Grail (Album),65.0
26,Marshall Crenshaw,Live it Up,12.0
27,The Germs,Throw It Away,0.0
28,Mike And The Mechanics,Now That You've Gone,154.0
29,The Yardbirds,My Baby (Top Gear),15.0
30,Hot Chocolate,You Could've Been A Lady,36.0
31,Alberta Hunter,You Can't Have It All,0.0
32,A Radio With Guts,Bloodletter,3.0
33,NOFX,No Problems,128.0
34,Eric Burdon,Never give up Blues,20.0
35,Kelly Marie,If I Can't Have You,0.0
36,Lionel Richie,One World,12.0
37,Blessid Union Of Souls,Could've Been With You,57.0
38,The Young Punx,You You You,0.0
39,Chris De Burgh,Missing You,1551.0
40,Miss Li,Take a Shower!,68.0
41,MU330,Oh My God,5.0
42,Skin,Faithfulness,716.0
43,Thea Gilmore,Pontiac To A Home Girl,0.0
44,Patrice Rushen,Haven't You Heard (LP Version),1058.0
45,Low,Stay,7.0
46,The Bees,End Of The Street,850.0
47,Timo Räisänen,With a Mask on,23.0
48,Songs:Ohia,Ghost Tropic,94.0
49,Fleetwood Mac,Coming Home,1620.0
50,Linkin Park,What I've Done (Album Version),45817.0

  Collection: WAR

,artist,title,play_count
1,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
2,Kenny G,Santa Claus Is Coming To Town,8.0
3,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
4,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
5,Everclear,The Boys Are Back In Town,836.0
6,Patty Loveless,The Boys Are Back In Town,0.0
7,The Silencers,Bulletproof heart,134.0
8,iLiKETRAiNS,Twenty Five Sins,28.0
9,Hot Hot Heat,This Town,334.0
10,Del Shannon,Stranger In Town,0.0
11,Tony Lucca,Devil Town,665.0
12,Brooks & Dunn,She Likes To Get Out Of Town,0.0
13,Pitchshifter,Phoenixology,0.0
14,War,L.A. Sunshine (Single Version),481.0
15,The Dubliners,Dirty Old Town,0.0
16,Sparks,The Toughest Girl in Town,0.0
17,O.A.R.,This Town (Album Version),138.0
18,Billy Gilman,There's A New Kid In Town,0.0
19,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,59.0
20,Hans Theessink,Bourgeois Blues,0.0
21,Siouxsie And The Banshees,Running Town,164.0
22,Dan Colehour,Quarry Town,0.0
23,Desmond Dekker,007,1789.0
24,John Leyton,Country Boy,0.0
25,Jason & The Scorchers,Ghost Town,0.0
26,Joe Jackson,Hell of a Town,0.0
27,Lemonhead,Down Town,0.0
28,Wishbone Ash,Rock 'N Roll Widow,0.0
29,Meredith Brooks,My Little Town,62.0
30,The Gone Jackals,Get Outta Town,30.0
31,Milton Mapes,Lonesome Town,123.0
32,Kinesis,Civilised Fury,0.0
33,The Pure,Rock This Town,0.0
34,Fred Eaglesmith,The Rocket,0.0
35,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
36,Andrea Bocelli,Santa Claus Is Coming To Town,36.0
37,Willie Nelson,Here Comes Santa Claus,0.0
38,Gene Autry,Here Comes Santa Claus,0.0
39,Bob Dylan,Here Comes Santa Claus,0.0
40,Cocoa Tea,Sweeter (Album Version),0.0
41,Stray Cats,Rock This Town,0.0
42,Evidence,Out of Town,0.0
43,Lesley Gore,My Town My Guy And Me,0.0
44,John Martyn,Dancing,0.0
45,Odetta,The Fox,0.0
46,Jill Sobule,Happy Town (LP Version),21.0
47,Brooks & Dunn,Santa Claus Is Comin' To Town,0.0
48,Frankie Laine,Strange Lady In Town,0.0
49,Better Than Ezra,Normal Town (LP Version),0.0
50,ENUR Feat NATASJA,Calabria 2007,18045.0

  Collection: HAPPINESS

,artist,title,play_count
1,Dionysus,Don't Forget,30.0
2,Charlotte Gainsbourg,Don't Forget To Forget Me,7.0
3,Procol Harum,I Keep Forgetting,12.0
4,The Honor System,Saints,45.0
5,Stefanie Bennett,I'll Never Forget You,0.0
6,Carl Belew,Am I That Easy To Forget,2.0
7,Saga,Back To The Shadows,1.0
8,The Cooper Temple Clause,Head,11.0
9,Morcheeba,What New York Couples Fight About (KCRW Sessio...,0.0
10,Go:Audio,Forget About It,0.0
11,Sandrine,Don't Forget About Me,0.0
12,Jim Reeves,Am I That Easy To Forget,0.0
13,From Zero,Undeniable,0.0
14,Rufio,Don't You Forget About Me,323.0
15,Jill Paquette,Forget,0.0
16,Divinyls,Siren Song,0.0
17,Engelbert Humperdinck,Am I That Easy To Forget?,0.0
18,Gabrielle,Forget About The World,0.0
19,Beck,Broken Drum,15.0
20,The Inchtabokatables,Keep In Mind,0.0
21,Guns N' Roses,Think About You,2123.0
22,B3,Where I'll Be,2.0
23,The Lamps,Hey Girl,0.0
24,Tricky,You Don't,329.0
25,Yellowcard,One Year_ Six Months,2872.0
26,Of Montreal,Wraith Pinned to the Mist (And Other Games),128.0
27,Korn,Thoughtless,0.0
28,On Thorns I Lay,A Light In Paradise,0.0
29,Sara Gazarek,Yours (Live),0.0
30,4ft Fingers,Emergency Manoeuvre,0.0
31,The Corrs,Someday ( LP Version ),30.0
32,Before Dark,It's All About You,0.0
33,Carolina Liar,Simple Life (Album Version),546.0
34,Danielle Brisebois,Don't Wanna Talk About Love,1.0
35,Heart,What About Love? (2000 Digital Remaster),0.0
36,3-11 Porter,I Can'T Forget The Girl I Never Met,41.0
37,Vienna Teng,The Atheist Christmas Carol,2493.0
38,SR-71,Goodbye,2.0
39,The Outfield,All The Love,301.0
40,Slam,Lifetimes,0.0
41,MxPx,Correct Me If I'm Wrong (Life In General Album...,9.0
42,Elvis Presley,I Forgot To Remember To Forget,0.0
43,Gemma Hayes,At Constant Speed,2.0
44,MDO,So Hard To Forget,0.0
45,Harry Nilsson,Don't Leave Me,0.0
46,Training For Utopia,Thoughtless Reminders (The Falling Cycle Album...,1.0
47,Ruff Endz,Please Don't Forget About Me,0.0
48,Silverstein,Here Today_ Gone Tomorrow (Album Version),469.0
49,Saint Etienne,Hobart Paving,91.0
50,Ingrid Olava,Headlines,37.0

  Collection: LONELINESS

,artist,title,play_count
1,Laurie Berkner,BOOTS,164.0
2,Bodyrockers,Keep Your Boots On,11.0
3,Bon Jovi,Put The Boy Back In Cowboy,1000.0
4,Bow Wow Wow,Cowboy,0.0
5,Eric Church,These Boots,4589.0
6,Unwound,Fingernails On A Chalkboard,22.0
7,Randy Houser,Boots On,3375.0
8,Dolly Parton,White Limozeen,0.0
9,Josh Turner,Backwoods Boy,1277.0
10,The Milkshakes,Boys,0.0
11,Venus,In Dissolvenza (live At suoni E Ultrasuoni_ Rai,0.0
12,Lonestar,Cowboy Girl,0.0
13,Sutton Foster,Flight,76.0
14,J-Diggs,Dirty Girls,7.0
15,The Aliens,Robot Man,36.0
16,Lou Reed,I Wanna Be Black,0.0
17,Godhead,Girls and Boys,0.0
18,Die Fantastischen Vier,Yeah Yeah Yeah,0.0
19,FPI Project,Rich In Paradise,2305.0
20,Múm,Boots of Fog,169.0
21,Lloyd Cole,Let's Get Lost,0.0
22,Joe Ely,The Road Goes On Forever,69.0
23,Erin O'Donnell,Janie's Garden (LP Version),0.0
24,Ashford & Simpson,High-Rise,0.0
25,Gorillaz,Man Research (Clapper),2708.0
26,Eleni Mandell,Miracle of Five,32.0
27,Good Charlotte,Girls & Boys,80.0
28,Jill Phillips,Wrecking Ball (Album Version),39.0
29,Quiet Riot,Let's Get Crazy,0.0
30,Ghoti Hook,Cowboy,12.0
31,Ween,Freedom of '76 (LP Version),1161.0
32,Red Elvises,Sad Cowboy Song,0.0
33,Mason Jennings,Fighter Girl,6.0
34,Silvertide,Blue Jeans,0.0
35,Dismemberment Plan,The Dismemberment Plan Gets Rich,7.0
36,The Wolfmen,Kama Sutra,0.0
37,The Ike Reilly Assassination,The Mixture (Album),2.0
38,French Affair,My boots are made for walking,0.0
39,Gyllene Tider,Teaser Japaneese,77.0
40,The Highwaymen,The Road Goes On Forever,165.0
41,Jon & Vangelis,Back To School,73.0
42,The Young Knives,Walking On The Autobahn,5.0
43,Underworld,Born Slippy,0.0
44,The Replacements,Waitress In The Sky,355.0
45,Die Fantastischen Vier,Le Smou,0.0
46,67 Special,Hard Kinda Talk,0.0
47,Joan Baez,Long Black Veil,0.0
48,Be Bop Deluxe,Kiss Of Light,56.0
49,Shakespears Sister,Excuse Me John,0.0
50,The Libertines,Tomblands,38.0

  Collection: MONEY

,artist,title,play_count
1,Khaled,Mauvais Sang,55.0
2,Dany Dan,Master,0.0
3,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
4,Svinkels,Front Contre Front,0.0
5,Nessbeal,Rimes Instinctives,0.0
6,MYSA,80-07,0.0
7,Sniper,35 heures,0.0
8,Youssoupha,Éternel recommencement,0.0
9,KDD,Orange M.,0.0
10,Michèle Arnaud,Douze belles dans la peau (Gainsbourg),0.0
11,Lara Fabian,Comme Ils Disent,40.0
12,La Fouine,Ma Tabatière (Chronique D'Un Dealer),182.0
13,Sniper,Visions Chaotiques,27.0
14,Michèle Bernard,Ce soir je n'entends rien,0.0
15,Sinik,Ennemi d'Etat,12.0
16,Alibi Montana,Fossoyeur,0.0
17,Shurik'n,Fugitif,68.0
18,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
19,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
20,Benjamin Biolay,La Chambre D'amis,98.0
21,Oxmo Puccino,Un Flingue Et Des Roses (Avec Kool Shen),27.0
22,Nicolas Bacchus,Les maladies mortelles,0.0
23,Rohff,Pervertie,8.0
24,Alain Turban,Drôle de vie,0.0
25,Despo' Rutti,L'Oeil Aux Beurs Noirs,0.0
26,Oxmo Puccino,Amour Et Jalousie,32.0
27,JoeyStarr,Cigarette Piegee,0.0
28,NTM,Le monde de demain,0.0
29,Oldelaf et Monsieur D,Rue de Nantes,0.0
30,Despo' Rutti,Legitime Defense,0.0
31,Les Sages Poetes De La Rue,Un monde étrange,0.0
32,Dub Incorporation,Face à Soi,74.0
33,Le Klub Des Loosers,Baise les gens,0.0
34,Grand Corps Malade,Comme Une Evidence,81.0
35,Nessbeal,Les larmes de ce monde,0.0
36,La Fouine,Peace On Earth,0.0
37,KDD,Jungle Fever,0.0
38,Pierre Perret,La petite Kurde,7.0
39,Fonky Family;BOSS (Boss Of Scandalz Strategyz)...,La Résistance,218.0
40,Aldebert,Tête en l'air (Live),0.0
41,Fonky Family,La Furie Et La Foi,0.0
42,Sinik,Dans le Vif,36.0
43,Marcel Mouloudji,Tout lamour que jai,0.0
44,Mano Solo,Du Vent,0.0
45,Nessbeal,Au Dela De L'horizon,0.0
46,Rohff,La Puissance (Classic),1287.0
47,Thomas Fersen,Croque,214.0
48,Despo' Rutti,Redemption,0.0
49,Georges Brassens,Supplique Pour Etre Enterré A La Plage De Sète,0.0
50,Dub Incorporation,Petit Soldat,74.0

============================================================
Classifier: SGD
============================================================

  Collection: LOVE

,artist,title,play_count
1,JET,L'esprit D'escalier (Digital Album Version),0.0
2,Glenn Hughes,Mistreated,0.0
3,Hughes Turner Project,Mistreated,0.0
4,Let's Go Sailing,Sideways,398.0
5,Whitesnake,Mistreated (Live) (2007 Digital Remaster),383.0
6,Le Tigre,Fake French,233.0
7,Infected Mushroom,Tasty Mushroom,263.0
8,Screaming Trees,Dime Western,35.0
9,Don McLean,Since I Don't Have You,365.0
10,Husker Du,No Promise Have I Made,31.0
11,Neil Young,Jellyroll Man,22.0
12,Mixel Pixel,I've Been Around,0.0
13,Ernest Tubb,Have You Ever Been Lonely (Have You Ever Been ...,4.0
14,Ginuwine,Bedda To Have Loved,0.0
15,Ritchie Family,Brazil,48.0
16,Within Temptation,What Have You Done [feat Keith Caputo] - Live ...,0.0
17,Secret Lives Of The Freemasons,The New Whack (Album Version),0.0
18,Sophie Zelmani,Got To Stop,0.0
19,Metronomy,A Thing For Me,1616.0
20,Nil Lara,Bleeding,342.0
21,Alberta Hunter,You Can't Have It All,0.0
22,The Heavy Blinkers,Don't Get Me Wrong,0.0
23,Enchant,Despicable,46.0
24,Mike And The Mechanics,Now That You've Gone,154.0
25,Kelly Marie,If I Can't Have You,0.0
26,Randy Crawford,I've Never Been To Me (LP Version),0.0
27,Fozzy,Grail (Album),65.0
28,The Germs,Throw It Away,0.0
29,Joe Clay,Annabella,0.0
30,NOFX,No Problems,128.0
31,A Radio With Guts,Bloodletter,3.0
32,Low,Stay,7.0
33,Hot Chocolate,You Could've Been A Lady,36.0
34,Lionel Richie,One World,12.0
35,The Yardbirds,My Baby (Top Gear),15.0
36,Thea Gilmore,Pontiac To A Home Girl,0.0
37,Marshall Crenshaw,Live it Up,12.0
38,MU330,Oh My God,5.0
39,Miss Li,Take a Shower!,68.0
40,Patrice Rushen,Haven't You Heard (LP Version),1058.0
41,Eric Burdon,Never give up Blues,20.0
42,The Young Punx,You You You,0.0
43,Linkin Park,What I've Done (Album Version),45817.0
44,Skin,Faithfulness,716.0
45,Blessid Union Of Souls,Could've Been With You,57.0
46,Hoobastank,Never Saw It Coming,408.0
47,Chris De Burgh,Missing You,1551.0
48,Timo Räisänen,With a Mask on,23.0
49,Twisted Wheel,Let Them Have It All,2.0
50,Fleetwood Mac,Coming Home,1620.0

  Collection: WAR

,artist,title,play_count
1,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
2,The Silencers,Bulletproof heart,134.0
3,iLiKETRAiNS,Twenty Five Sins,28.0
4,Patty Loveless,The Boys Are Back In Town,0.0
5,Del Shannon,Stranger In Town,0.0
6,Hot Hot Heat,This Town,334.0
7,Kenny G,Santa Claus Is Coming To Town,8.0
8,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
9,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
10,Everclear,The Boys Are Back In Town,836.0
11,War,L.A. Sunshine (Single Version),481.0
12,Tony Lucca,Devil Town,665.0
13,Pitchshifter,Phoenixology,0.0
14,Siouxsie And The Banshees,Running Town,164.0
15,Desmond Dekker,007,1789.0
16,Brooks & Dunn,She Likes To Get Out Of Town,0.0
17,Billy Gilman,There's A New Kid In Town,0.0
18,The Dubliners,Dirty Old Town,0.0
19,Hans Theessink,Bourgeois Blues,0.0
20,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,59.0
21,O.A.R.,This Town (Album Version),138.0
22,The Pure,Rock This Town,0.0
23,The Gone Jackals,Get Outta Town,30.0
24,Kinesis,Civilised Fury,0.0
25,Cocoa Tea,Sweeter (Album Version),0.0
26,Sparks,The Toughest Girl in Town,0.0
27,Milton Mapes,Lonesome Town,123.0
28,Fred Eaglesmith,The Rocket,0.0
29,Stray Cats,Rock This Town,0.0
30,John Martyn,Dancing,0.0
31,Wishbone Ash,Rock 'N Roll Widow,0.0
32,Joe Jackson,Hell of a Town,0.0
33,Frankie Laine,Strange Lady In Town,0.0
34,Jason & The Scorchers,Ghost Town,0.0
35,Meredith Brooks,My Little Town,62.0
36,Iggy Pop,Butt Town,8.0
37,Lesley Gore,My Town My Guy And Me,0.0
38,Better Than Ezra,Normal Town (LP Version),0.0
39,Secret Lives Of The Freemasons,Airplanes (Album Version),31.0
40,Dan Colehour,Quarry Town,0.0
41,John Leyton,Country Boy,0.0
42,Lemonhead,Down Town,0.0
43,Abandon Kansas,I Wonder If It's Me (Album Version),0.0
44,ENUR Feat NATASJA,Calabria 2007,18045.0
45,Evidence,Out of Town,0.0
46,Jill Sobule,Happy Town (LP Version),21.0
47,Darden Smith,Love Left Town,0.0
48,The Everly Brothers,Bully Of The Town,0.0
49,Adam Brand,Big Old Car,0.0
50,The Upper Room,All Over This Town,0.0

  Collection: HAPPINESS

,artist,title,play_count
1,Charlotte Gainsbourg,Don't Forget To Forget Me,7.0
2,Dionysus,Don't Forget,30.0
3,Procol Harum,I Keep Forgetting,12.0
4,The Honor System,Saints,45.0
5,Carl Belew,Am I That Easy To Forget,2.0
6,Stefanie Bennett,I'll Never Forget You,0.0
7,Morcheeba,What New York Couples Fight About (KCRW Sessio...,0.0
8,Jim Reeves,Am I That Easy To Forget,0.0
9,Go:Audio,Forget About It,0.0
10,Black My Heart,Did It All,40.0
11,The Inchtabokatables,Keep In Mind,0.0
12,The Cooper Temple Clause,Head,11.0
13,Of Montreal,Wraith Pinned to the Mist (And Other Games),128.0
14,Slipknot,Before I Forget (Album Version),9649.0
15,Divinyls,Siren Song,0.0
16,On Thorns I Lay,A Light In Paradise,0.0
17,Mansun,Dark Mavis,40.0
18,Elvis Presley,I Forgot To Remember To Forget,0.0
19,Journey,Lovin'_ Touchin'_ Squeezin',0.0
20,Sick City,Moving_ Not Moving Forward,0.0
21,Roy Orbison,Land Of 1000 Dances,0.0
22,Gemma Hayes,At Constant Speed,2.0
23,Sandrine,Don't Forget About Me,0.0
24,Hipsway,Something Special,0.0
25,Training For Utopia,Thoughtless Reminders (The Falling Cycle Album...,1.0
26,Engelbert Humperdinck,Am I That Easy To Forget?,0.0
27,VIP,VIP,0.0
28,Talk Talk,It's My Life (Extended Mix) (1998 Digital Rema...,159.0
29,Yellowcard,One Year_ Six Months,2872.0
30,Korn,Thoughtless,0.0
31,Squirtgun,Please Be Mine,1.0
32,Itchy Poopzkid,Lyrically Happy,22.0
33,Blink-182,All The Small Things,0.0
34,Talk Talk,It's So Serious,6.0
35,Avril Lavigne,Slipped Away,0.0
36,Kaiser Chiefs,Na Na Na Na Naa,0.0
37,Birdman,Outro,29.0
38,Pistol,Kill You,0.0
39,Akon,Right Now (Na Na Na) (UK Radio Edit),0.0
40,Brakes,You'll Always Have A Place To Stay,10.0
41,The Corrs,Someday ( LP Version ),30.0
42,Anatomy Of A Ghost,Since Yesterday,6.0
43,Katrina & The Waves,Sun Street,77.0
44,Rufio,Don't You Forget About Me,323.0
45,Dinosaur Jr.,Forget The Swan,454.0
46,Cannibal & The Headhunters,Land Of 1000 Dances,684.0
47,Harry Nilsson,Don't Leave Me,0.0
48,Saint Etienne,Hobart Paving,91.0
49,Hard-FI,Tied Up Too Tight (BBC Radio 1 Live Lounge),0.0
50,The Benjamin Gate,Your Kisses Blind Me (Contact Album Version),3.0

  Collection: LONELINESS

,artist,title,play_count
1,Laurie Berkner,BOOTS,164.0
2,Bodyrockers,Keep Your Boots On,11.0
3,Bon Jovi,Put The Boy Back In Cowboy,1000.0
4,The Milkshakes,Boys,0.0
5,Bow Wow Wow,Cowboy,0.0
6,Eric Church,These Boots,4589.0
7,Yung Berg,Look What You Made Me,0.0
8,Gorillaz,Man Research (Clapper),2708.0
9,Erin O'Donnell,Janie's Garden (LP Version),0.0
10,Die Fantastischen Vier,Yeah Yeah Yeah,0.0
11,J-Diggs,Dirty Girls,7.0
12,Godhead,Girls and Boys,0.0
13,Dolly Parton,White Limozeen,0.0
14,The Wolfmen,Kama Sutra,0.0
15,Good Charlotte,Girls & Boys,80.0
16,Underworld,Born Slippy,0.0
17,Jill Phillips,Wrecking Ball (Album Version),39.0
18,Eleni Mandell,Miracle of Five,32.0
19,Unwound,Fingernails On A Chalkboard,22.0
20,Allan Sherman,Rat Fink (LP Version),10.0
21,French Affair,My boots are made for walking,0.0
22,Shakespears Sister,Excuse Me John,0.0
23,Terrorgruppe,Afterburner (Album version),0.0
24,Lou Reed,I Wanna Be Black,0.0
25,38 Special,Wild-Eyed Southern Boys,0.0
26,Pete Yorn,Atlantic City / Murray,0.0
27,Ween,Freedom of '76 (LP Version),1161.0
28,Lonestar,Cowboy Girl,0.0
29,67 Special,Hard Kinda Talk,0.0
30,Jackie Wilson,Give Me You,0.0
31,Ayabie,Japanese Rourezo Caramel Town,0.0
32,Blue Oyster Cult,Teen Archer,0.0
33,Gyllene Tider,Teaser Japaneese,77.0
34,Venus,In Dissolvenza (live At suoni E Ultrasuoni_ Rai,0.0
35,Silvertide,Blue Jeans,0.0
36,Survivor,Seconds Away,0.0
37,Adina Howard,Nasty Grind,418.0
38,Stacie Orrico,You Restore My Soul (Genuine Album Version),91.0
39,Norma Jean,Face:Face (Bless The Martyr Album Version),348.0
40,Mason Jennings,Fighter Girl,6.0
41,Eugenius,Molly's Lips,0.0
42,Susanna Hoffs,Boys Keep Swinging,0.0
43,Zombina & The Skeletones,Janie's Got a Dissolvo Ray,0.0
44,Lucinda Williams,Memphis Pearl (LP Version),2.0
45,Randy Houser,Boots On,3375.0
46,The Doors,Twentieth Century Fox ( LP Version ),0.0
47,Josh Turner,Backwoods Boy,1277.0
48,Skids,Hurry On Boys (2007 Digital Remaster),19.0
49,Liz Phair,X-Ray Man,166.0
50,Millencolin,Man Or Mouse (Album Version),574.0

  Collection: MONEY

,artist,title,play_count
1,Benjamin Biolay,La Chambre D'amis,98.0
2,Isabelle Adjani,Ohio,36.0
3,Michèle Arnaud,Douze belles dans la peau (Gainsbourg),0.0
4,La Fouine,Ma Tabatière (Chronique D'Un Dealer),182.0
5,Les Innocents,Une Vie Moins Ordinaire,806.0
6,Dany Dan,Master,0.0
7,Joe Dassin,La luzerne,0.0
8,Oldelaf et Monsieur D,Rue de Nantes,0.0
9,Thomas Fersen,Pickpocket,31.0
10,Michèle Bernard,Ce soir je n'entends rien,0.0
11,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
12,Billy Ze Kick et Les Gamins En Folie,Ma petite dépression,48.0
13,Thomas Fersen,Croque,214.0
14,Svinkels,Front Contre Front,0.0
15,JoeyStarr,Cigarette Piegee,0.0
16,Nessbeal,Rimes Instinctives,0.0
17,Khaled,Mauvais Sang,55.0
18,Lara Fabian,Comme Ils Disent,40.0
19,Garou,Gitan,0.0
20,La Rue Kétanou,Déchirer Ma Mémoire,245.0
21,Alibi Montana,Fossoyeur,0.0
22,Thomas Fersen,Monsieur Live,0.0
23,Vulgaires Machins,A (Live),0.0
24,Edith Piaf,Un Refrain Courait Dans La Rue,0.0
25,Thomas Fersen,L'Escalier Live,0.0
26,Renan Luce,Repenti,301.0
27,Ariane Moffatt,Se Perdre,0.0
28,Alain Turban,Drôle de vie,0.0
29,MYSA,80-07,0.0
30,Olivia Ruiz,L'Absente,165.0
31,Sniper,35 heures,0.0
32,Les Sages Poetes De La Rue,Un monde étrange,0.0
33,Nessbeal,Au Dela De L'horizon,0.0
34,Patrick Bruel,Voulez-Vous,0.0
35,Fatals Picards,Moi je vis chez Amélie Poulain,0.0
36,Mano Solo,Du Vent,0.0
37,Dany Brillant,Suzette,82.0
38,Aimable,Sombreros et Mantilles,0.0
39,LOFOFORA,Vice Et Rale,0.0
40,Yann Perreau,Soul Circus,0.0
41,Anis,La Preuve Par 1000 (Mahlich Boy),96.0
42,Mes Aïeux,Notre-Dame-du-Bon-Conseil,12.0
43,Les Ogres De Barback,L'education du corps des porcs,41.0
44,Aldebert,Tête en l'air (Live),0.0
45,Jean Ferrat,L'adresse du bonheur,0.0
46,Nicolas Bacchus,Les maladies mortelles,0.0
47,Pleymo,Galaxie Autarcie,0.0
48,Benjamin Biolay,Sous Le Soleil Du Mois D'août,3.0
49,Maxime Le Forestier,Education Sentimentale,0.0
50,Tagada Jones,Camisole,0.0

============================================================
Classifier: FOREST
============================================================

  Collection: LOVE

,artist,title,play_count
1,Clawfinger,Runner Boy,59.0
2,Clawfinger,Life Will Kill You,13.0
3,Maxwell,Arroz Con Pollo,0.0
4,Clawfinger,The Best & The Worst,0.0
5,Maxwell,Eachhoureachsecondeachminuteeachday:Of My Life,0.0
6,Geri,Superstar,0.0
7,Flaw,You've Changed,169.0
8,S Club 7,Stronger,81.0
9,Jason Mraz,Traveler / Make It Mine (Live On Earth Version),202.0
10,Leana,I Just Died In Your Arms Tonight,6.0
11,Cutting Crew,(I Just) Died In Your Arms,0.0
12,Leela James,Good Time [Groove Junkies MoHo Vox],132.0
13,K-Ci & JoJo,Love Ballad,80.0
14,Andrew W.K.,The Party God,26.0
15,Don Johnson,Lonely Too Long,0.0
16,Jeremiah Freed,Wait For Me,0.0
17,Martha Reeves,I've Got To Use My Imagination,0.0
18,Dhany,What You Do To Me,0.0
19,Maxwell,This Woman's Work,3601.0
20,Patrice Rushen,Haven't You Heard (LP Version),1058.0
21,Albert Hammond Jr.,Holiday,301.0
22,Keith Sweat,What Goes Around (LP Version),35.0
23,Justin Tubb,Be Glad,2.0
24,Mary Black,God Bless The Child,0.0
25,Re:hab,Find My Way,0.0
26,Buddy Jewell,I Can Get By,0.0
27,Fleetwood Mac,Coming Home,1620.0
28,Whitesnake,Mistreated (Live) (2007 Digital Remaster),383.0
29,Margaret Becker,All I Ever Wanted,121.0
30,Kimya Dawson,All I Want Is You (Album Version),50.0
31,The Regiment,Take It Back,0.0
32,Robin S,Show Me Love,0.0
33,Vipers,Maggie May,0.0
34,Tree63,Look What You've Done,300.0
35,Jason Mraz,Butterfly [Live From Highline Ballroom],0.0
36,Glenn Hughes,Mistreated,0.0
37,James Blunt,Goodbye My Lover (Live at 93 East),0.0
38,Hughes Turner Project,Mistreated,0.0
39,James Taylor,Fire And Rain,9026.0
40,The Stone Roses,Tears,432.0
41,Neil Sedaka,Happy Birthday_ Sweet Sixteen,118.0
42,Dinosaur Jr,Seemed Like The Thing To Do,112.0
43,Sammi Smith,Fire and Rain,2.0
44,The Bar-Kays,I Thank You,3.0
45,Kleiton & Kledir,Mamma mia,0.0
46,Billy Joel,The Entertainer,0.0
47,Nirvana,Been A Son,8261.0
48,Joni Mitchell,This Flight Tonight (LP Version),1028.0
49,The Jets,Crush On You,992.0
50,Hellsongs,Jump,46.0

  Collection: WAR

,artist,title,play_count
1,Kenny G,Santa Claus Is Coming To Town,8.0
2,All-4-One,Santa Claus Is Coming To Town (LP Version),0.0
3,Matt Belsante,Santa Claus Is Coming To Town (White Christmas...,0.0
4,Everclear,The Boys Are Back In Town,836.0
5,The Pure,Rock This Town,0.0
6,Stray Cats,Rock This Town,0.0
7,Tom T. Hall,A Million Miles To The City,42.0
8,Tony Lucca,Devil Town,665.0
9,The Clash,Last Gang In Town,399.0
10,Johnny Cash,The Night Hank Williams Came To Town,0.0
11,Iggy Pop,Butt Town,8.0
12,Patty Loveless,The Boys Are Back In Town,0.0
13,ENUR Feat NATASJA,Calabria 2007,18045.0
14,Thea Gilmore,My Own Private Riot,8.0
15,Billy Gilman,There's A New Kid In Town,0.0
16,Frankie Laine,Strange Lady In Town,0.0
17,Brian Wilson,Country Feelin's,0.0
18,The Clash,Clash City Rockers,0.0
19,Webb Pierce,In the Jailhouse now,310.0
20,Alan Jackson duet with Keith Whitley,There's A New Kid In Town,59.0
21,The Gone Jackals,Get Outta Town,30.0
22,They Might Be Giants,They Got Lost,0.0
23,Snot,Snot,329.0
24,The Vogues,Magic Town,63.0
25,Andrea Bocelli,Santa Claus Is Coming To Town,36.0
26,Swingin' Utters,Reggae Gets Big In A Small Town,19.0
27,Mississippi John Hurt,Hot Time In Old Town Tonight,0.0
28,Brooks & Dunn,She Likes To Get Out Of Town,0.0
29,The Dubliners,Dirty Old Town,0.0
30,Aviator,Dancing Bear,0.0
31,The Brian Setzer Orchestra,Hey_ Louis Prima,142.0
32,The Most Serene Republic,Phages,20.0
33,Odetta,The Fox,0.0
34,Hans Theessink,Bourgeois Blues,0.0
35,George Thorogood & The Destroyers,Restless,0.0
36,Empire Of The Sun,Delta Bay,0.0
37,Rogue Wave,Phonytown,44.0
38,Lucky Soul,Love3,7.0
39,Woody Guthrie,Vigilante Man,0.0
40,Red Foley,Midnight,0.0
41,The Enemy,We'll Live And Die In These Towns,302.0
42,Milton Mapes,Lonesome Town,123.0
43,The Replacements,Lay It Down Clown,93.0
44,Bachman-Turner Overdrive,Stonegates,60.0
45,Tift Merritt,Laid A Highway,21.0
46,Sparks,The Toughest Girl in Town,0.0
47,The Enemy,Images (Live),0.0
48,John Martyn,Dancing,0.0
49,Jimmy Buffett,Fins,2838.0
50,The Academy Is...,Paper Chase (Album Version),456.0

  Collection: HAPPINESS

,artist,title,play_count
1,Slipknot,Before I Forget (Album Version),9649.0
2,Dionysus,Don't Forget,30.0
3,Enrique Iglesias,Addicted,0.0
4,Ruff Endz,Please Don't Forget About Me,0.0
5,DMX / Regina Bell,Angel (Featuring Regina Bell),1020.0
6,Belleruche,Alice,801.0
7,P. Diddy,Making It Hard Featuring Mary J. Blige (Amende...,184.0
8,The Emotions,I Don't Wanna Lose Your Love,178.0
9,KRS-One,What's Your Plan?,2.0
10,Elliott Smith,Coast to Coast,942.0
11,Leonard Cohen,Hallelujah,0.0
12,Alicia Keys,You Don't Know My Name,0.0
13,DMX,Do You Feel,0.0
14,Faith Hill,Somebody Stand By Me (Album Version),0.0
15,Musiq,Previouscats,659.0
16,Brian McKnight,The Day The Earth Stood Still,429.0
17,The Fray,Syndicate,406.0
18,Justin Timberlake,What Goes Around...Comes Around,326.0
19,Tiffany Evans featuring Bow Wow,I'm Grown,185.0
20,Adam Sandler,I'm So Wasted (Album Version),69.0
21,Ashanti,U Say_ I Say,66.0
22,Third Eye Blind,Crystal Baller [Explicit Version],31.0
23,Alexia,Happy,22.0
24,Fallen From the Sky,Dead Wrong,0.0
25,Goat,I'll Be Good,0.0
26,Tracy Nelson,Walk Away,0.0
27,Jonas Brothers,Still In Love With You,3418.0
28,G. Love & Special Sauce,Baby's Got Sauce,3085.0
29,The Honorary Title,Petals,380.0
30,Midtown,Become What You Hate,307.0
31,The Flying Pickets,I Heard It Through The Grapevine,220.0
32,Kate Voegele,Devil In Me,142.0
33,Lyrics Born,Love Me So Bad,46.0
34,Ambrosia,Dancin' By Myself (Album Version),18.0
35,Beck,Broken Drum,15.0
36,Louise,Reminds Me Of You,0.0
37,Jason Mraz,Did You Get My Message? (feat. Rachael Yamagata),0.0
38,Sister Hazel,Boy Next Door (Album),0.0
39,Gabrielle,Forget About The World,0.0
40,Omarion,O,0.0
41,King Curtis,The Shake (LP Version),0.0
42,Common,Forever Begins,0.0
43,Dave Edmunds,Girls Talk,0.0
44,Ray J,Anytime,654.0
45,Backstreet Boys,Set Adrift On Memory Bliss,506.0
46,Strung Out,Gear Box,487.0
47,Dr. Buzzard's Original Savannah Band,I'll Play The Fool,228.0
48,Musiq,Thereason,210.0
49,Dilated Peoples,Self Defense,136.0
50,Kid Frost,No Sunshine,111.0

  Collection: LONELINESS

,artist,title,play_count
1,Company Flow,8 Steps To Perfection,802.0
2,Mobb Deep,Backstage Pass,834.0
3,Kool Moe Dee,I'm Hittin' Hard,0.0
4,Patti Smith Group,Piss Factory,254.0
5,Extreme,Wind Me Up,94.0
6,Sutton Foster,Flight,76.0
7,Nelly,Batter Up (Full Phat Remix),0.0
8,Kool G Rap,Ghetto Knows,0.0
9,Krayzie Bone,I Don't Give A F**k,0.0
10,Albert King,Blues Power,0.0
11,Weird Al Yankovic,Albuquerque,1040.0
12,Jin,Thank You (Edited),73.0
13,Mobb Deep featuring NOYD,Can't Fuck Wit,72.0
14,Ted Nugent,Fred Bear (LP Version),30.0
15,Felt,Felt Chewed Up (Instrumental),0.0
16,Tha Alkaholiks,Last Call,0.0
17,Janis Joplin,Ego Rock,0.0
18,Akela,Black Jesus,0.0
19,Dead Prez,W-4,203.0
20,Lou Reed,The Cask (Album Version),42.0
21,Javine,Definition Of A Man,26.0
22,SPICE 1,Snitch Killas,8.0
23,T.I.,Chillin With My Bitch (Featuring Jazze Pha) (E...,0.0
24,Ty Herndon,Pray For Me,0.0
25,Randy Houser,Boots On,3375.0
26,Atmosphere,Trying To Find A Balance,3321.0
27,Atmosphere,Flesh,329.0
28,Vanilla Ice,Stop That Train,238.0
29,UGK (Underground Kingz),One Day,70.0
30,Silkk The Shocker,You Ain't Gotta Lie To Kick It,13.0
31,Adam Sandler,Pibb Goes Surfing (Album Version),5.0
32,Consequence,Job Song,3.0
33,Daz Dillinger,When Ya Lease Expected It,1.0
34,Nikita,Give Me,0.0
35,Chipmunk,Role Model,0.0
36,Nappy Roots,Ballin' On A Budget [Tight Vocal Up Version],0.0
37,Assassin,Live or Die,0.0
38,Shelby Lynne,Jesus On A Greyhound,0.0
39,Twista,Get Me (Explicit Album Version),0.0
40,Atmosphere,Hair,0.0
41,Big Punisher featuring Fat Joe,Twinz (Deep Cover 98),1595.0
42,Gym Class Heroes,Pertrified Life And The Twice Told Joke [Decre...,522.0
43,MARC COHN,Saving The Best For Last (LP Version),146.0
44,Sundowner,Jackson Underground,114.0
45,John Prine,My Darlin' Hometown,80.0
46,Masta Killa,East M.C.'s,21.0
47,Latif,Girl,9.0
48,Keith Sweat,I'll Trade (A Million Bucks) (Remix),8.0
49,Streetwize,My Name Is,3.0
50,Knoc-Turn'al,Peepin' Tom (Early Fade),0.0

  Collection: MONEY

,artist,title,play_count
1,La Fouine,Ma Tabatière (Chronique D'Un Dealer),182.0
2,Anis,La Preuve Par 1000 (Mahlich Boy),96.0
3,Sniper,Y'a Pas De Mérite,78.0
4,Seth Gueko,J'oublierai Pas,52.0
5,Abd Al Malik,Soldat De Plomb,48.0
6,Sniper,Hall Story,45.0
7,Le Klub des 7,L'appel,45.0
8,Lara Fabian,Comme Ils Disent,40.0
9,Abd Al Malik,La Gravité,37.0
10,Sniper,Visions Chaotiques,27.0
11,Mano Solo,Du Vent,0.0
12,Les Sages Poetes De La Rue,Un noir tue un noir,0.0
13,Expression Direkt,Krapulax,0.0
14,Despo' Rutti,Legitime Defense,0.0
15,Iron Sy,Mon opinion,0.0
16,Les Sages Poetes De La Rue,L'histoire commence en partant du zéro,0.0
17,MYSA,80-07,0.0
18,La Fouine,Mon Autobiographie,0.0
19,Oldelaf et Monsieur D,Rue de Nantes,0.0
20,Deka,La violence,0.0
21,Svinkels,Front Contre Front,0.0
22,Les Sages Poetes De La Rue,Teknik dans la peau,0.0
23,La Fouine,Fouiny Flow,0.0
24,Nessbeal,Au Dela De L'horizon,0.0
25,Thomas Fersen,Monsieur Live,0.0
26,Véronique Sanson,Mi-Maître_ Mi-Esclave [Olympia 2005],0.0
27,Booba,Le Météore,441.0
28,Jacques Higelin,Banlieue Boogie Blues (Remasterisé En 2007),404.0
29,Georges Brassens,Le Pornographe,361.0
30,Renan Luce,Repenti,301.0
31,La Rue Kétanou,Déchirer Ma Mémoire,245.0
32,Thomas Fersen,Croque,214.0
33,Renan Luce,Je Suis Une Feuille,143.0
34,Fonky Family,La Guerre,139.0
35,Benjamin Biolay,La Chambre D'amis,98.0
36,Dany Brillant,Suzette,82.0
37,Grand Corps Malade,Comme Une Evidence,81.0
38,Sinik,Dans le Vif,36.0
39,Anis,Le Sommeil,35.0
40,Oxmo Puccino,Amour Et Jalousie,32.0
41,Rohff,Enculé De Ton Clash (Avec Soundkail),23.0
42,Le Klub des 7,Pouilleux massacreur,19.0
43,Julien Clerc,L'assassin Assassiné,7.0
44,Svinkels,Ultras festifs,4.0
45,3ème Oeil,Opérationnel,0.0
46,KDD,Jungle Fever,0.0
47,Don Choa,Toute La Nuit,0.0
48,Despo' Rutti,Redemption,0.0
49,Miossec,Au Haut Du Mat,0.0
50,Jacques Brel,Les Timides,0.0

peak RSS : 5412 MB

In [13]:
# overlap summary between the three approaches
def summarize(df):
    if df is None or len(df) == 0:
        return 0, set()
    return len(df), set(zip(df["artist"], df["title"]))

methods = [("baseline", baseline_results), ("w2v", w2v_results)]
methods += [(f"clf_{name}", clf_results[name]) for name in classifiers]

rows = {}
for kw in KEYWORDS:
    rows[kw.upper()] = {label: summarize(res.get(kw))[0] for label, res in methods}
display(__import__("pandas").DataFrame(rows).T)

            baseline  w2v  clf_nb  clf_logistic  clf_sgd  clf_forest
LOVE              50   50      50            50       50          50
WAR               50    0      50            50       50          50
HAPPINESS         50   14      50            50       50          50
LONELINESS        50    1      50            50       50          50
MONEY             50   33      50            50       50          50

---
## 4. Collaborative filtering (implicit ALS)

Matrix factorization (Hu, Koren & Volinsky 2008) on the sparse
user×song matrix, evaluated with precision@10.

In [14]:
# free the lyrics table before ALS so peak memory stays low
del rs.lyrics_long
gc.collect()

user_item, user_idx, song_idx, idx_song = build_user_item_matrix(rs)
print(f"user×song matrix : {user_item.shape}  (nnz={user_item.nnz:,})")
print(f"peak RSS         : {rss_mb()} MB")

user×song matrix : (1019318, 384546)  (nnz=48,373,586)
peak RSS         : 5716 MB

In [15]:
train, test = implicit_split(user_item, train_percentage=0.8, random_state=42)
print(f"train nnz : {train.nnz:,}")
print(f"test  nnz : {test.nnz:,}")

train nnz : 38,702,352
test  nnz : 9,671,234

In [ ]:
model = fit_als(train, factors=192, regularization=0.09, alpha=1.0, iterations=25)
print(f"peak RSS : {rss_mb()} MB")

/home/samy/MySpotify/.venv/lib/python3.12/site-packages/implicit/cpu/als.py:96: RuntimeWarning: OpenBLAS is configured to use 28 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
 16%|█▌        | 4/25 [00:32<02:43,  7.78s/it]

### 4a — User-based recommendations (latent factors)

The eval user `b7815dbb206eb2831ce0fe040d0aa537e2e800f7` — the list must
contain 10 tracks the user has **not** already listened to.

In [ ]:
EVAL_USER = "b7815dbb206eb2831ce0fe040d0aa537e2e800f7"
recs_user = recommend_users_df(
    EVAL_USER, model, user_item, user_idx, idx_song, rs.tracks, top_n=10
)
print(f"10 recommendations for user {EVAL_USER}:")
display(recs_user)

heard = set(rs.triplets.loc[rs.triplets["user_id"] == EVAL_USER, "song_id"])
uid = user_idx[EVAL_USER]
new_ids, _ = model.recommend(uid, user_item[uid], N=10)
new = {idx_song[i] for i in new_ids}
print(f"already-listened tracks in the list: {len(heard & new)} (must be 0)")

### 4b — Similar tracks (item-based CF)

The eval track `SOWYSKH12AF72A303A` — the list must contain 10 tracks and must
**not** contain the seed itself.

In [ ]:
EVAL_SONG = "SOWYSKH12AF72A303A"
recs_item = recommend_tracks_df(
    EVAL_SONG, model, song_idx, idx_song, rs.tracks, top_n=10
)
print(f"10 similar tracks to {EVAL_SONG}:")
display(recs_item)
sid = song_idx[EVAL_SONG]
sim_ids, _ = model.similar_items(sid, N=11)
seed_in_list = any(idx_song[i] == EVAL_SONG for i in sim_ids[1:])
print(f"seed in the list: {seed_in_list} (must be False)")

### Precision@10 — user-based CF

`precision@10` must be greater than 10%.

In [ ]:
pk = evaluate_user_cf(model, train, test, top_n=10)
print(f"mean precision@10 : {pk:.4f} (> 0.10)  -> {'PASS' if pk > 0.10 else 'FAIL'}")
print(f"peak RSS          : {rss_mb()} MB")

---
## Done

All four tasks run on pandas DataFrames parsed **in place from the uncleaned raw
files** (`data/raw`) — nothing is cleaned or saved to disk.

| Task | Output | RSS |
|------|--------|-----|
| Top-250 | 250 most-played songs (global + per-user) | see prints above |
| Top-100 by genre | Rock / Rap / Electronic lists | |
| Collections | 50 songs per keyword (baseline, w2v, classification) | |
| Collaborative filtering | ALS model, user & item recommendations, p@k | |